// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package personaappapi_auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Entities
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNKNOWN AccountType = 0
	AccountType_ACCOUNT_TYPE_COMPANY AccountType = 1
	AccountType_ACCOUNT_TYPE_PERSONA AccountType = 2
	AccountType_ACCOUNT_TYPE_ADMIN   AccountType = 3
)

var AccountType_name = map[int32]string{
	0: "ACCOUNT_TYPE_UNKNOWN",
	1: "ACCOUNT_TYPE_COMPANY",
	2: "ACCOUNT_TYPE_PERSONA",
	3: "ACCOUNT_TYPE_ADMIN",
}

var AccountType_value = map[string]int32{
	"ACCOUNT_TYPE_UNKNOWN": 0,
	"ACCOUNT_TYPE_COMPANY": 1,
	"ACCOUNT_TYPE_PERSONA": 2,
	"ACCOUNT_TYPE_ADMIN":   3,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

// Register
type RegisterRequest struct {
	Email                string      `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string      `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string      `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AccountType          AccountType `protobuf:"varint,4,opt,name=account_type,json=accountType,proto3,enum=personaappapi.auth.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNKNOWN
}

type RegisterResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// Login
type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// Logout
type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{4}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{5}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

// Refresh
type RefreshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{6}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

type RefreshResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{7}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

func (m *RefreshResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// GetSelf
type GetSelfRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSelfRequest) Reset()         { *m = GetSelfRequest{} }
func (m *GetSelfRequest) String() string { return proto.CompactTextString(m) }
func (*GetSelfRequest) ProtoMessage()    {}
func (*GetSelfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{8}
}

func (m *GetSelfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSelfRequest.Unmarshal(m, b)
}
func (m *GetSelfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSelfRequest.Marshal(b, m, deterministic)
}
func (m *GetSelfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSelfRequest.Merge(m, src)
}
func (m *GetSelfRequest) XXX_Size() int {
	return xxx_messageInfo_GetSelfRequest.Size(m)
}
func (m *GetSelfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSelfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSelfRequest proto.InternalMessageInfo

type GetSelfResponse struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string      `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string      `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	AccountType          AccountType `protobuf:"varint,4,opt,name=account_type,json=accountType,proto3,enum=personaappapi.auth.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSelfResponse) Reset()         { *m = GetSelfResponse{} }
func (m *GetSelfResponse) String() string { return proto.CompactTextString(m) }
func (*GetSelfResponse) ProtoMessage()    {}
func (*GetSelfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{9}
}

func (m *GetSelfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSelfResponse.Unmarshal(m, b)
}
func (m *GetSelfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSelfResponse.Marshal(b, m, deterministic)
}
func (m *GetSelfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSelfResponse.Merge(m, src)
}
func (m *GetSelfResponse) XXX_Size() int {
	return xxx_messageInfo_GetSelfResponse.Size(m)
}
func (m *GetSelfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSelfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSelfResponse proto.InternalMessageInfo

func (m *GetSelfResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetSelfResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetSelfResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetSelfResponse) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNKNOWN
}

// Update email
type UpdateEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{10}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateEmailRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateEmailResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailResponse) Reset()         { *m = UpdateEmailResponse{} }
func (m *UpdateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailResponse) ProtoMessage()    {}
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{11}
}

func (m *UpdateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailResponse.Unmarshal(m, b)
}
func (m *UpdateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailResponse.Merge(m, src)
}
func (m *UpdateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailResponse.Size(m)
}
func (m *UpdateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailResponse proto.InternalMessageInfo

func (m *UpdateEmailResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// Update phone
type UpdatePhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePhoneRequest) Reset()         { *m = UpdatePhoneRequest{} }
func (m *UpdatePhoneRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePhoneRequest) ProtoMessage()    {}
func (*UpdatePhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{12}
}

func (m *UpdatePhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePhoneRequest.Unmarshal(m, b)
}
func (m *UpdatePhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePhoneRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePhoneRequest.Merge(m, src)
}
func (m *UpdatePhoneRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePhoneRequest.Size(m)
}
func (m *UpdatePhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePhoneRequest proto.InternalMessageInfo

func (m *UpdatePhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdatePhoneRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePhoneResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePhoneResponse) Reset()         { *m = UpdatePhoneResponse{} }
func (m *UpdatePhoneResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePhoneResponse) ProtoMessage()    {}
func (*UpdatePhoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{13}
}

func (m *UpdatePhoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePhoneResponse.Unmarshal(m, b)
}
func (m *UpdatePhoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePhoneResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePhoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePhoneResponse.Merge(m, src)
}
func (m *UpdatePhoneResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePhoneResponse.Size(m)
}
func (m *UpdatePhoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePhoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePhoneResponse proto.InternalMessageInfo

func (m *UpdatePhoneResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// Update password
type UpdatePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{14}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{15}
}

func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(m, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

func (m *UpdatePasswordResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

// Recovery email
type RecoveryPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoveryPasswordRequest) Reset()         { *m = RecoveryPasswordRequest{} }
func (m *RecoveryPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*RecoveryPasswordRequest) ProtoMessage()    {}
func (*RecoveryPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{16}
}

func (m *RecoveryPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoveryPasswordRequest.Unmarshal(m, b)
}
func (m *RecoveryPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoveryPasswordRequest.Marshal(b, m, deterministic)
}
func (m *RecoveryPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoveryPasswordRequest.Merge(m, src)
}
func (m *RecoveryPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_RecoveryPasswordRequest.Size(m)
}
func (m *RecoveryPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoveryPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoveryPasswordRequest proto.InternalMessageInfo

func (m *RecoveryPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RecoveryPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoveryPasswordResponse) Reset()         { *m = RecoveryPasswordResponse{} }
func (m *RecoveryPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*RecoveryPasswordResponse) ProtoMessage()    {}
func (*RecoveryPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{17}
}

func (m *RecoveryPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoveryPasswordResponse.Unmarshal(m, b)
}
func (m *RecoveryPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoveryPasswordResponse.Marshal(b, m, deterministic)
}
func (m *RecoveryPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoveryPasswordResponse.Merge(m, src)
}
func (m *RecoveryPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_RecoveryPasswordResponse.Size(m)
}
func (m *RecoveryPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoveryPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoveryPasswordResponse proto.InternalMessageInfo

// Update password by secret
type UpdatePasswordBySecretRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordBySecretRequest) Reset()         { *m = UpdatePasswordBySecretRequest{} }
func (m *UpdatePasswordBySecretRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordBySecretRequest) ProtoMessage()    {}
func (*UpdatePasswordBySecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{18}
}

func (m *UpdatePasswordBySecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordBySecretRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordBySecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordBySecretRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordBySecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordBySecretRequest.Merge(m, src)
}
func (m *UpdatePasswordBySecretRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordBySecretRequest.Size(m)
}
func (m *UpdatePasswordBySecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordBySecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordBySecretRequest proto.InternalMessageInfo

func (m *UpdatePasswordBySecretRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *UpdatePasswordBySecretRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UpdatePasswordBySecretResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordBySecretResponse) Reset()         { *m = UpdatePasswordBySecretResponse{} }
func (m *UpdatePasswordBySecretResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordBySecretResponse) ProtoMessage()    {}
func (*UpdatePasswordBySecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{19}
}

func (m *UpdatePasswordBySecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordBySecretResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordBySecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordBySecretResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordBySecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordBySecretResponse.Merge(m, src)
}
func (m *UpdatePasswordBySecretResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordBySecretResponse.Size(m)
}
func (m *UpdatePasswordBySecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordBySecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordBySecretResponse proto.InternalMessageInfo

func (m *UpdatePasswordBySecretResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Token struct {
	Token                string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AccountType          AccountType          `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=personaappapi.auth.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{20}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *Token) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNKNOWN
}

func init() {
	proto.RegisterEnum("personaappapi.auth.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*RegisterRequest)(nil), "personaappapi.auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "personaappapi.auth.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "personaappapi.auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "personaappapi.auth.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "personaappapi.auth.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "personaappapi.auth.LogoutResponse")
	proto.RegisterType((*RefreshRequest)(nil), "personaappapi.auth.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "personaappapi.auth.RefreshResponse")
	proto.RegisterType((*GetSelfRequest)(nil), "personaappapi.auth.GetSelfRequest")
	proto.RegisterType((*GetSelfResponse)(nil), "personaappapi.auth.GetSelfResponse")
	proto.RegisterType((*UpdateEmailRequest)(nil), "personaappapi.auth.UpdateEmailRequest")
	proto.RegisterType((*UpdateEmailResponse)(nil), "personaappapi.auth.UpdateEmailResponse")
	proto.RegisterType((*UpdatePhoneRequest)(nil), "personaappapi.auth.UpdatePhoneRequest")
	proto.RegisterType((*UpdatePhoneResponse)(nil), "personaappapi.auth.UpdatePhoneResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "personaappapi.auth.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "personaappapi.auth.UpdatePasswordResponse")
	proto.RegisterType((*RecoveryPasswordRequest)(nil), "personaappapi.auth.RecoveryPasswordRequest")
	proto.RegisterType((*RecoveryPasswordResponse)(nil), "personaappapi.auth.RecoveryPasswordResponse")
	proto.RegisterType((*UpdatePasswordBySecretRequest)(nil), "personaappapi.auth.UpdatePasswordBySecretRequest")
	proto.RegisterType((*UpdatePasswordBySecretResponse)(nil), "personaappapi.auth.UpdatePasswordBySecretResponse")
	proto.RegisterType((*Token)(nil), "personaappapi.auth.Token")
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2) }

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0xd3, 0x4a,
	0x10, 0xbd, 0x4e, 0x6e, 0xfa, 0x31, 0xe9, 0x4d, 0x72, 0x97, 0x52, 0x82, 0xa5, 0xd2, 0xd6, 0x45,
	0x50, 0x0a, 0x72, 0x44, 0x78, 0xe2, 0xad, 0x4e, 0x68, 0xab, 0x8a, 0xd6, 0x09, 0x6e, 0x22, 0x54,
	0x24, 0x88, 0xdc, 0x64, 0x9b, 0x58, 0x38, 0xde, 0xc5, 0xde, 0x50, 0xf2, 0xc4, 0x6f, 0xe0, 0x1d,
	0x7e, 0x0f, 0x7f, 0x0b, 0xd9, 0x5e, 0x27, 0xb6, 0xe3, 0xb8, 0x6d, 0xc4, 0x4b, 0xa5, 0x99, 0x39,
	0x73, 0xf6, 0x4c, 0x76, 0xe7, 0xb8, 0x50, 0xd4, 0x47, 0x6c, 0x50, 0x71, 0xff, 0xc8, 0xd4, 0x26,
	0x8c, 0x20, 0x44, 0xb1, 0xed, 0x10, 0x4b, 0xd7, 0x29, 0xd5, 0xa9, 0x21, 0xbb, 0x15, 0x71, 0xab,
	0x4f, 0x48, 0xdf, 0xc4, 0x15, 0x0f, 0x71, 0x39, 0xba, 0xaa, 0x30, 0x63, 0x88, 0x1d, 0xa6, 0x0f,
	0xa9, 0xdf, 0x24, 0xfd, 0x12, 0xa0, 0xa8, 0xe1, 0xbe, 0xe1, 0x30, 0x6c, 0x6b, 0xf8, 0xcb, 0x08,
	0x3b, 0x0c, 0xad, 0x43, 0x0e, 0x0f, 0x75, 0xc3, 0x2c, 0x0b, 0xdb, 0xc2, 0xde, 0xaa, 0xe6, 0x07,
	0x6e, 0x96, 0x0e, 0x88, 0x85, 0xcb, 0x19, 0x3f, 0xeb, 0x05, 0x48, 0x84, 0x15, 0xaa, 0x3b, 0xce,
	0x35, 0xb1, 0x7b, 0xe5, 0xac, 0x57, 0x98, 0xc4, 0xa8, 0x06, 0x6b, 0x7a, 0xb7, 0x4b, 0x46, 0x16,
	0xeb, 0xb0, 0x31, 0xc5, 0xe5, 0x7f, 0xb7, 0x85, 0xbd, 0x42, 0x75, 0x4b, 0x9e, 0xd5, 0x29, 0x2b,
	0x3e, 0xae, 0x35, 0xa6, 0x58, 0xcb, 0xeb, 0xd3, 0x40, 0xaa, 0x43, 0x69, 0x2a, 0xcf, 0xa1, 0xc4,
	0x72, 0x30, 0xaa, 0x40, 0x8e, 0x91, 0xcf, 0xd8, 0xf2, 0xf4, 0xe5, 0xab, 0x0f, 0x93, 0x08, 0x5b,
	0x2e, 0x40, 0xf3, 0x71, 0xd2, 0x01, 0xac, 0x9d, 0x92, 0xbe, 0x61, 0x85, 0x06, 0x34, 0xdd, 0x38,
	0x18, 0xd0, 0x0b, 0x22, 0xa3, 0x64, 0xa2, 0xa3, 0x48, 0x07, 0xf0, 0x1f, 0x67, 0x58, 0x54, 0x43,
	0xd1, 0x63, 0x20, 0x23, 0xc6, 0x45, 0x48, 0x25, 0x28, 0x04, 0x09, 0x9f, 0xd3, 0xcd, 0x68, 0xf8,
	0xca, 0xc6, 0xce, 0x20, 0xc0, 0xd4, 0xdc, 0xcb, 0xe1, 0x99, 0x45, 0x0f, 0x2e, 0x41, 0xe1, 0x18,
	0xb3, 0x73, 0x6c, 0x5e, 0x05, 0xac, 0x3f, 0x04, 0x28, 0x4e, 0x52, 0x9c, 0xb6, 0x00, 0x19, 0xa3,
	0xc7, 0x7f, 0x8f, 0x8c, 0xd1, 0x9b, 0xbe, 0x81, 0x4c, 0xe2, 0x1b, 0xc8, 0x86, 0xdf, 0xc0, 0xdf,
	0xb8, 0xe7, 0x23, 0x40, 0x6d, 0xda, 0xd3, 0x19, 0x3e, 0x74, 0x0f, 0x4a, 0x7f, 0x89, 0x69, 0x17,
	0x75, 0x04, 0xf7, 0x22, 0x3c, 0x8b, 0xfe, 0x6a, 0x13, 0x3d, 0x4d, 0x77, 0xc4, 0x90, 0x1e, 0x7f,
	0x7e, 0x61, 0xde, 0x0e, 0xcc, 0xd5, 0xc3, 0x79, 0x16, 0xd5, 0xf3, 0x11, 0xee, 0x73, 0x1e, 0xce,
	0x1c, 0x48, 0xda, 0x81, 0x35, 0x62, 0xf6, 0x3a, 0x13, 0x01, 0xbe, 0xb2, 0x3c, 0x31, 0x7b, 0x01,
	0xd2, 0x85, 0x58, 0xf8, 0xba, 0x13, 0xd3, 0x98, 0xb7, 0xf0, 0x75, 0x00, 0x91, 0x4e, 0x60, 0x23,
	0x4e, 0xbf, 0xa8, 0xd2, 0x0a, 0x3c, 0xd0, 0x70, 0x97, 0x7c, 0xc5, 0xf6, 0x38, 0xae, 0x35, 0xf1,
	0x3a, 0x25, 0x11, 0xca, 0xb3, 0x0d, 0x7c, 0x25, 0x3e, 0xc0, 0x66, 0x54, 0x57, 0x6d, 0x7c, 0x8e,
	0xbb, 0x36, 0x0e, 0xb6, 0x08, 0x6d, 0xc0, 0x92, 0xe3, 0x25, 0x38, 0x27, 0x8f, 0x6e, 0x33, 0xf3,
	0x3b, 0x78, 0x34, 0x8f, 0x7b, 0xd1, 0xd9, 0x7f, 0x0a, 0x90, 0xf3, 0x12, 0xee, 0xa8, 0xd3, 0xd6,
	0x55, 0x5e, 0x47, 0xaf, 0x01, 0xf0, 0x37, 0x6a, 0xd8, 0xd8, 0xe9, 0xe8, 0xcc, 0xd3, 0x94, 0xaf,
	0x8a, 0xb2, 0xef, 0xd1, 0x72, 0xe0, 0xd1, 0x72, 0x2b, 0xf0, 0x68, 0x6d, 0x95, 0xa3, 0x15, 0x36,
	0xb3, 0x64, 0xd9, 0xbb, 0x2f, 0xd9, 0xbe, 0x03, 0xf9, 0x50, 0x0d, 0x95, 0x61, 0x5d, 0xa9, 0xd7,
	0x1b, 0x6d, 0xb5, 0xd5, 0x69, 0x5d, 0x34, 0x0f, 0x3b, 0x6d, 0xf5, 0xad, 0xda, 0x78, 0xaf, 0x96,
	0xfe, 0x99, 0xa9, 0xd4, 0x1b, 0x67, 0x4d, 0x45, 0xbd, 0x28, 0x09, 0x33, 0x95, 0xe6, 0xa1, 0x76,
	0xde, 0x50, 0x95, 0x52, 0x06, 0x6d, 0x00, 0x8a, 0x54, 0x94, 0x37, 0x67, 0x27, 0x6a, 0x29, 0x5b,
	0xfd, 0xbd, 0x0c, 0x85, 0xa6, 0x2f, 0x52, 0xa1, 0x54, 0x19, 0xb1, 0x01, 0x6a, 0xc3, 0x4a, 0x60,
	0xea, 0x68, 0x37, 0x69, 0x82, 0xd8, 0x17, 0x49, 0x7c, 0x9c, 0x0e, 0xe2, 0xd7, 0x75, 0x0a, 0x39,
	0xcf, 0xa4, 0xd1, 0x76, 0x12, 0x3c, 0xfc, 0x05, 0x10, 0x77, 0x52, 0x10, 0x9c, 0xad, 0x01, 0x4b,
	0xbe, 0x3f, 0xa3, 0x79, 0xe0, 0xa9, 0x99, 0x8b, 0x52, 0x1a, 0x84, 0x13, 0x6a, 0xb0, 0xcc, 0xcd,
	0x1c, 0x49, 0xc9, 0xf3, 0x84, 0xbd, 0x5f, 0xdc, 0x4d, 0xc5, 0x4c, 0x39, 0xb9, 0x93, 0x27, 0x73,
	0x46, 0x9d, 0x3f, 0x99, 0x33, 0xfe, 0x29, 0xf8, 0x04, 0xf9, 0x90, 0x85, 0xa2, 0x27, 0x49, 0x3d,
	0xb3, 0x5e, 0x2d, 0x3e, 0xbd, 0x11, 0x17, 0xe7, 0xf7, 0x2c, 0x31, 0x8d, 0x3f, 0xec, 0xbd, 0x69,
	0xfc, 0x51, 0x6f, 0xed, 0x43, 0x21, 0xba, 0xd7, 0xe8, 0x59, 0x4a, 0x6b, 0xd4, 0xa2, 0xc4, 0xfd,
	0xdb, 0x40, 0xf9, 0x41, 0x43, 0xf7, 0x7f, 0x93, 0xa8, 0x71, 0xa1, 0xe7, 0xc9, 0xb7, 0x96, 0xe8,
	0x87, 0xe2, 0x8b, 0xdb, 0x81, 0xf9, 0x71, 0xdf, 0xe3, 0x1e, 0x1d, 0xf8, 0x15, 0x7a, 0x79, 0xb3,
	0xe8, 0x98, 0x6f, 0x8a, 0xd5, 0xbb, 0xb4, 0xf8, 0x02, 0x6a, 0x9b, 0xf0, 0x3f, 0xb1, 0x4c, 0xc3,
	0xc2, 0xa1, 0xde, 0xda, 0xca, 0xb1, 0x4d, 0xbb, 0xee, 0x56, 0x5f, 0x2e, 0x79, 0x06, 0xf6, 0xea,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x4d, 0xbb, 0xf5, 0x99, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonaAppAuthClient is the client API for PersonaAppAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppAuthClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	GetSelf(ctx context.Context, in *GetSelfRequest, opts ...grpc.CallOption) (*GetSelfResponse, error)
	UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error)
	UpdatePhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*UpdatePhoneResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
	RecoveryPassword(ctx context.Context, in *RecoveryPasswordRequest, opts ...grpc.CallOption) (*RecoveryPasswordResponse, error)
	UpdatePasswordBySecret(ctx context.Context, in *UpdatePasswordBySecretRequest, opts ...grpc.CallOption) (*UpdatePasswordBySecretResponse, error)
}

type personaAppAuthClient struct {
	cc *grpc.ClientConn
}

func NewPersonaAppAuthClient(cc *grpc.ClientConn) PersonaAppAuthClient {
	return &personaAppAuthClient{cc}
}

func (c *personaAppAuthClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) GetSelf(ctx context.Context, in *GetSelfRequest, opts ...grpc.CallOption) (*GetSelfResponse, error) {
	out := new(GetSelfResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/GetSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) UpdateEmail(ctx context.Context, in *UpdateEmailRequest, opts ...grpc.CallOption) (*UpdateEmailResponse, error) {
	out := new(UpdateEmailResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) UpdatePhone(ctx context.Context, in *UpdatePhoneRequest, opts ...grpc.CallOption) (*UpdatePhoneResponse, error) {
	out := new(UpdatePhoneResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/UpdatePhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	out := new(UpdatePasswordResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) RecoveryPassword(ctx context.Context, in *RecoveryPasswordRequest, opts ...grpc.CallOption) (*RecoveryPasswordResponse, error) {
	out := new(RecoveryPasswordResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/RecoveryPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppAuthClient) UpdatePasswordBySecret(ctx context.Context, in *UpdatePasswordBySecretRequest, opts ...grpc.CallOption) (*UpdatePasswordBySecretResponse, error) {
	out := new(UpdatePasswordBySecretResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.auth.PersonaAppAuth/UpdatePasswordBySecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppAuthServer is the server API for PersonaAppAuth service.
type PersonaAppAuthServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	GetSelf(context.Context, *GetSelfRequest) (*GetSelfResponse, error)
	UpdateEmail(context.Context, *UpdateEmailRequest) (*UpdateEmailResponse, error)
	UpdatePhone(context.Context, *UpdatePhoneRequest) (*UpdatePhoneResponse, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	RecoveryPassword(context.Context, *RecoveryPasswordRequest) (*RecoveryPasswordResponse, error)
	UpdatePasswordBySecret(context.Context, *UpdatePasswordBySecretRequest) (*UpdatePasswordBySecretResponse, error)
}

// UnimplementedPersonaAppAuthServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppAuthServer struct {
}

func (*UnimplementedPersonaAppAuthServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedPersonaAppAuthServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedPersonaAppAuthServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedPersonaAppAuthServer) Refresh(ctx context.Context, req *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (*UnimplementedPersonaAppAuthServer) GetSelf(ctx context.Context, req *GetSelfRequest) (*GetSelfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelf not implemented")
}
func (*UnimplementedPersonaAppAuthServer) UpdateEmail(ctx context.Context, req *UpdateEmailRequest) (*UpdateEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmail not implemented")
}
func (*UnimplementedPersonaAppAuthServer) UpdatePhone(ctx context.Context, req *UpdatePhoneRequest) (*UpdatePhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePhone not implemented")
}
func (*UnimplementedPersonaAppAuthServer) UpdatePassword(ctx context.Context, req *UpdatePasswordRequest) (*UpdatePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePassword not implemented")
}
func (*UnimplementedPersonaAppAuthServer) RecoveryPassword(ctx context.Context, req *RecoveryPasswordRequest) (*RecoveryPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoveryPassword not implemented")
}
func (*UnimplementedPersonaAppAuthServer) UpdatePasswordBySecret(ctx context.Context, req *UpdatePasswordBySecretRequest) (*UpdatePasswordBySecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePasswordBySecret not implemented")
}

func RegisterPersonaAppAuthServer(s *grpc.Server, srv PersonaAppAuthServer) {
	s.RegisterService(&_PersonaAppAuth_serviceDesc, srv)
}

func _PersonaAppAuth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_GetSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).GetSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/GetSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).GetSelf(ctx, req.(*GetSelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).UpdateEmail(ctx, req.(*UpdateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_UpdatePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).UpdatePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/UpdatePhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).UpdatePhone(ctx, req.(*UpdatePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_RecoveryPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoveryPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).RecoveryPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/RecoveryPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).RecoveryPassword(ctx, req.(*RecoveryPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppAuth_UpdatePasswordBySecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordBySecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppAuthServer).UpdatePasswordBySecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.auth.PersonaAppAuth/UpdatePasswordBySecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppAuthServer).UpdatePasswordBySecret(ctx, req.(*UpdatePasswordBySecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaAppAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.auth.PersonaAppAuth",
	HandlerType: (*PersonaAppAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PersonaAppAuth_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PersonaAppAuth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PersonaAppAuth_Logout_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _PersonaAppAuth_Refresh_Handler,
		},
		{
			MethodName: "GetSelf",
			Handler:    _PersonaAppAuth_GetSelf_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _PersonaAppAuth_UpdateEmail_Handler,
		},
		{
			MethodName: "UpdatePhone",
			Handler:    _PersonaAppAuth_UpdatePhone_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _PersonaAppAuth_UpdatePassword_Handler,
		},
		{
			MethodName: "RecoveryPassword",
			Handler:    _PersonaAppAuth_RecoveryPassword_Handler,
		},
		{
			MethodName: "UpdatePasswordBySecret",
			Handler:    _PersonaAppAuth_UpdatePasswordBySecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
