image: registry.gitlab.com/persona_app_online/devops/golangci:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  REGISTRY: registry.gitlab.com
  SERVICE_NAMESPACE: persona_app_online
  PROJECT_NAME: personaapp-go
  IMAGE_NAME: personaapp
  IMAGE_MASTER: $REGISTRY/$SERVICE_NAMESPACE/$PROJECT_NAME/$IMAGE_NAME:master

before_script:
  - docker login $REGISTRY -u $GITLAB_REGISTRY_USER -p $GITLAB_REGISTRY_TOKEN

stages:
  - test
  - build
  - build_image_master
  - deploy

test:
  stage: test
  script:
    -  make clean fmt build lint # testing is disable for now in ci cause of inability to start a docker in docker

build:
  stage: build
  image: docker:17
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_MASTER .
  except:
    - master

build_image_master:
  stage: build_image_master
  image: docker:17
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_MASTER .
    - docker push $IMAGE_MASTER
  only:
    - master
