openapi: 3.0.0

info:
  title: Persona API
  description: REST API v1
  version: 0.0.1

servers:
  - url: 165.227.165.6:8080/v1
    description: Dev server

tags:
- name: "device"
- name: "user"

paths:
  /signup:
    post:
      tags:
      - "user"
      summary: Register user
      
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  $ref: '#/components/schemas/Role'
              required:
                - email
                - password
                - role
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Role:
      type: string
      enum:
        - employee
        - employer
    Auth:
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
          format: int32
        token_type:
          type: string
        refresh_token:
          type: string

      required:
        - access_token
        - expires_in
        - token_type
        - refresh_token


                
