// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vacancy/vacancy.proto

package personaappapi_vacancy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Entity
type VacancyType int32

const (
	VacancyType_VACANCY_TYPE_UNKNOWN VacancyType = 0
	VacancyType_VACANCY_TYPE_REMOTE  VacancyType = 1
	VacancyType_VACANCY_TYPE_NORMAL  VacancyType = 2
)

var VacancyType_name = map[int32]string{
	0: "VACANCY_TYPE_UNKNOWN",
	1: "VACANCY_TYPE_REMOTE",
	2: "VACANCY_TYPE_NORMAL",
}

var VacancyType_value = map[string]int32{
	"VACANCY_TYPE_UNKNOWN": 0,
	"VACANCY_TYPE_REMOTE":  1,
	"VACANCY_TYPE_NORMAL":  2,
}

func (x VacancyType) String() string {
	return proto.EnumName(VacancyType_name, int32(x))
}

func (VacancyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{0}
}

type Currency int32

const (
	Currency_CURRENCY_UNKNOWN Currency = 0
	Currency_CURRENCY_UAH     Currency = 1
)

var Currency_name = map[int32]string{
	0: "CURRENCY_UNKNOWN",
	1: "CURRENCY_UAH",
}

var Currency_value = map[string]int32{
	"CURRENCY_UNKNOWN": 0,
	"CURRENCY_UAH":     1,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}

func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{1}
}

// Get vacancy category
type GetVacancyCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyCategoryRequest) Reset()         { *m = GetVacancyCategoryRequest{} }
func (m *GetVacancyCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacancyCategoryRequest) ProtoMessage()    {}
func (*GetVacancyCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{0}
}

func (m *GetVacancyCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyCategoryRequest.Unmarshal(m, b)
}
func (m *GetVacancyCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetVacancyCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyCategoryRequest.Merge(m, src)
}
func (m *GetVacancyCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacancyCategoryRequest.Size(m)
}
func (m *GetVacancyCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyCategoryRequest proto.InternalMessageInfo

func (m *GetVacancyCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetVacancyCategoryResponse struct {
	Category             *VacancyCategory `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetVacancyCategoryResponse) Reset()         { *m = GetVacancyCategoryResponse{} }
func (m *GetVacancyCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacancyCategoryResponse) ProtoMessage()    {}
func (*GetVacancyCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{1}
}

func (m *GetVacancyCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyCategoryResponse.Unmarshal(m, b)
}
func (m *GetVacancyCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetVacancyCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyCategoryResponse.Merge(m, src)
}
func (m *GetVacancyCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacancyCategoryResponse.Size(m)
}
func (m *GetVacancyCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyCategoryResponse proto.InternalMessageInfo

func (m *GetVacancyCategoryResponse) GetCategory() *VacancyCategory {
	if m != nil {
		return m.Category
	}
	return nil
}

// Upsert vacancy category
type UpsertVacancyCategoryRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IconUrl              string                `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpsertVacancyCategoryRequest) Reset()         { *m = UpsertVacancyCategoryRequest{} }
func (m *UpsertVacancyCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyCategoryRequest) ProtoMessage()    {}
func (*UpsertVacancyCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{2}
}

func (m *UpsertVacancyCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyCategoryRequest.Unmarshal(m, b)
}
func (m *UpsertVacancyCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyCategoryRequest.Merge(m, src)
}
func (m *UpsertVacancyCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyCategoryRequest.Size(m)
}
func (m *UpsertVacancyCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyCategoryRequest proto.InternalMessageInfo

func (m *UpsertVacancyCategoryRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpsertVacancyCategoryRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpsertVacancyCategoryRequest) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

type UpsertVacancyCategoryResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertVacancyCategoryResponse) Reset()         { *m = UpsertVacancyCategoryResponse{} }
func (m *UpsertVacancyCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyCategoryResponse) ProtoMessage()    {}
func (*UpsertVacancyCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{3}
}

func (m *UpsertVacancyCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyCategoryResponse.Unmarshal(m, b)
}
func (m *UpsertVacancyCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyCategoryResponse.Merge(m, src)
}
func (m *UpsertVacancyCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyCategoryResponse.Size(m)
}
func (m *UpsertVacancyCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyCategoryResponse proto.InternalMessageInfo

func (m *UpsertVacancyCategoryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Delete vacancy
type DeleteVacancyCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVacancyCategoryRequest) Reset()         { *m = DeleteVacancyCategoryRequest{} }
func (m *DeleteVacancyCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVacancyCategoryRequest) ProtoMessage()    {}
func (*DeleteVacancyCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{4}
}

func (m *DeleteVacancyCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVacancyCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteVacancyCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVacancyCategoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVacancyCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVacancyCategoryRequest.Merge(m, src)
}
func (m *DeleteVacancyCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVacancyCategoryRequest.Size(m)
}
func (m *DeleteVacancyCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVacancyCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVacancyCategoryRequest proto.InternalMessageInfo

func (m *DeleteVacancyCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteVacancyCategoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVacancyCategoryResponse) Reset()         { *m = DeleteVacancyCategoryResponse{} }
func (m *DeleteVacancyCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVacancyCategoryResponse) ProtoMessage()    {}
func (*DeleteVacancyCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5}
}

func (m *DeleteVacancyCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVacancyCategoryResponse.Unmarshal(m, b)
}
func (m *DeleteVacancyCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVacancyCategoryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVacancyCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVacancyCategoryResponse.Merge(m, src)
}
func (m *DeleteVacancyCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVacancyCategoryResponse.Size(m)
}
func (m *DeleteVacancyCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVacancyCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVacancyCategoryResponse proto.InternalMessageInfo

// Get Vacancies filters list
type GetVacancyCategoriesListRequest struct {
	Rating               *wrappers.Int32Value `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetVacancyCategoriesListRequest) Reset()         { *m = GetVacancyCategoriesListRequest{} }
func (m *GetVacancyCategoriesListRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacancyCategoriesListRequest) ProtoMessage()    {}
func (*GetVacancyCategoriesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{6}
}

func (m *GetVacancyCategoriesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyCategoriesListRequest.Unmarshal(m, b)
}
func (m *GetVacancyCategoriesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyCategoriesListRequest.Marshal(b, m, deterministic)
}
func (m *GetVacancyCategoriesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyCategoriesListRequest.Merge(m, src)
}
func (m *GetVacancyCategoriesListRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacancyCategoriesListRequest.Size(m)
}
func (m *GetVacancyCategoriesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyCategoriesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyCategoriesListRequest proto.InternalMessageInfo

func (m *GetVacancyCategoriesListRequest) GetRating() *wrappers.Int32Value {
	if m != nil {
		return m.Rating
	}
	return nil
}

type GetVacancyCategoriesListResponse struct {
	VacancyCategories    map[string]*VacancyCategory `protobuf:"bytes,1,rep,name=vacancy_categories,json=vacancyCategories,proto3" json:"vacancy_categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetVacancyCategoriesListResponse) Reset()         { *m = GetVacancyCategoriesListResponse{} }
func (m *GetVacancyCategoriesListResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacancyCategoriesListResponse) ProtoMessage()    {}
func (*GetVacancyCategoriesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{7}
}

func (m *GetVacancyCategoriesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyCategoriesListResponse.Unmarshal(m, b)
}
func (m *GetVacancyCategoriesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyCategoriesListResponse.Marshal(b, m, deterministic)
}
func (m *GetVacancyCategoriesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyCategoriesListResponse.Merge(m, src)
}
func (m *GetVacancyCategoriesListResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacancyCategoriesListResponse.Size(m)
}
func (m *GetVacancyCategoriesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyCategoriesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyCategoriesListResponse proto.InternalMessageInfo

func (m *GetVacancyCategoriesListResponse) GetVacancyCategories() map[string]*VacancyCategory {
	if m != nil {
		return m.VacancyCategories
	}
	return nil
}

// Upsert vacancy
type UpsertVacancyRequest struct {
	Vacancy              *UpsertVacancyRequest_Vacancy            `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	ImageURLs            []string                                 `protobuf:"bytes,2,rep,name=imageURLs,proto3" json:"imageURLs,omitempty"`
	Location             *UpsertVacancyRequest_VacancyLocation    `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description          *UpsertVacancyRequest_VacancyDescription `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CityIDs              []string                                 `protobuf:"bytes,5,rep,name=cityIDs,proto3" json:"cityIDs,omitempty"`
	CategoryIDs          []string                                 `protobuf:"bytes,6,rep,name=categoryIDs,proto3" json:"categoryIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *UpsertVacancyRequest) Reset()         { *m = UpsertVacancyRequest{} }
func (m *UpsertVacancyRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyRequest) ProtoMessage()    {}
func (*UpsertVacancyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{8}
}

func (m *UpsertVacancyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyRequest.Unmarshal(m, b)
}
func (m *UpsertVacancyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyRequest.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyRequest.Merge(m, src)
}
func (m *UpsertVacancyRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyRequest.Size(m)
}
func (m *UpsertVacancyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyRequest proto.InternalMessageInfo

func (m *UpsertVacancyRequest) GetVacancy() *UpsertVacancyRequest_Vacancy {
	if m != nil {
		return m.Vacancy
	}
	return nil
}

func (m *UpsertVacancyRequest) GetImageURLs() []string {
	if m != nil {
		return m.ImageURLs
	}
	return nil
}

func (m *UpsertVacancyRequest) GetLocation() *UpsertVacancyRequest_VacancyLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *UpsertVacancyRequest) GetDescription() *UpsertVacancyRequest_VacancyDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpsertVacancyRequest) GetCityIDs() []string {
	if m != nil {
		return m.CityIDs
	}
	return nil
}

func (m *UpsertVacancyRequest) GetCategoryIDs() []string {
	if m != nil {
		return m.CategoryIDs
	}
	return nil
}

type UpsertVacancyRequest_VacancyLocation struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertVacancyRequest_VacancyLocation) Reset()         { *m = UpsertVacancyRequest_VacancyLocation{} }
func (m *UpsertVacancyRequest_VacancyLocation) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyRequest_VacancyLocation) ProtoMessage()    {}
func (*UpsertVacancyRequest_VacancyLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{8, 0}
}

func (m *UpsertVacancyRequest_VacancyLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyRequest_VacancyLocation.Unmarshal(m, b)
}
func (m *UpsertVacancyRequest_VacancyLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyRequest_VacancyLocation.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyRequest_VacancyLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyRequest_VacancyLocation.Merge(m, src)
}
func (m *UpsertVacancyRequest_VacancyLocation) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyRequest_VacancyLocation.Size(m)
}
func (m *UpsertVacancyRequest_VacancyLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyRequest_VacancyLocation.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyRequest_VacancyLocation proto.InternalMessageInfo

func (m *UpsertVacancyRequest_VacancyLocation) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *UpsertVacancyRequest_VacancyLocation) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type UpsertVacancyRequest_VacancyDescription struct {
	Description          string      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	WorkMonthsExperience uint32      `protobuf:"varint,2,opt,name=work_months_experience,json=workMonthsExperience,proto3" json:"work_months_experience,omitempty"`
	WorkSchedule         string      `protobuf:"bytes,3,opt,name=work_schedule,json=workSchedule,proto3" json:"work_schedule,omitempty"`
	Type                 VacancyType `protobuf:"varint,4,opt,name=type,proto3,enum=personaappapi.vacancy.VacancyType" json:"type,omitempty"`
	Address              string      `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	CountryCode          int32       `protobuf:"varint,6,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpsertVacancyRequest_VacancyDescription) Reset() {
	*m = UpsertVacancyRequest_VacancyDescription{}
}
func (m *UpsertVacancyRequest_VacancyDescription) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyRequest_VacancyDescription) ProtoMessage()    {}
func (*UpsertVacancyRequest_VacancyDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{8, 1}
}

func (m *UpsertVacancyRequest_VacancyDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyRequest_VacancyDescription.Unmarshal(m, b)
}
func (m *UpsertVacancyRequest_VacancyDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyRequest_VacancyDescription.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyRequest_VacancyDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyRequest_VacancyDescription.Merge(m, src)
}
func (m *UpsertVacancyRequest_VacancyDescription) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyRequest_VacancyDescription.Size(m)
}
func (m *UpsertVacancyRequest_VacancyDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyRequest_VacancyDescription.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyRequest_VacancyDescription proto.InternalMessageInfo

func (m *UpsertVacancyRequest_VacancyDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpsertVacancyRequest_VacancyDescription) GetWorkMonthsExperience() uint32 {
	if m != nil {
		return m.WorkMonthsExperience
	}
	return 0
}

func (m *UpsertVacancyRequest_VacancyDescription) GetWorkSchedule() string {
	if m != nil {
		return m.WorkSchedule
	}
	return ""
}

func (m *UpsertVacancyRequest_VacancyDescription) GetType() VacancyType {
	if m != nil {
		return m.Type
	}
	return VacancyType_VACANCY_TYPE_UNKNOWN
}

func (m *UpsertVacancyRequest_VacancyDescription) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpsertVacancyRequest_VacancyDescription) GetCountryCode() int32 {
	if m != nil {
		return m.CountryCode
	}
	return 0
}

type UpsertVacancyRequest_Vacancy struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Phone                string                `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	MinSalary            int32                 `protobuf:"varint,4,opt,name=min_salary,json=minSalary,proto3" json:"min_salary,omitempty"`
	MaxSalary            int32                 `protobuf:"varint,5,opt,name=max_salary,json=maxSalary,proto3" json:"max_salary,omitempty"`
	CompanyId            string                `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Currency             Currency              `protobuf:"varint,7,opt,name=currency,proto3,enum=personaappapi.vacancy.Currency" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpsertVacancyRequest_Vacancy) Reset()         { *m = UpsertVacancyRequest_Vacancy{} }
func (m *UpsertVacancyRequest_Vacancy) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyRequest_Vacancy) ProtoMessage()    {}
func (*UpsertVacancyRequest_Vacancy) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{8, 2}
}

func (m *UpsertVacancyRequest_Vacancy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyRequest_Vacancy.Unmarshal(m, b)
}
func (m *UpsertVacancyRequest_Vacancy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyRequest_Vacancy.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyRequest_Vacancy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyRequest_Vacancy.Merge(m, src)
}
func (m *UpsertVacancyRequest_Vacancy) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyRequest_Vacancy.Size(m)
}
func (m *UpsertVacancyRequest_Vacancy) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyRequest_Vacancy.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyRequest_Vacancy proto.InternalMessageInfo

func (m *UpsertVacancyRequest_Vacancy) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpsertVacancyRequest_Vacancy) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpsertVacancyRequest_Vacancy) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpsertVacancyRequest_Vacancy) GetMinSalary() int32 {
	if m != nil {
		return m.MinSalary
	}
	return 0
}

func (m *UpsertVacancyRequest_Vacancy) GetMaxSalary() int32 {
	if m != nil {
		return m.MaxSalary
	}
	return 0
}

func (m *UpsertVacancyRequest_Vacancy) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *UpsertVacancyRequest_Vacancy) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_CURRENCY_UNKNOWN
}

type UpsertVacancyResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertVacancyResponse) Reset()         { *m = UpsertVacancyResponse{} }
func (m *UpsertVacancyResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertVacancyResponse) ProtoMessage()    {}
func (*UpsertVacancyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{9}
}

func (m *UpsertVacancyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertVacancyResponse.Unmarshal(m, b)
}
func (m *UpsertVacancyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertVacancyResponse.Marshal(b, m, deterministic)
}
func (m *UpsertVacancyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertVacancyResponse.Merge(m, src)
}
func (m *UpsertVacancyResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertVacancyResponse.Size(m)
}
func (m *UpsertVacancyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertVacancyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertVacancyResponse proto.InternalMessageInfo

func (m *UpsertVacancyResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Get Vacancies List
type GetVacanciesListRequest struct {
	CategoriesIds        map[string]*Empty     `protobuf:"bytes,1,rep,name=categories_ids,json=categoriesIds,proto3" json:"categories_ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cursor               *wrappers.StringValue `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Count                *wrappers.Int32Value  `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetVacanciesListRequest) Reset()         { *m = GetVacanciesListRequest{} }
func (m *GetVacanciesListRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListRequest) ProtoMessage()    {}
func (*GetVacanciesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{10}
}

func (m *GetVacanciesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListRequest.Unmarshal(m, b)
}
func (m *GetVacanciesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListRequest.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListRequest.Merge(m, src)
}
func (m *GetVacanciesListRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListRequest.Size(m)
}
func (m *GetVacanciesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListRequest proto.InternalMessageInfo

func (m *GetVacanciesListRequest) GetCategoriesIds() map[string]*Empty {
	if m != nil {
		return m.CategoriesIds
	}
	return nil
}

func (m *GetVacanciesListRequest) GetCursor() *wrappers.StringValue {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *GetVacanciesListRequest) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

type GetVacanciesListResponse struct {
	VacanciesIds         []string                                            `protobuf:"bytes,1,rep,name=vacancies_ids,json=vacanciesIds,proto3" json:"vacancies_ids,omitempty"`
	Vacancies            map[string]*GetVacanciesListResponse_VacancyDetails `protobuf:"bytes,2,rep,name=vacancies,proto3" json:"vacancies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Companies            map[string]*Company                                 `protobuf:"bytes,3,rep,name=companies,proto3" json:"companies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Categories           map[string]*VacancyCategoryShort                    `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cursor               *wrappers.StringValue                               `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *GetVacanciesListResponse) Reset()         { *m = GetVacanciesListResponse{} }
func (m *GetVacanciesListResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListResponse) ProtoMessage()    {}
func (*GetVacanciesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{11}
}

func (m *GetVacanciesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse.Merge(m, src)
}
func (m *GetVacanciesListResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse.Size(m)
}
func (m *GetVacanciesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse proto.InternalMessageInfo

func (m *GetVacanciesListResponse) GetVacanciesIds() []string {
	if m != nil {
		return m.VacanciesIds
	}
	return nil
}

func (m *GetVacanciesListResponse) GetVacancies() map[string]*GetVacanciesListResponse_VacancyDetails {
	if m != nil {
		return m.Vacancies
	}
	return nil
}

func (m *GetVacanciesListResponse) GetCompanies() map[string]*Company {
	if m != nil {
		return m.Companies
	}
	return nil
}

func (m *GetVacanciesListResponse) GetCategories() map[string]*VacancyCategoryShort {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *GetVacanciesListResponse) GetCursor() *wrappers.StringValue {
	if m != nil {
		return m.Cursor
	}
	return nil
}

type GetVacanciesListResponse_VacancyDetails struct {
	Vacancy              *Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	ImageUrls            []string `protobuf:"bytes,2,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacanciesListResponse_VacancyDetails) Reset() {
	*m = GetVacanciesListResponse_VacancyDetails{}
}
func (m *GetVacanciesListResponse_VacancyDetails) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListResponse_VacancyDetails) ProtoMessage()    {}
func (*GetVacanciesListResponse_VacancyDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{11, 0}
}

func (m *GetVacanciesListResponse_VacancyDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse_VacancyDetails.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse_VacancyDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse_VacancyDetails.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse_VacancyDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse_VacancyDetails.Merge(m, src)
}
func (m *GetVacanciesListResponse_VacancyDetails) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse_VacancyDetails.Size(m)
}
func (m *GetVacanciesListResponse_VacancyDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse_VacancyDetails.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse_VacancyDetails proto.InternalMessageInfo

func (m *GetVacanciesListResponse_VacancyDetails) GetVacancy() *Vacancy {
	if m != nil {
		return m.Vacancy
	}
	return nil
}

func (m *GetVacanciesListResponse_VacancyDetails) GetImageUrls() []string {
	if m != nil {
		return m.ImageUrls
	}
	return nil
}

// Get Vacancy Details
type GetVacancyDetailsRequest struct {
	VacancyId            string   `protobuf:"bytes,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsRequest) Reset()         { *m = GetVacancyDetailsRequest{} }
func (m *GetVacancyDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsRequest) ProtoMessage()    {}
func (*GetVacancyDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{12}
}

func (m *GetVacancyDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsRequest.Unmarshal(m, b)
}
func (m *GetVacancyDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsRequest.Merge(m, src)
}
func (m *GetVacancyDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsRequest.Size(m)
}
func (m *GetVacancyDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsRequest proto.InternalMessageInfo

func (m *GetVacancyDetailsRequest) GetVacancyId() string {
	if m != nil {
		return m.VacancyId
	}
	return ""
}

type GetVacancyDetailsResponse struct {
	Vacancy              *Vacancy                                      `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	Image                *GetVacancyDetailsResponse_VacancyImage       `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Location             *GetVacancyDetailsResponse_VacancyLocation    `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description          *GetVacancyDetailsResponse_VacancyDescription `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Company              *GetVacancyDetailsResponse_VacancyCompany     `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	City                 *City                                         `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Categories           map[string]*VacancyCategoryShort              `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *GetVacancyDetailsResponse) Reset()         { *m = GetVacancyDetailsResponse{} }
func (m *GetVacancyDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse) ProtoMessage()    {}
func (*GetVacancyDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{13}
}

func (m *GetVacancyDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse.Merge(m, src)
}
func (m *GetVacancyDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse.Size(m)
}
func (m *GetVacancyDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse) GetVacancy() *Vacancy {
	if m != nil {
		return m.Vacancy
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetImage() *GetVacancyDetailsResponse_VacancyImage {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetLocation() *GetVacancyDetailsResponse_VacancyLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetDescription() *GetVacancyDetailsResponse_VacancyDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetCompany() *GetVacancyDetailsResponse_VacancyCompany {
	if m != nil {
		return m.Company
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetCity() *City {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetCategories() map[string]*VacancyCategoryShort {
	if m != nil {
		return m.Categories
	}
	return nil
}

type GetVacancyDetailsResponse_CompanyDescription struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsResponse_CompanyDescription) Reset() {
	*m = GetVacancyDetailsResponse_CompanyDescription{}
}
func (m *GetVacancyDetailsResponse_CompanyDescription) String() string {
	return proto.CompactTextString(m)
}
func (*GetVacancyDetailsResponse_CompanyDescription) ProtoMessage() {}
func (*GetVacancyDetailsResponse_CompanyDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{13, 0}
}

func (m *GetVacancyDetailsResponse_CompanyDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_CompanyDescription.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_CompanyDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_CompanyDescription.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_CompanyDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_CompanyDescription.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_CompanyDescription) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_CompanyDescription.Size(m)
}
func (m *GetVacancyDetailsResponse_CompanyDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_CompanyDescription.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_CompanyDescription proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_CompanyDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetVacancyDetailsResponse_VacancyLocation struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsResponse_VacancyLocation) Reset() {
	*m = GetVacancyDetailsResponse_VacancyLocation{}
}
func (m *GetVacancyDetailsResponse_VacancyLocation) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_VacancyLocation) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_VacancyLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{13, 1}
}

func (m *GetVacancyDetailsResponse_VacancyLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyLocation.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_VacancyLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyLocation.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_VacancyLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyLocation.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_VacancyLocation) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyLocation.Size(m)
}
func (m *GetVacancyDetailsResponse_VacancyLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyLocation.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_VacancyLocation proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_VacancyLocation) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GetVacancyDetailsResponse_VacancyLocation) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetVacancyDetailsResponse_VacancyDescription struct {
	Description          string      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	WorkMonthsExperience uint32      `protobuf:"varint,2,opt,name=work_months_experience,json=workMonthsExperience,proto3" json:"work_months_experience,omitempty"`
	WorkSchedule         string      `protobuf:"bytes,3,opt,name=work_schedule,json=workSchedule,proto3" json:"work_schedule,omitempty"`
	Type                 VacancyType `protobuf:"varint,4,opt,name=type,proto3,enum=personaappapi.vacancy.VacancyType" json:"type,omitempty"`
	Address              string      `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	CountryCode          int32       `protobuf:"varint,6,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetVacancyDetailsResponse_VacancyDescription) Reset() {
	*m = GetVacancyDetailsResponse_VacancyDescription{}
}
func (m *GetVacancyDetailsResponse_VacancyDescription) String() string {
	return proto.CompactTextString(m)
}
func (*GetVacancyDetailsResponse_VacancyDescription) ProtoMessage() {}
func (*GetVacancyDetailsResponse_VacancyDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{13, 2}
}

func (m *GetVacancyDetailsResponse_VacancyDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyDescription.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_VacancyDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyDescription.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_VacancyDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyDescription.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_VacancyDescription) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyDescription.Size(m)
}
func (m *GetVacancyDetailsResponse_VacancyDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyDescription.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_VacancyDescription proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_VacancyDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetVacancyDetailsResponse_VacancyDescription) GetWorkMonthsExperience() uint32 {
	if m != nil {
		return m.WorkMonthsExperience
	}
	return 0
}

func (m *GetVacancyDetailsResponse_VacancyDescription) GetWorkSchedule() string {
	if m != nil {
		return m.WorkSchedule
	}
	return ""
}

func (m *GetVacancyDetailsResponse_VacancyDescription) GetType() VacancyType {
	if m != nil {
		return m.Type
	}
	return VacancyType_VACANCY_TYPE_UNKNOWN
}

func (m *GetVacancyDetailsResponse_VacancyDescription) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetVacancyDetailsResponse_VacancyDescription) GetCountryCode() int32 {
	if m != nil {
		return m.CountryCode
	}
	return 0
}

type GetVacancyDetailsResponse_VacancyCompany struct {
	Company              *Company                                      `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Description          *GetVacancyDetailsResponse_CompanyDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *GetVacancyDetailsResponse_VacancyCompany) Reset() {
	*m = GetVacancyDetailsResponse_VacancyCompany{}
}
func (m *GetVacancyDetailsResponse_VacancyCompany) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_VacancyCompany) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_VacancyCompany) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{13, 3}
}

func (m *GetVacancyDetailsResponse_VacancyCompany) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyCompany.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_VacancyCompany) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyCompany.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_VacancyCompany) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyCompany.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_VacancyCompany) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyCompany.Size(m)
}
func (m *GetVacancyDetailsResponse_VacancyCompany) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyCompany.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_VacancyCompany proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_VacancyCompany) GetCompany() *Company {
	if m != nil {
		return m.Company
	}
	return nil
}

func (m *GetVacancyDetailsResponse_VacancyCompany) GetDescription() *GetVacancyDetailsResponse_CompanyDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type GetVacancyDetailsResponse_VacancyImage struct {
	ImageUrls            []string `protobuf:"bytes,1,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsResponse_VacancyImage) Reset() {
	*m = GetVacancyDetailsResponse_VacancyImage{}
}
func (m *GetVacancyDetailsResponse_VacancyImage) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_VacancyImage) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_VacancyImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{13, 4}
}

func (m *GetVacancyDetailsResponse_VacancyImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyImage.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_VacancyImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyImage.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_VacancyImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyImage.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_VacancyImage) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_VacancyImage.Size(m)
}
func (m *GetVacancyDetailsResponse_VacancyImage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_VacancyImage.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_VacancyImage proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_VacancyImage) GetImageUrls() []string {
	if m != nil {
		return m.ImageUrls
	}
	return nil
}

// Delete Vacancy
type DeleteVacancyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVacancyRequest) Reset()         { *m = DeleteVacancyRequest{} }
func (m *DeleteVacancyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVacancyRequest) ProtoMessage()    {}
func (*DeleteVacancyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{14}
}

func (m *DeleteVacancyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVacancyRequest.Unmarshal(m, b)
}
func (m *DeleteVacancyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVacancyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVacancyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVacancyRequest.Merge(m, src)
}
func (m *DeleteVacancyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVacancyRequest.Size(m)
}
func (m *DeleteVacancyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVacancyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVacancyRequest proto.InternalMessageInfo

func (m *DeleteVacancyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteVacancyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVacancyResponse) Reset()         { *m = DeleteVacancyResponse{} }
func (m *DeleteVacancyResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVacancyResponse) ProtoMessage()    {}
func (*DeleteVacancyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{15}
}

func (m *DeleteVacancyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVacancyResponse.Unmarshal(m, b)
}
func (m *DeleteVacancyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVacancyResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVacancyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVacancyResponse.Merge(m, src)
}
func (m *DeleteVacancyResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVacancyResponse.Size(m)
}
func (m *DeleteVacancyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVacancyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVacancyResponse proto.InternalMessageInfo

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{16}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Company struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	LogoUrl              string   `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{17}
}

func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Company) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Company) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

type VacancyCategory struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IconUrl              string   `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VacancyCategory) Reset()         { *m = VacancyCategory{} }
func (m *VacancyCategory) String() string { return proto.CompactTextString(m) }
func (*VacancyCategory) ProtoMessage()    {}
func (*VacancyCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{18}
}

func (m *VacancyCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VacancyCategory.Unmarshal(m, b)
}
func (m *VacancyCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VacancyCategory.Marshal(b, m, deterministic)
}
func (m *VacancyCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VacancyCategory.Merge(m, src)
}
func (m *VacancyCategory) XXX_Size() int {
	return xxx_messageInfo_VacancyCategory.Size(m)
}
func (m *VacancyCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_VacancyCategory.DiscardUnknown(m)
}

var xxx_messageInfo_VacancyCategory proto.InternalMessageInfo

func (m *VacancyCategory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VacancyCategory) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VacancyCategory) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *VacancyCategory) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type Vacancy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	MinSalary            int32    `protobuf:"varint,4,opt,name=min_salary,json=minSalary,proto3" json:"min_salary,omitempty"`
	MaxSalary            int32    `protobuf:"varint,5,opt,name=max_salary,json=maxSalary,proto3" json:"max_salary,omitempty"`
	CompanyId            string   `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Currency             Currency `protobuf:"varint,7,opt,name=currency,proto3,enum=personaappapi.vacancy.Currency" json:"currency,omitempty"`
	CategoriesIds        []string `protobuf:"bytes,8,rep,name=categories_ids,json=categoriesIds,proto3" json:"categories_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vacancy) Reset()         { *m = Vacancy{} }
func (m *Vacancy) String() string { return proto.CompactTextString(m) }
func (*Vacancy) ProtoMessage()    {}
func (*Vacancy) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{19}
}

func (m *Vacancy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vacancy.Unmarshal(m, b)
}
func (m *Vacancy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vacancy.Marshal(b, m, deterministic)
}
func (m *Vacancy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vacancy.Merge(m, src)
}
func (m *Vacancy) XXX_Size() int {
	return xxx_messageInfo_Vacancy.Size(m)
}
func (m *Vacancy) XXX_DiscardUnknown() {
	xxx_messageInfo_Vacancy.DiscardUnknown(m)
}

var xxx_messageInfo_Vacancy proto.InternalMessageInfo

func (m *Vacancy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vacancy) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Vacancy) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Vacancy) GetMinSalary() int32 {
	if m != nil {
		return m.MinSalary
	}
	return 0
}

func (m *Vacancy) GetMaxSalary() int32 {
	if m != nil {
		return m.MaxSalary
	}
	return 0
}

func (m *Vacancy) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *Vacancy) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_CURRENCY_UNKNOWN
}

func (m *Vacancy) GetCategoriesIds() []string {
	if m != nil {
		return m.CategoriesIds
	}
	return nil
}

type VacancyCategoryShort struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VacancyCategoryShort) Reset()         { *m = VacancyCategoryShort{} }
func (m *VacancyCategoryShort) String() string { return proto.CompactTextString(m) }
func (*VacancyCategoryShort) ProtoMessage()    {}
func (*VacancyCategoryShort) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{20}
}

func (m *VacancyCategoryShort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VacancyCategoryShort.Unmarshal(m, b)
}
func (m *VacancyCategoryShort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VacancyCategoryShort.Marshal(b, m, deterministic)
}
func (m *VacancyCategoryShort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VacancyCategoryShort.Merge(m, src)
}
func (m *VacancyCategoryShort) XXX_Size() int {
	return xxx_messageInfo_VacancyCategoryShort.Size(m)
}
func (m *VacancyCategoryShort) XXX_DiscardUnknown() {
	xxx_messageInfo_VacancyCategoryShort.DiscardUnknown(m)
}

var xxx_messageInfo_VacancyCategoryShort proto.InternalMessageInfo

func (m *VacancyCategoryShort) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type City struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryCode          int32    `protobuf:"varint,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{21}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *City) GetCountryCode() int32 {
	if m != nil {
		return m.CountryCode
	}
	return 0
}

func (m *City) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func init() {
	proto.RegisterEnum("personaappapi.vacancy.VacancyType", VacancyType_name, VacancyType_value)
	proto.RegisterEnum("personaappapi.vacancy.Currency", Currency_name, Currency_value)
	proto.RegisterType((*GetVacancyCategoryRequest)(nil), "personaappapi.vacancy.GetVacancyCategoryRequest")
	proto.RegisterType((*GetVacancyCategoryResponse)(nil), "personaappapi.vacancy.GetVacancyCategoryResponse")
	proto.RegisterType((*UpsertVacancyCategoryRequest)(nil), "personaappapi.vacancy.UpsertVacancyCategoryRequest")
	proto.RegisterType((*UpsertVacancyCategoryResponse)(nil), "personaappapi.vacancy.UpsertVacancyCategoryResponse")
	proto.RegisterType((*DeleteVacancyCategoryRequest)(nil), "personaappapi.vacancy.DeleteVacancyCategoryRequest")
	proto.RegisterType((*DeleteVacancyCategoryResponse)(nil), "personaappapi.vacancy.DeleteVacancyCategoryResponse")
	proto.RegisterType((*GetVacancyCategoriesListRequest)(nil), "personaappapi.vacancy.GetVacancyCategoriesListRequest")
	proto.RegisterType((*GetVacancyCategoriesListResponse)(nil), "personaappapi.vacancy.GetVacancyCategoriesListResponse")
	proto.RegisterMapType((map[string]*VacancyCategory)(nil), "personaappapi.vacancy.GetVacancyCategoriesListResponse.VacancyCategoriesEntry")
	proto.RegisterType((*UpsertVacancyRequest)(nil), "personaappapi.vacancy.UpsertVacancyRequest")
	proto.RegisterType((*UpsertVacancyRequest_VacancyLocation)(nil), "personaappapi.vacancy.UpsertVacancyRequest.VacancyLocation")
	proto.RegisterType((*UpsertVacancyRequest_VacancyDescription)(nil), "personaappapi.vacancy.UpsertVacancyRequest.VacancyDescription")
	proto.RegisterType((*UpsertVacancyRequest_Vacancy)(nil), "personaappapi.vacancy.UpsertVacancyRequest.Vacancy")
	proto.RegisterType((*UpsertVacancyResponse)(nil), "personaappapi.vacancy.UpsertVacancyResponse")
	proto.RegisterType((*GetVacanciesListRequest)(nil), "personaappapi.vacancy.GetVacanciesListRequest")
	proto.RegisterMapType((map[string]*Empty)(nil), "personaappapi.vacancy.GetVacanciesListRequest.CategoriesIdsEntry")
	proto.RegisterType((*GetVacanciesListResponse)(nil), "personaappapi.vacancy.GetVacanciesListResponse")
	proto.RegisterMapType((map[string]*VacancyCategoryShort)(nil), "personaappapi.vacancy.GetVacanciesListResponse.CategoriesEntry")
	proto.RegisterMapType((map[string]*Company)(nil), "personaappapi.vacancy.GetVacanciesListResponse.CompaniesEntry")
	proto.RegisterMapType((map[string]*GetVacanciesListResponse_VacancyDetails)(nil), "personaappapi.vacancy.GetVacanciesListResponse.VacanciesEntry")
	proto.RegisterType((*GetVacanciesListResponse_VacancyDetails)(nil), "personaappapi.vacancy.GetVacanciesListResponse.VacancyDetails")
	proto.RegisterType((*GetVacancyDetailsRequest)(nil), "personaappapi.vacancy.GetVacancyDetailsRequest")
	proto.RegisterType((*GetVacancyDetailsResponse)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse")
	proto.RegisterMapType((map[string]*VacancyCategoryShort)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.CategoriesEntry")
	proto.RegisterType((*GetVacancyDetailsResponse_CompanyDescription)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.CompanyDescription")
	proto.RegisterType((*GetVacancyDetailsResponse_VacancyLocation)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.VacancyLocation")
	proto.RegisterType((*GetVacancyDetailsResponse_VacancyDescription)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.VacancyDescription")
	proto.RegisterType((*GetVacancyDetailsResponse_VacancyCompany)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.VacancyCompany")
	proto.RegisterType((*GetVacancyDetailsResponse_VacancyImage)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.VacancyImage")
	proto.RegisterType((*DeleteVacancyRequest)(nil), "personaappapi.vacancy.DeleteVacancyRequest")
	proto.RegisterType((*DeleteVacancyResponse)(nil), "personaappapi.vacancy.DeleteVacancyResponse")
	proto.RegisterType((*Empty)(nil), "personaappapi.vacancy.Empty")
	proto.RegisterType((*Company)(nil), "personaappapi.vacancy.Company")
	proto.RegisterType((*VacancyCategory)(nil), "personaappapi.vacancy.VacancyCategory")
	proto.RegisterType((*Vacancy)(nil), "personaappapi.vacancy.Vacancy")
	proto.RegisterType((*VacancyCategoryShort)(nil), "personaappapi.vacancy.VacancyCategoryShort")
	proto.RegisterType((*City)(nil), "personaappapi.vacancy.City")
}

func init() { proto.RegisterFile("vacancy/vacancy.proto", fileDescriptor_47be6d1234ea964b) }

var fileDescriptor_47be6d1234ea964b = []byte{
	// 1546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0xbe, 0x94, 0x2d, 0x4b, 0x3a, 0xb2, 0x1d, 0x79, 0xae, 0x9c, 0x28, 0xbc, 0x76, 0xa2, 0xcb,
	0xa0, 0xa9, 0x91, 0xa4, 0x52, 0x22, 0x1b, 0x69, 0xda, 0xb4, 0x4d, 0x15, 0x45, 0x48, 0xdd, 0xd8,
	0x4e, 0x40, 0xff, 0x04, 0x06, 0x82, 0x2a, 0x0c, 0x39, 0x95, 0x99, 0x50, 0x24, 0x4b, 0x52, 0x4e,
	0x04, 0x34, 0x9b, 0x2e, 0xb2, 0xe9, 0xa2, 0xcf, 0xd2, 0x6d, 0xf7, 0xdd, 0x75, 0xd1, 0xf7, 0xe8,
	0x33, 0x14, 0x28, 0x66, 0x38, 0x43, 0xf1, 0x47, 0x94, 0x25, 0xa1, 0x2d, 0x50, 0xa0, 0x2b, 0x89,
	0x73, 0xce, 0x7c, 0x33, 0xf3, 0xcd, 0x99, 0xef, 0x9c, 0x19, 0x58, 0x3d, 0x55, 0x54, 0xc5, 0x54,
	0x07, 0x75, 0xf6, 0x5b, 0xb3, 0x1d, 0xcb, 0xb3, 0xd0, 0xaa, 0x8d, 0x1d, 0xd7, 0x32, 0x15, 0xc5,
	0xb6, 0x15, 0x5b, 0xaf, 0x31, 0xa3, 0x78, 0xa9, 0x6b, 0x59, 0x5d, 0x03, 0xd7, 0xa9, 0xd3, 0x8b,
	0xfe, 0xd7, 0xf5, 0xd7, 0x8e, 0x62, 0x13, 0x57, 0xbf, 0x9b, 0x74, 0x1d, 0x2e, 0x3e, 0xc4, 0xde,
	0x91, 0xef, 0xdd, 0x52, 0x3c, 0xdc, 0xb5, 0x9c, 0x81, 0x8c, 0xbf, 0xe9, 0x63, 0xd7, 0x43, 0xcb,
	0x90, 0xd1, 0xb5, 0x8a, 0x50, 0x15, 0x36, 0x0a, 0x72, 0x46, 0xd7, 0xa4, 0xe7, 0x20, 0x8e, 0x72,
	0x76, 0x6d, 0xcb, 0x74, 0x31, 0xba, 0x0f, 0x79, 0x95, 0xb5, 0xd1, 0x3e, 0xc5, 0xc6, 0xd5, 0xda,
	0xc8, 0x49, 0xd5, 0xe2, 0x08, 0x41, 0x3f, 0xe9, 0x2d, 0xac, 0x1d, 0xda, 0x2e, 0x76, 0xd2, 0x66,
	0x74, 0x23, 0x98, 0x51, 0xb1, 0xb1, 0x56, 0xf3, 0xd7, 0x56, 0xe3, 0x6b, 0xab, 0xed, 0x7b, 0x8e,
	0x6e, 0x76, 0x8f, 0x14, 0xa3, 0x8f, 0xc9, 0x7c, 0x51, 0x19, 0xb2, 0x9e, 0xee, 0x19, 0xb8, 0x92,
	0xa1, 0x4b, 0xf0, 0x3f, 0xd0, 0x45, 0xc8, 0xeb, 0xaa, 0x65, 0x76, 0xfa, 0x8e, 0x51, 0x99, 0xa3,
	0x86, 0x1c, 0xf9, 0x3e, 0x74, 0x0c, 0xa9, 0x0e, 0xeb, 0x29, 0xc3, 0xb3, 0x35, 0xc6, 0x19, 0xa9,
	0xc1, 0xda, 0x03, 0x6c, 0x60, 0x0f, 0x4f, 0xc8, 0xe0, 0x65, 0x58, 0x4f, 0xf1, 0xf7, 0x07, 0x90,
	0x8e, 0xe0, 0x72, 0x82, 0x62, 0x1d, 0xbb, 0x3b, 0xba, 0xeb, 0x71, 0xcc, 0x4d, 0x58, 0x70, 0x14,
	0x4f, 0x37, 0xbb, 0x8c, 0x87, 0xff, 0x25, 0x78, 0xd8, 0x36, 0xbd, 0xcd, 0x86, 0x4f, 0x03, 0x73,
	0x95, 0x7e, 0xc8, 0x40, 0x35, 0x1d, 0x98, 0xad, 0xee, 0x2d, 0x20, 0xb6, 0x45, 0x1d, 0x35, 0xf0,
	0xa8, 0x08, 0xd5, 0xb9, 0x8d, 0x62, 0x63, 0x2f, 0x65, 0x2f, 0xcf, 0x02, 0xad, 0x25, 0xac, 0x6d,
	0xd3, 0x73, 0x06, 0xf2, 0xca, 0x69, 0xbc, 0x5d, 0x34, 0xe0, 0xfc, 0x68, 0x67, 0x54, 0x82, 0xb9,
	0x57, 0x78, 0xc0, 0x78, 0x24, 0x7f, 0xd1, 0x27, 0x90, 0x3d, 0x25, 0x0b, 0xa4, 0x5b, 0x3b, 0x79,
	0xa4, 0xf9, 0x9d, 0x3e, 0xce, 0xdc, 0x11, 0xa4, 0x5f, 0x73, 0x50, 0x8e, 0x6c, 0x36, 0xe7, 0x77,
	0x17, 0x72, 0xac, 0x3b, 0x23, 0x78, 0x33, 0x05, 0x7c, 0x54, 0x6f, 0x3e, 0xa2, 0xcc, 0x31, 0xd0,
	0x1a, 0x14, 0xf4, 0x9e, 0xd2, 0xc5, 0x87, 0xf2, 0x8e, 0x5b, 0xc9, 0x54, 0xe7, 0x36, 0x0a, 0xf2,
	0xb0, 0x01, 0x3d, 0x85, 0xbc, 0x61, 0xa9, 0x8a, 0xa7, 0x5b, 0x26, 0x0d, 0xc6, 0x62, 0xe3, 0xee,
	0x0c, 0xa3, 0xed, 0x30, 0x08, 0x39, 0x00, 0x43, 0xcf, 0xa1, 0xa8, 0x61, 0x57, 0x75, 0x74, 0x9b,
	0x62, 0xcf, 0x53, 0xec, 0xcf, 0x66, 0xc0, 0x7e, 0x30, 0x44, 0x91, 0xc3, 0x90, 0xa8, 0x02, 0x39,
	0x55, 0xf7, 0x06, 0xdb, 0x0f, 0xdc, 0x4a, 0x96, 0x2e, 0x8b, 0x7f, 0xa2, 0x2a, 0x14, 0xf9, 0x89,
	0x26, 0xd6, 0x05, 0x6a, 0x0d, 0x37, 0x89, 0x8f, 0xe0, 0x5c, 0x6c, 0xea, 0x48, 0x84, 0xbc, 0xa1,
	0x78, 0xba, 0xd7, 0xd7, 0x30, 0xe5, 0x3d, 0x23, 0x07, 0xdf, 0x84, 0x43, 0xc3, 0x32, 0xbb, 0xbe,
	0x31, 0x43, 0x8d, 0xc3, 0x06, 0xf1, 0x5d, 0x06, 0x50, 0x72, 0xb2, 0x64, 0x16, 0x61, 0x06, 0xfc,
	0xe0, 0x89, 0xac, 0x60, 0x0b, 0xce, 0xbf, 0xb6, 0x9c, 0x57, 0x9d, 0x9e, 0x65, 0x7a, 0x27, 0x6e,
	0x07, 0xbf, 0xb1, 0xb1, 0xa3, 0x63, 0x53, 0xf5, 0xc7, 0x58, 0x92, 0xcb, 0xc4, 0xba, 0x4b, 0x8d,
	0xed, 0xc0, 0x86, 0xae, 0xc0, 0x12, 0xed, 0xe5, 0xaa, 0x27, 0x58, 0xeb, 0x1b, 0x98, 0x89, 0xc8,
	0x22, 0x69, 0xdc, 0x67, 0x6d, 0xe8, 0x36, 0xcc, 0x7b, 0x03, 0x1b, 0x53, 0xde, 0x97, 0x1b, 0xd2,
	0xf8, 0xf0, 0x3c, 0x18, 0xd8, 0x58, 0xa6, 0xfe, 0x84, 0x54, 0x45, 0xd3, 0x1c, 0xec, 0x12, 0x52,
	0xa9, 0x36, 0xb1, 0x4f, 0xf4, 0x7f, 0x58, 0x54, 0xad, 0x3e, 0x39, 0x0e, 0x1d, 0xd5, 0xd2, 0x70,
	0x65, 0xa1, 0x2a, 0x6c, 0x64, 0xe5, 0x22, 0x6b, 0x6b, 0x59, 0x1a, 0x16, 0x7f, 0x17, 0x20, 0xc7,
	0x20, 0xff, 0x14, 0xa5, 0x2c, 0x43, 0xd6, 0x3e, 0xb1, 0x4c, 0xbe, 0x42, 0xff, 0x03, 0xad, 0x03,
	0xf4, 0x74, 0xb3, 0xe3, 0x2a, 0x86, 0xe2, 0x0c, 0xe8, 0x02, 0xb3, 0x72, 0xa1, 0xa7, 0x9b, 0xfb,
	0xb4, 0x81, 0x9a, 0x95, 0x37, 0xdc, 0x9c, 0x65, 0x66, 0xe5, 0xcd, 0xd0, 0xac, 0x5a, 0x3d, 0x5b,
	0x31, 0x07, 0x1d, 0x5d, 0xa3, 0x8b, 0x28, 0xc8, 0x05, 0xd6, 0xb2, 0xad, 0xa1, 0xbb, 0x90, 0x57,
	0xfb, 0x8e, 0x83, 0xc9, 0xe9, 0xcb, 0x51, 0xee, 0x2e, 0xa7, 0x70, 0xd7, 0x62, 0x6e, 0x72, 0xd0,
	0x41, 0x7a, 0x1f, 0x56, 0x63, 0x91, 0x9c, 0x22, 0xdb, 0xbf, 0x64, 0xe0, 0x42, 0x20, 0x5c, 0x31,
	0x79, 0x3d, 0x81, 0xe5, 0xa1, 0xf8, 0x75, 0x74, 0x8d, 0x0b, 0x60, 0xf3, 0x2c, 0x01, 0x8c, 0xe2,
	0xd4, 0x86, 0x1a, 0xb6, 0xad, 0x31, 0xcd, 0x5b, 0x52, 0xc3, 0x6d, 0x68, 0x0b, 0x16, 0xd4, 0xbe,
	0xe3, 0x5a, 0x0e, 0x13, 0xb1, 0xf1, 0xdb, 0xc4, 0x7c, 0xd1, 0x2d, 0xc8, 0xd2, 0x3d, 0x67, 0x72,
	0x31, 0x56, 0xfd, 0x7d, 0x4f, 0xf1, 0x2b, 0x40, 0xc9, 0xd9, 0x8c, 0x10, 0xd5, 0x46, 0x54, 0x54,
	0xd7, 0x52, 0x56, 0xdc, 0xee, 0xd9, 0x5e, 0x44, 0x4a, 0x7f, 0x5e, 0x80, 0x4a, 0x92, 0x06, 0xc6,
	0xfd, 0x15, 0x58, 0x3a, 0xe5, 0x86, 0x80, 0xce, 0x82, 0xbc, 0x18, 0x34, 0x12, 0x2a, 0x9e, 0x41,
	0x21, 0xf8, 0xa6, 0x22, 0x99, 0xae, 0x55, 0x69, 0x03, 0xd5, 0x82, 0x56, 0x9f, 0xec, 0x21, 0x20,
	0x41, 0xf7, 0x23, 0x8c, 0xa0, 0xcf, 0xcd, 0x86, 0xde, 0xe2, 0x00, 0x0c, 0x3d, 0x00, 0x44, 0x1d,
	0x80, 0x50, 0xb6, 0x9c, 0xa7, 0xf0, 0xf7, 0xa6, 0x86, 0x8f, 0xa5, 0xc7, 0x10, 0x64, 0x28, 0x4e,
	0xb2, 0x93, 0xc7, 0x89, 0xa8, 0xc3, 0x72, 0x20, 0x8a, 0x9e, 0xa2, 0x1b, 0x2e, 0xba, 0x13, 0x4f,
	0x6c, 0x97, 0xc6, 0xcb, 0xd2, 0x30, 0x87, 0xad, 0x03, 0xd0, 0x94, 0x45, 0x6a, 0xa6, 0x58, 0x12,
	0x73, 0x0c, 0x57, 0xfc, 0x96, 0x0f, 0x35, 0x26, 0x61, 0x1f, 0x44, 0x63, 0x6b, 0xc6, 0xdd, 0xe5,
	0x6b, 0x09, 0x45, 0x9f, 0xf8, 0x0c, 0x96, 0xa3, 0x9b, 0x33, 0x62, 0xf4, 0xad, 0xe8, 0xe8, 0x69,
	0x0b, 0xf7, 0x71, 0xc2, 0xb1, 0x2d, 0xbe, 0x84, 0x73, 0x67, 0x57, 0x23, 0xcd, 0x28, 0xfc, 0xf5,
	0xc9, 0xaa, 0x91, 0xfd, 0x13, 0xcb, 0xf1, 0xc2, 0xe7, 0xe8, 0xa3, 0xd0, 0x31, 0x0a, 0x56, 0xca,
	0x64, 0x69, 0x1d, 0x80, 0xd7, 0x66, 0x81, 0x94, 0xb1, 0x10, 0x1f, 0x6c, 0x6b, 0xd2, 0x4f, 0x10,
	0x2e, 0xe4, 0x83, 0xbe, 0xec, 0x0c, 0xce, 0xbe, 0xf3, 0xfb, 0x90, 0xa5, 0xfb, 0xcc, 0x56, 0xf6,
	0xe9, 0x99, 0x55, 0x60, 0x6c, 0x68, 0x8e, 0xb8, 0x4d, 0x40, 0x64, 0x1f, 0x0b, 0x3d, 0x4b, 0x14,
	0x3d, 0x9f, 0xcf, 0x8a, 0x3b, 0xa2, 0xf2, 0xc1, 0xa3, 0x2a, 0x9f, 0xd6, 0xac, 0x03, 0xa4, 0x96,
	0x3f, 0xc7, 0x90, 0x63, 0x69, 0x8b, 0x1d, 0xcb, 0x7b, 0xb3, 0x0e, 0xc1, 0xa3, 0x8e, 0xe3, 0xa1,
	0x3a, 0xcc, 0x93, 0x52, 0x8a, 0x66, 0x47, 0xa2, 0xf0, 0x29, 0xc1, 0xaa, 0x7b, 0x03, 0x99, 0x3a,
	0xa2, 0xe7, 0x11, 0x09, 0xca, 0x51, 0x09, 0x9a, 0x9e, 0xd2, 0x31, 0x1a, 0x24, 0xde, 0x06, 0xc4,
	0xa6, 0x39, 0x55, 0x89, 0xf5, 0x6f, 0xa1, 0xf7, 0x97, 0x14, 0x7a, 0x3f, 0x0a, 0x81, 0xb8, 0xb3,
	0x5d, 0x21, 0x47, 0x9c, 0x87, 0xa3, 0x30, 0x91, 0xc6, 0x05, 0xd1, 0x16, 0x3b, 0x2f, 0x99, 0x19,
	0xcf, 0x4b, 0x32, 0x3c, 0xa2, 0x91, 0xf0, 0x01, 0x2c, 0x86, 0xb5, 0x20, 0x96, 0x53, 0x84, 0x78,
	0x4e, 0xf9, 0x3b, 0x75, 0xf7, 0x2a, 0x94, 0x23, 0xb7, 0xf2, 0xb4, 0xdb, 0xfb, 0x05, 0x58, 0x8d,
	0xf9, 0xb1, 0x5b, 0x7b, 0x0e, 0xb2, 0xb4, 0x28, 0x92, 0xbe, 0x84, 0x1c, 0xdf, 0x90, 0x58, 0xe7,
	0xf4, 0xc7, 0x08, 0xc3, 0xea, 0x5a, 0xe1, 0xc7, 0x08, 0xf2, 0x7d, 0xe8, 0x18, 0xd2, 0xcb, 0xe0,
	0xe8, 0xf0, 0x89, 0x4f, 0x8e, 0x99, 0xf2, 0xc0, 0x81, 0xce, 0x07, 0x6f, 0x07, 0x7e, 0xdd, 0xce,
	0x9f, 0x07, 0xde, 0x65, 0x86, 0x37, 0x87, 0xc9, 0x06, 0xf9, 0x87, 0xdd, 0x0d, 0xd0, 0x7b, 0x89,
	0xb2, 0x3e, 0x4f, 0x43, 0x2e, 0x5a, 0x93, 0x4b, 0x37, 0xa0, 0x3c, 0x2a, 0x5a, 0x86, 0x24, 0x08,
	0x21, 0x12, 0x24, 0x0c, 0xf3, 0x44, 0x85, 0x13, 0x94, 0x21, 0x98, 0x37, 0x95, 0x1e, 0x67, 0x8c,
	0xfe, 0x4f, 0x1c, 0xeb, 0xb9, 0xc4, 0xb1, 0x4e, 0xdb, 0x9d, 0x6b, 0xc7, 0x50, 0x0c, 0x09, 0x08,
	0xaa, 0x40, 0xf9, 0xa8, 0xd9, 0x6a, 0xee, 0xb5, 0x8e, 0x3b, 0x07, 0xc7, 0x4f, 0xda, 0x9d, 0xc3,
	0xbd, 0x47, 0x7b, 0x8f, 0x9f, 0xee, 0x95, 0xfe, 0x83, 0x2e, 0xc0, 0x7f, 0x23, 0x16, 0xb9, 0xbd,
	0xfb, 0xf8, 0xa0, 0x5d, 0x12, 0x12, 0x86, 0xbd, 0xc7, 0xf2, 0x6e, 0x73, 0xa7, 0x94, 0xb9, 0xd6,
	0x80, 0x3c, 0x27, 0x0b, 0x95, 0xa1, 0xd4, 0x3a, 0x94, 0xe5, 0x36, 0xf1, 0x1a, 0x62, 0x96, 0x60,
	0x71, 0xd8, 0xda, 0xfc, 0xa2, 0x24, 0x34, 0x7e, 0xcb, 0xc1, 0xca, 0x13, 0x9f, 0xf7, 0xa6, 0x6d,
	0xf3, 0xb0, 0x19, 0x00, 0x4a, 0x3e, 0x0e, 0xa2, 0x9b, 0x93, 0x3e, 0x1b, 0xf1, 0x43, 0x27, 0xde,
	0x9a, 0xa2, 0x07, 0x2b, 0x6f, 0xbe, 0x13, 0x62, 0x17, 0xbf, 0x60, 0xf8, 0x89, 0x9e, 0x6e, 0xe2,
	0x33, 0xd8, 0x9a, 0xae, 0x53, 0x68, 0x12, 0x23, 0xdf, 0xf6, 0x52, 0x27, 0x31, 0xee, 0xe5, 0x30,
	0x75, 0x12, 0x63, 0x9f, 0x0f, 0xd1, 0xf7, 0x42, 0xb8, 0x84, 0x8c, 0xbe, 0xc8, 0xa1, 0xdb, 0x53,
	0x3f, 0xe1, 0xf9, 0x53, 0xf9, 0x70, 0xc6, 0xa7, 0x3f, 0xf4, 0x12, 0x96, 0x22, 0x9c, 0xa1, 0xeb,
	0x53, 0xbc, 0x3f, 0x89, 0x37, 0x26, 0x73, 0x66, 0x63, 0xb9, 0x50, 0x8a, 0xdf, 0x1d, 0x50, 0x6d,
	0xba, 0x2b, 0xbb, 0x58, 0x9f, 0xf2, 0x52, 0x82, 0x4e, 0x61, 0x25, 0x91, 0x10, 0x51, 0x7d, 0xf2,
	0xd4, 0xe9, 0x0f, 0x7b, 0x73, 0xda, 0x5c, 0x4b, 0x88, 0x8d, 0xc4, 0x41, 0x2a, 0xb1, 0xa3, 0xd2,
	0x5a, 0x2a, 0xb1, 0x23, 0x73, 0xdb, 0xfd, 0x2a, 0xac, 0x58, 0xa6, 0xa1, 0x9b, 0x38, 0xd4, 0xeb,
	0x7e, 0xf1, 0xa1, 0x63, 0xab, 0xcc, 0xf3, 0xc5, 0x02, 0xbd, 0x87, 0x6e, 0xfe, 0x11, 0x00, 0x00,
	0xff, 0xff, 0x62, 0xcb, 0x53, 0x53, 0x9a, 0x18, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonaAppVacancyClient is the client API for PersonaAppVacancy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppVacancyClient interface {
	// Vacancy categories
	GetVacancyCategory(ctx context.Context, in *GetVacancyCategoryRequest, opts ...grpc.CallOption) (*GetVacancyCategoryResponse, error)
	UpsertVacancyCategory(ctx context.Context, in *UpsertVacancyCategoryRequest, opts ...grpc.CallOption) (*UpsertVacancyCategoryResponse, error)
	DeleteVacancyCategory(ctx context.Context, in *DeleteVacancyCategoryRequest, opts ...grpc.CallOption) (*DeleteVacancyCategoryResponse, error)
	GetVacancyCategoriesList(ctx context.Context, in *GetVacancyCategoriesListRequest, opts ...grpc.CallOption) (*GetVacancyCategoriesListResponse, error)
	// Vacancy
	UpsertVacancy(ctx context.Context, in *UpsertVacancyRequest, opts ...grpc.CallOption) (*UpsertVacancyResponse, error)
	GetVacanciesList(ctx context.Context, in *GetVacanciesListRequest, opts ...grpc.CallOption) (*GetVacanciesListResponse, error)
	GetVacancyDetails(ctx context.Context, in *GetVacancyDetailsRequest, opts ...grpc.CallOption) (*GetVacancyDetailsResponse, error)
	DeleteVacancy(ctx context.Context, in *DeleteVacancyRequest, opts ...grpc.CallOption) (*DeleteVacancyResponse, error)
}

type personaAppVacancyClient struct {
	cc *grpc.ClientConn
}

func NewPersonaAppVacancyClient(cc *grpc.ClientConn) PersonaAppVacancyClient {
	return &personaAppVacancyClient{cc}
}

func (c *personaAppVacancyClient) GetVacancyCategory(ctx context.Context, in *GetVacancyCategoryRequest, opts ...grpc.CallOption) (*GetVacancyCategoryResponse, error) {
	out := new(GetVacancyCategoryResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) UpsertVacancyCategory(ctx context.Context, in *UpsertVacancyCategoryRequest, opts ...grpc.CallOption) (*UpsertVacancyCategoryResponse, error) {
	out := new(UpsertVacancyCategoryResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/UpsertVacancyCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) DeleteVacancyCategory(ctx context.Context, in *DeleteVacancyCategoryRequest, opts ...grpc.CallOption) (*DeleteVacancyCategoryResponse, error) {
	out := new(DeleteVacancyCategoryResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/DeleteVacancyCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) GetVacancyCategoriesList(ctx context.Context, in *GetVacancyCategoriesListRequest, opts ...grpc.CallOption) (*GetVacancyCategoriesListResponse, error) {
	out := new(GetVacancyCategoriesListResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyCategoriesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) UpsertVacancy(ctx context.Context, in *UpsertVacancyRequest, opts ...grpc.CallOption) (*UpsertVacancyResponse, error) {
	out := new(UpsertVacancyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/UpsertVacancy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) GetVacanciesList(ctx context.Context, in *GetVacanciesListRequest, opts ...grpc.CallOption) (*GetVacanciesListResponse, error) {
	out := new(GetVacanciesListResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacanciesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) GetVacancyDetails(ctx context.Context, in *GetVacancyDetailsRequest, opts ...grpc.CallOption) (*GetVacancyDetailsResponse, error) {
	out := new(GetVacancyDetailsResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) DeleteVacancy(ctx context.Context, in *DeleteVacancyRequest, opts ...grpc.CallOption) (*DeleteVacancyResponse, error) {
	out := new(DeleteVacancyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/DeleteVacancy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppVacancyServer is the server API for PersonaAppVacancy service.
type PersonaAppVacancyServer interface {
	// Vacancy categories
	GetVacancyCategory(context.Context, *GetVacancyCategoryRequest) (*GetVacancyCategoryResponse, error)
	UpsertVacancyCategory(context.Context, *UpsertVacancyCategoryRequest) (*UpsertVacancyCategoryResponse, error)
	DeleteVacancyCategory(context.Context, *DeleteVacancyCategoryRequest) (*DeleteVacancyCategoryResponse, error)
	GetVacancyCategoriesList(context.Context, *GetVacancyCategoriesListRequest) (*GetVacancyCategoriesListResponse, error)
	// Vacancy
	UpsertVacancy(context.Context, *UpsertVacancyRequest) (*UpsertVacancyResponse, error)
	GetVacanciesList(context.Context, *GetVacanciesListRequest) (*GetVacanciesListResponse, error)
	GetVacancyDetails(context.Context, *GetVacancyDetailsRequest) (*GetVacancyDetailsResponse, error)
	DeleteVacancy(context.Context, *DeleteVacancyRequest) (*DeleteVacancyResponse, error)
}

// UnimplementedPersonaAppVacancyServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppVacancyServer struct {
}

func (*UnimplementedPersonaAppVacancyServer) GetVacancyCategory(ctx context.Context, req *GetVacancyCategoryRequest) (*GetVacancyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancyCategory not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) UpsertVacancyCategory(ctx context.Context, req *UpsertVacancyCategoryRequest) (*UpsertVacancyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertVacancyCategory not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) DeleteVacancyCategory(ctx context.Context, req *DeleteVacancyCategoryRequest) (*DeleteVacancyCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVacancyCategory not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) GetVacancyCategoriesList(ctx context.Context, req *GetVacancyCategoriesListRequest) (*GetVacancyCategoriesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancyCategoriesList not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) UpsertVacancy(ctx context.Context, req *UpsertVacancyRequest) (*UpsertVacancyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertVacancy not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) GetVacanciesList(ctx context.Context, req *GetVacanciesListRequest) (*GetVacanciesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacanciesList not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) GetVacancyDetails(ctx context.Context, req *GetVacancyDetailsRequest) (*GetVacancyDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancyDetails not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) DeleteVacancy(ctx context.Context, req *DeleteVacancyRequest) (*DeleteVacancyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVacancy not implemented")
}

func RegisterPersonaAppVacancyServer(s *grpc.Server, srv PersonaAppVacancyServer) {
	s.RegisterService(&_PersonaAppVacancy_serviceDesc, srv)
}

func _PersonaAppVacancy_GetVacancyCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacancyCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacancyCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacancyCategory(ctx, req.(*GetVacancyCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_UpsertVacancyCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertVacancyCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).UpsertVacancyCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/UpsertVacancyCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).UpsertVacancyCategory(ctx, req.(*UpsertVacancyCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_DeleteVacancyCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVacancyCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).DeleteVacancyCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/DeleteVacancyCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).DeleteVacancyCategory(ctx, req.(*DeleteVacancyCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_GetVacancyCategoriesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacancyCategoriesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacancyCategoriesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyCategoriesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacancyCategoriesList(ctx, req.(*GetVacancyCategoriesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_UpsertVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).UpsertVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/UpsertVacancy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).UpsertVacancy(ctx, req.(*UpsertVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_GetVacanciesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacanciesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacanciesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacanciesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacanciesList(ctx, req.(*GetVacanciesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_GetVacancyDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacancyDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacancyDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacancyDetails(ctx, req.(*GetVacancyDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_DeleteVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).DeleteVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/DeleteVacancy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).DeleteVacancy(ctx, req.(*DeleteVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaAppVacancy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.vacancy.PersonaAppVacancy",
	HandlerType: (*PersonaAppVacancyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVacancyCategory",
			Handler:    _PersonaAppVacancy_GetVacancyCategory_Handler,
		},
		{
			MethodName: "UpsertVacancyCategory",
			Handler:    _PersonaAppVacancy_UpsertVacancyCategory_Handler,
		},
		{
			MethodName: "DeleteVacancyCategory",
			Handler:    _PersonaAppVacancy_DeleteVacancyCategory_Handler,
		},
		{
			MethodName: "GetVacancyCategoriesList",
			Handler:    _PersonaAppVacancy_GetVacancyCategoriesList_Handler,
		},
		{
			MethodName: "UpsertVacancy",
			Handler:    _PersonaAppVacancy_UpsertVacancy_Handler,
		},
		{
			MethodName: "GetVacanciesList",
			Handler:    _PersonaAppVacancy_GetVacanciesList_Handler,
		},
		{
			MethodName: "GetVacancyDetails",
			Handler:    _PersonaAppVacancy_GetVacancyDetails_Handler,
		},
		{
			MethodName: "DeleteVacancy",
			Handler:    _PersonaAppVacancy_DeleteVacancy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vacancy/vacancy.proto",
}
