// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vacancy/vacancy.proto

package vacancy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	entities "personaapp/pkg/grpcapi/entities"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency int32

const (
	Currency_CURRENCY_UNKNOWN Currency = 0
	Currency_CURRENCY_UAH     Currency = 1
	Currency_CURRENCY_USD     Currency = 2
	Currency_CURRENCY_EUR     Currency = 3
)

var Currency_name = map[int32]string{
	0: "CURRENCY_UNKNOWN",
	1: "CURRENCY_UAH",
	2: "CURRENCY_USD",
	3: "CURRENCY_EUR",
}

var Currency_value = map[string]int32{
	"CURRENCY_UNKNOWN": 0,
	"CURRENCY_UAH":     1,
	"CURRENCY_USD":     2,
	"CURRENCY_EUR":     3,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}

func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{0}
}

// Get Vacancies filters list
type GetVacanciesFiltersListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacanciesFiltersListRequest) Reset()         { *m = GetVacanciesFiltersListRequest{} }
func (m *GetVacanciesFiltersListRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesFiltersListRequest) ProtoMessage()    {}
func (*GetVacanciesFiltersListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{0}
}

func (m *GetVacanciesFiltersListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesFiltersListRequest.Unmarshal(m, b)
}
func (m *GetVacanciesFiltersListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesFiltersListRequest.Marshal(b, m, deterministic)
}
func (m *GetVacanciesFiltersListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesFiltersListRequest.Merge(m, src)
}
func (m *GetVacanciesFiltersListRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesFiltersListRequest.Size(m)
}
func (m *GetVacanciesFiltersListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesFiltersListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesFiltersListRequest proto.InternalMessageInfo

type GetVacanciesFiltersListResponse struct {
	// Types that are valid to be assigned to Response:
	//	*GetVacanciesFiltersListResponse_Body_
	Response             isGetVacanciesFiltersListResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *GetVacanciesFiltersListResponse) Reset()         { *m = GetVacanciesFiltersListResponse{} }
func (m *GetVacanciesFiltersListResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesFiltersListResponse) ProtoMessage()    {}
func (*GetVacanciesFiltersListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{1}
}

func (m *GetVacanciesFiltersListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesFiltersListResponse.Unmarshal(m, b)
}
func (m *GetVacanciesFiltersListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesFiltersListResponse.Marshal(b, m, deterministic)
}
func (m *GetVacanciesFiltersListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesFiltersListResponse.Merge(m, src)
}
func (m *GetVacanciesFiltersListResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesFiltersListResponse.Size(m)
}
func (m *GetVacanciesFiltersListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesFiltersListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesFiltersListResponse proto.InternalMessageInfo

type isGetVacanciesFiltersListResponse_Response interface {
	isGetVacanciesFiltersListResponse_Response()
}

type GetVacanciesFiltersListResponse_Body_ struct {
	Body *GetVacanciesFiltersListResponse_Body `protobuf:"bytes,1,opt,name=body,proto3,oneof"`
}

func (*GetVacanciesFiltersListResponse_Body_) isGetVacanciesFiltersListResponse_Response() {}

func (m *GetVacanciesFiltersListResponse) GetResponse() isGetVacanciesFiltersListResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetVacanciesFiltersListResponse) GetBody() *GetVacanciesFiltersListResponse_Body {
	if x, ok := m.GetResponse().(*GetVacanciesFiltersListResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetVacanciesFiltersListResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetVacanciesFiltersListResponse_Body_)(nil),
	}
}

type GetVacanciesFiltersListResponse_VacancyFilter struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacanciesFiltersListResponse_VacancyFilter) Reset() {
	*m = GetVacanciesFiltersListResponse_VacancyFilter{}
}
func (m *GetVacanciesFiltersListResponse_VacancyFilter) String() string {
	return proto.CompactTextString(m)
}
func (*GetVacanciesFiltersListResponse_VacancyFilter) ProtoMessage() {}
func (*GetVacanciesFiltersListResponse_VacancyFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{1, 0}
}

func (m *GetVacanciesFiltersListResponse_VacancyFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesFiltersListResponse_VacancyFilter.Unmarshal(m, b)
}
func (m *GetVacanciesFiltersListResponse_VacancyFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesFiltersListResponse_VacancyFilter.Marshal(b, m, deterministic)
}
func (m *GetVacanciesFiltersListResponse_VacancyFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesFiltersListResponse_VacancyFilter.Merge(m, src)
}
func (m *GetVacanciesFiltersListResponse_VacancyFilter) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesFiltersListResponse_VacancyFilter.Size(m)
}
func (m *GetVacanciesFiltersListResponse_VacancyFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesFiltersListResponse_VacancyFilter.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesFiltersListResponse_VacancyFilter proto.InternalMessageInfo

func (m *GetVacanciesFiltersListResponse_VacancyFilter) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacanciesFiltersListResponse_VacancyFilter) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type GetVacanciesFiltersListResponse_Body struct {
	VacancyFilters       map[string]*GetVacanciesFiltersListResponse_VacancyFilter `protobuf:"bytes,1,rep,name=vacancy_filters,json=vacancyFilters,proto3" json:"vacancy_filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *GetVacanciesFiltersListResponse_Body) Reset()         { *m = GetVacanciesFiltersListResponse_Body{} }
func (m *GetVacanciesFiltersListResponse_Body) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesFiltersListResponse_Body) ProtoMessage()    {}
func (*GetVacanciesFiltersListResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{1, 1}
}

func (m *GetVacanciesFiltersListResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesFiltersListResponse_Body.Unmarshal(m, b)
}
func (m *GetVacanciesFiltersListResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesFiltersListResponse_Body.Marshal(b, m, deterministic)
}
func (m *GetVacanciesFiltersListResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesFiltersListResponse_Body.Merge(m, src)
}
func (m *GetVacanciesFiltersListResponse_Body) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesFiltersListResponse_Body.Size(m)
}
func (m *GetVacanciesFiltersListResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesFiltersListResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesFiltersListResponse_Body proto.InternalMessageInfo

func (m *GetVacanciesFiltersListResponse_Body) GetVacancyFilters() map[string]*GetVacanciesFiltersListResponse_VacancyFilter {
	if m != nil {
		return m.VacancyFilters
	}
	return nil
}

// Get Vacancies List
type GetVacanciesListRequest struct {
	FilterIds            map[string]*entities.Empty `protobuf:"bytes,1,rep,name=filter_ids,json=filterIds,proto3" json:"filter_ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Offset               *wrappers.Int32Value       `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                *wrappers.Int32Value       `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetVacanciesListRequest) Reset()         { *m = GetVacanciesListRequest{} }
func (m *GetVacanciesListRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListRequest) ProtoMessage()    {}
func (*GetVacanciesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{2}
}

func (m *GetVacanciesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListRequest.Unmarshal(m, b)
}
func (m *GetVacanciesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListRequest.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListRequest.Merge(m, src)
}
func (m *GetVacanciesListRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListRequest.Size(m)
}
func (m *GetVacanciesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListRequest proto.InternalMessageInfo

func (m *GetVacanciesListRequest) GetFilterIds() map[string]*entities.Empty {
	if m != nil {
		return m.FilterIds
	}
	return nil
}

func (m *GetVacanciesListRequest) GetOffset() *wrappers.Int32Value {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *GetVacanciesListRequest) GetCount() *wrappers.Int32Value {
	if m != nil {
		return m.Count
	}
	return nil
}

type GetVacanciesListResponse struct {
	// Types that are valid to be assigned to Response:
	//	*GetVacanciesListResponse_Body_
	Response             isGetVacanciesListResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetVacanciesListResponse) Reset()         { *m = GetVacanciesListResponse{} }
func (m *GetVacanciesListResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListResponse) ProtoMessage()    {}
func (*GetVacanciesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{3}
}

func (m *GetVacanciesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse.Merge(m, src)
}
func (m *GetVacanciesListResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse.Size(m)
}
func (m *GetVacanciesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse proto.InternalMessageInfo

type isGetVacanciesListResponse_Response interface {
	isGetVacanciesListResponse_Response()
}

type GetVacanciesListResponse_Body_ struct {
	Body *GetVacanciesListResponse_Body `protobuf:"bytes,1,opt,name=body,proto3,oneof"`
}

func (*GetVacanciesListResponse_Body_) isGetVacanciesListResponse_Response() {}

func (m *GetVacanciesListResponse) GetResponse() isGetVacanciesListResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetVacanciesListResponse) GetBody() *GetVacanciesListResponse_Body {
	if x, ok := m.GetResponse().(*GetVacanciesListResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetVacanciesListResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetVacanciesListResponse_Body_)(nil),
	}
}

type GetVacanciesListResponse_CompanyActivityField struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacanciesListResponse_CompanyActivityField) Reset() {
	*m = GetVacanciesListResponse_CompanyActivityField{}
}
func (m *GetVacanciesListResponse_CompanyActivityField) String() string {
	return proto.CompactTextString(m)
}
func (*GetVacanciesListResponse_CompanyActivityField) ProtoMessage() {}
func (*GetVacanciesListResponse_CompanyActivityField) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{3, 0}
}

func (m *GetVacanciesListResponse_CompanyActivityField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse_CompanyActivityField.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse_CompanyActivityField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse_CompanyActivityField.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse_CompanyActivityField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse_CompanyActivityField.Merge(m, src)
}
func (m *GetVacanciesListResponse_CompanyActivityField) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse_CompanyActivityField.Size(m)
}
func (m *GetVacanciesListResponse_CompanyActivityField) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse_CompanyActivityField.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse_CompanyActivityField proto.InternalMessageInfo

func (m *GetVacanciesListResponse_CompanyActivityField) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacanciesListResponse_CompanyActivityField) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type GetVacanciesListResponse_Company struct {
	Title                string                     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	LogoUrl              string                     `protobuf:"bytes,2,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ActivityFieldsIds    map[string]*entities.Empty `protobuf:"bytes,3,rep,name=activity_fields_ids,json=activityFieldsIds,proto3" json:"activity_fields_ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetVacanciesListResponse_Company) Reset()         { *m = GetVacanciesListResponse_Company{} }
func (m *GetVacanciesListResponse_Company) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListResponse_Company) ProtoMessage()    {}
func (*GetVacanciesListResponse_Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{3, 1}
}

func (m *GetVacanciesListResponse_Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse_Company.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse_Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse_Company.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse_Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse_Company.Merge(m, src)
}
func (m *GetVacanciesListResponse_Company) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse_Company.Size(m)
}
func (m *GetVacanciesListResponse_Company) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse_Company.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse_Company proto.InternalMessageInfo

func (m *GetVacanciesListResponse_Company) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacanciesListResponse_Company) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *GetVacanciesListResponse_Company) GetActivityFieldsIds() map[string]*entities.Empty {
	if m != nil {
		return m.ActivityFieldsIds
	}
	return nil
}

type GetVacanciesListResponse_Vacancy struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MinSalary            int32    `protobuf:"varint,2,opt,name=min_salary,json=minSalary,proto3" json:"min_salary,omitempty"`
	MaxSalary            int32    `protobuf:"varint,3,opt,name=max_salary,json=maxSalary,proto3" json:"max_salary,omitempty"`
	Currency             Currency `protobuf:"varint,4,opt,name=currency,proto3,enum=personaappapi.vacancy.Currency" json:"currency,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CompanyId            string   `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacanciesListResponse_Vacancy) Reset()         { *m = GetVacanciesListResponse_Vacancy{} }
func (m *GetVacanciesListResponse_Vacancy) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListResponse_Vacancy) ProtoMessage()    {}
func (*GetVacanciesListResponse_Vacancy) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{3, 2}
}

func (m *GetVacanciesListResponse_Vacancy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse_Vacancy.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse_Vacancy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse_Vacancy.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse_Vacancy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse_Vacancy.Merge(m, src)
}
func (m *GetVacanciesListResponse_Vacancy) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse_Vacancy.Size(m)
}
func (m *GetVacanciesListResponse_Vacancy) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse_Vacancy.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse_Vacancy proto.InternalMessageInfo

func (m *GetVacanciesListResponse_Vacancy) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacanciesListResponse_Vacancy) GetMinSalary() int32 {
	if m != nil {
		return m.MinSalary
	}
	return 0
}

func (m *GetVacanciesListResponse_Vacancy) GetMaxSalary() int32 {
	if m != nil {
		return m.MaxSalary
	}
	return 0
}

func (m *GetVacanciesListResponse_Vacancy) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_CURRENCY_UNKNOWN
}

func (m *GetVacanciesListResponse_Vacancy) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *GetVacanciesListResponse_Vacancy) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

type GetVacanciesListResponse_Body struct {
	VacanciesIds         []string                                                  `protobuf:"bytes,1,rep,name=vacancies_ids,json=vacanciesIds,proto3" json:"vacancies_ids,omitempty"`
	Vacancies            map[string]*GetVacanciesListResponse_Vacancy              `protobuf:"bytes,2,rep,name=vacancies,proto3" json:"vacancies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Companies            map[string]*GetVacanciesListResponse_Company              `protobuf:"bytes,3,rep,name=companies,proto3" json:"companies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ActivityFields       map[string]*GetVacanciesListResponse_CompanyActivityField `protobuf:"bytes,4,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                  `json:"-"`
	XXX_unrecognized     []byte                                                    `json:"-"`
	XXX_sizecache        int32                                                     `json:"-"`
}

func (m *GetVacanciesListResponse_Body) Reset()         { *m = GetVacanciesListResponse_Body{} }
func (m *GetVacanciesListResponse_Body) String() string { return proto.CompactTextString(m) }
func (*GetVacanciesListResponse_Body) ProtoMessage()    {}
func (*GetVacanciesListResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{3, 3}
}

func (m *GetVacanciesListResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacanciesListResponse_Body.Unmarshal(m, b)
}
func (m *GetVacanciesListResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacanciesListResponse_Body.Marshal(b, m, deterministic)
}
func (m *GetVacanciesListResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacanciesListResponse_Body.Merge(m, src)
}
func (m *GetVacanciesListResponse_Body) XXX_Size() int {
	return xxx_messageInfo_GetVacanciesListResponse_Body.Size(m)
}
func (m *GetVacanciesListResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacanciesListResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacanciesListResponse_Body proto.InternalMessageInfo

func (m *GetVacanciesListResponse_Body) GetVacanciesIds() []string {
	if m != nil {
		return m.VacanciesIds
	}
	return nil
}

func (m *GetVacanciesListResponse_Body) GetVacancies() map[string]*GetVacanciesListResponse_Vacancy {
	if m != nil {
		return m.Vacancies
	}
	return nil
}

func (m *GetVacanciesListResponse_Body) GetCompanies() map[string]*GetVacanciesListResponse_Company {
	if m != nil {
		return m.Companies
	}
	return nil
}

func (m *GetVacanciesListResponse_Body) GetActivityFields() map[string]*GetVacanciesListResponse_CompanyActivityField {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

// Get Vacancy Details
type GetVacancyDetailsRequest struct {
	VacancyId            string   `protobuf:"bytes,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsRequest) Reset()         { *m = GetVacancyDetailsRequest{} }
func (m *GetVacancyDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsRequest) ProtoMessage()    {}
func (*GetVacancyDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{4}
}

func (m *GetVacancyDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsRequest.Unmarshal(m, b)
}
func (m *GetVacancyDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsRequest.Merge(m, src)
}
func (m *GetVacancyDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsRequest.Size(m)
}
func (m *GetVacancyDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsRequest proto.InternalMessageInfo

func (m *GetVacancyDetailsRequest) GetVacancyId() string {
	if m != nil {
		return m.VacancyId
	}
	return ""
}

type GetVacancyDetailsResponse struct {
	// Types that are valid to be assigned to Response:
	//	*GetVacancyDetailsResponse_Body_
	Response             isGetVacancyDetailsResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *GetVacancyDetailsResponse) Reset()         { *m = GetVacancyDetailsResponse{} }
func (m *GetVacancyDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse) ProtoMessage()    {}
func (*GetVacancyDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5}
}

func (m *GetVacancyDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse.Merge(m, src)
}
func (m *GetVacancyDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse.Size(m)
}
func (m *GetVacancyDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse proto.InternalMessageInfo

type isGetVacancyDetailsResponse_Response interface {
	isGetVacancyDetailsResponse_Response()
}

type GetVacancyDetailsResponse_Body_ struct {
	Body *GetVacancyDetailsResponse_Body `protobuf:"bytes,1,opt,name=body,proto3,oneof"`
}

func (*GetVacancyDetailsResponse_Body_) isGetVacancyDetailsResponse_Response() {}

func (m *GetVacancyDetailsResponse) GetResponse() isGetVacancyDetailsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetVacancyDetailsResponse) GetBody() *GetVacancyDetailsResponse_Body {
	if x, ok := m.GetResponse().(*GetVacancyDetailsResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetVacancyDetailsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetVacancyDetailsResponse_Body_)(nil),
	}
}

type GetVacancyDetailsResponse_Vacancy struct {
	Company              *GetVacancyDetailsResponse_Company  `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Location             *GetVacancyDetailsResponse_Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Title                string                              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                              `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MinSalary            int32                               `protobuf:"varint,5,opt,name=min_salary,json=minSalary,proto3" json:"min_salary,omitempty"`
	MaxSalary            int32                               `protobuf:"varint,6,opt,name=max_salary,json=maxSalary,proto3" json:"max_salary,omitempty"`
	Currency             Currency                            `protobuf:"varint,7,opt,name=currency,proto3,enum=personaappapi.vacancy.Currency" json:"currency,omitempty"`
	ImageUrl             string                              `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	WorkExperience       string                              `protobuf:"bytes,9,opt,name=work_experience,json=workExperience,proto3" json:"work_experience,omitempty"`
	WorkSchedule         string                              `protobuf:"bytes,10,opt,name=work_schedule,json=workSchedule,proto3" json:"work_schedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetVacancyDetailsResponse_Vacancy) Reset()         { *m = GetVacancyDetailsResponse_Vacancy{} }
func (m *GetVacancyDetailsResponse_Vacancy) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_Vacancy) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_Vacancy) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5, 0}
}

func (m *GetVacancyDetailsResponse_Vacancy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_Vacancy.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_Vacancy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_Vacancy.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_Vacancy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_Vacancy.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_Vacancy) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_Vacancy.Size(m)
}
func (m *GetVacancyDetailsResponse_Vacancy) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_Vacancy.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_Vacancy proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_Vacancy) GetCompany() *GetVacancyDetailsResponse_Company {
	if m != nil {
		return m.Company
	}
	return nil
}

func (m *GetVacancyDetailsResponse_Vacancy) GetLocation() *GetVacancyDetailsResponse_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetVacancyDetailsResponse_Vacancy) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Vacancy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Vacancy) GetMinSalary() int32 {
	if m != nil {
		return m.MinSalary
	}
	return 0
}

func (m *GetVacancyDetailsResponse_Vacancy) GetMaxSalary() int32 {
	if m != nil {
		return m.MaxSalary
	}
	return 0
}

func (m *GetVacancyDetailsResponse_Vacancy) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_CURRENCY_UNKNOWN
}

func (m *GetVacancyDetailsResponse_Vacancy) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Vacancy) GetWorkExperience() string {
	if m != nil {
		return m.WorkExperience
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Vacancy) GetWorkSchedule() string {
	if m != nil {
		return m.WorkSchedule
	}
	return ""
}

type GetVacancyDetailsResponse_Location struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsResponse_Location) Reset()         { *m = GetVacancyDetailsResponse_Location{} }
func (m *GetVacancyDetailsResponse_Location) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_Location) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5, 1}
}

func (m *GetVacancyDetailsResponse_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_Location.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_Location.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_Location.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_Location) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_Location.Size(m)
}
func (m *GetVacancyDetailsResponse_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_Location.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_Location proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_Location) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GetVacancyDetailsResponse_Location) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type GetVacancyDetailsResponse_Company struct {
	Title                string                                                     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                                                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              string                                                     `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Phone                string                                                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ActivityFields       map[string]*GetVacancyDetailsResponse_CompanyActivityField `protobuf:"bytes,5,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *GetVacancyDetailsResponse_Company) Reset()         { *m = GetVacancyDetailsResponse_Company{} }
func (m *GetVacancyDetailsResponse_Company) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_Company) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5, 2}
}

func (m *GetVacancyDetailsResponse_Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_Company.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_Company.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_Company.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_Company) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_Company.Size(m)
}
func (m *GetVacancyDetailsResponse_Company) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_Company.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_Company proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_Company) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Company) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Company) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Company) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetVacancyDetailsResponse_Company) GetActivityFields() map[string]*GetVacancyDetailsResponse_CompanyActivityField {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

type GetVacancyDetailsResponse_CompanyActivityField struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVacancyDetailsResponse_CompanyActivityField) Reset() {
	*m = GetVacancyDetailsResponse_CompanyActivityField{}
}
func (m *GetVacancyDetailsResponse_CompanyActivityField) String() string {
	return proto.CompactTextString(m)
}
func (*GetVacancyDetailsResponse_CompanyActivityField) ProtoMessage() {}
func (*GetVacancyDetailsResponse_CompanyActivityField) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5, 3}
}

func (m *GetVacancyDetailsResponse_CompanyActivityField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_CompanyActivityField.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_CompanyActivityField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_CompanyActivityField.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_CompanyActivityField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_CompanyActivityField.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_CompanyActivityField) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_CompanyActivityField.Size(m)
}
func (m *GetVacancyDetailsResponse_CompanyActivityField) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_CompanyActivityField.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_CompanyActivityField proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_CompanyActivityField) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetVacancyDetailsResponse_CompanyActivityField) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type GetVacancyDetailsResponse_Body struct {
	Vacancy              *GetVacancyDetailsResponse_Vacancy `protobuf:"bytes,1,opt,name=vacancy,proto3" json:"vacancy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *GetVacancyDetailsResponse_Body) Reset()         { *m = GetVacancyDetailsResponse_Body{} }
func (m *GetVacancyDetailsResponse_Body) String() string { return proto.CompactTextString(m) }
func (*GetVacancyDetailsResponse_Body) ProtoMessage()    {}
func (*GetVacancyDetailsResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_47be6d1234ea964b, []int{5, 4}
}

func (m *GetVacancyDetailsResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVacancyDetailsResponse_Body.Unmarshal(m, b)
}
func (m *GetVacancyDetailsResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVacancyDetailsResponse_Body.Marshal(b, m, deterministic)
}
func (m *GetVacancyDetailsResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVacancyDetailsResponse_Body.Merge(m, src)
}
func (m *GetVacancyDetailsResponse_Body) XXX_Size() int {
	return xxx_messageInfo_GetVacancyDetailsResponse_Body.Size(m)
}
func (m *GetVacancyDetailsResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVacancyDetailsResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetVacancyDetailsResponse_Body proto.InternalMessageInfo

func (m *GetVacancyDetailsResponse_Body) GetVacancy() *GetVacancyDetailsResponse_Vacancy {
	if m != nil {
		return m.Vacancy
	}
	return nil
}

func init() {
	proto.RegisterEnum("personaappapi.vacancy.Currency", Currency_name, Currency_value)
	proto.RegisterType((*GetVacanciesFiltersListRequest)(nil), "personaappapi.vacancy.GetVacanciesFiltersListRequest")
	proto.RegisterType((*GetVacanciesFiltersListResponse)(nil), "personaappapi.vacancy.GetVacanciesFiltersListResponse")
	proto.RegisterType((*GetVacanciesFiltersListResponse_VacancyFilter)(nil), "personaappapi.vacancy.GetVacanciesFiltersListResponse.VacancyFilter")
	proto.RegisterType((*GetVacanciesFiltersListResponse_Body)(nil), "personaappapi.vacancy.GetVacanciesFiltersListResponse.Body")
	proto.RegisterMapType((map[string]*GetVacanciesFiltersListResponse_VacancyFilter)(nil), "personaappapi.vacancy.GetVacanciesFiltersListResponse.Body.VacancyFiltersEntry")
	proto.RegisterType((*GetVacanciesListRequest)(nil), "personaappapi.vacancy.GetVacanciesListRequest")
	proto.RegisterMapType((map[string]*entities.Empty)(nil), "personaappapi.vacancy.GetVacanciesListRequest.FilterIdsEntry")
	proto.RegisterType((*GetVacanciesListResponse)(nil), "personaappapi.vacancy.GetVacanciesListResponse")
	proto.RegisterType((*GetVacanciesListResponse_CompanyActivityField)(nil), "personaappapi.vacancy.GetVacanciesListResponse.CompanyActivityField")
	proto.RegisterType((*GetVacanciesListResponse_Company)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Company")
	proto.RegisterMapType((map[string]*entities.Empty)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Company.ActivityFieldsIdsEntry")
	proto.RegisterType((*GetVacanciesListResponse_Vacancy)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Vacancy")
	proto.RegisterType((*GetVacanciesListResponse_Body)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Body")
	proto.RegisterMapType((map[string]*GetVacanciesListResponse_CompanyActivityField)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Body.ActivityFieldsEntry")
	proto.RegisterMapType((map[string]*GetVacanciesListResponse_Company)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Body.CompaniesEntry")
	proto.RegisterMapType((map[string]*GetVacanciesListResponse_Vacancy)(nil), "personaappapi.vacancy.GetVacanciesListResponse.Body.VacanciesEntry")
	proto.RegisterType((*GetVacancyDetailsRequest)(nil), "personaappapi.vacancy.GetVacancyDetailsRequest")
	proto.RegisterType((*GetVacancyDetailsResponse)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse")
	proto.RegisterType((*GetVacancyDetailsResponse_Vacancy)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.Vacancy")
	proto.RegisterType((*GetVacancyDetailsResponse_Location)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.Location")
	proto.RegisterType((*GetVacancyDetailsResponse_Company)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.Company")
	proto.RegisterMapType((map[string]*GetVacancyDetailsResponse_CompanyActivityField)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.Company.ActivityFieldsEntry")
	proto.RegisterType((*GetVacancyDetailsResponse_CompanyActivityField)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.CompanyActivityField")
	proto.RegisterType((*GetVacancyDetailsResponse_Body)(nil), "personaappapi.vacancy.GetVacancyDetailsResponse.Body")
}

func init() { proto.RegisterFile("vacancy/vacancy.proto", fileDescriptor_47be6d1234ea964b) }

var fileDescriptor_47be6d1234ea964b = []byte{
	// 1164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcf, 0x52, 0x1b, 0x47,
	0x13, 0xb7, 0xb4, 0x08, 0x69, 0x5b, 0x58, 0x88, 0x31, 0xb6, 0xd7, 0xeb, 0x0f, 0x4c, 0xf1, 0x1d,
	0x42, 0xe5, 0xb0, 0x4a, 0x44, 0x9c, 0xd8, 0xa1, 0x72, 0x00, 0x21, 0x1b, 0x62, 0x82, 0x93, 0xa5,
	0x20, 0x15, 0x9c, 0x2a, 0xd5, 0xb0, 0x3b, 0x92, 0xa7, 0x58, 0x76, 0xd7, 0xfb, 0x47, 0x66, 0x2f,
	0xb9, 0xc6, 0x95, 0x5c, 0xf2, 0x06, 0xb9, 0xe5, 0x29, 0xf2, 0x04, 0x39, 0xe6, 0x90, 0x53, 0x1e,
	0x23, 0x0f, 0x90, 0xda, 0xd9, 0xd9, 0x65, 0x47, 0x48, 0x46, 0x12, 0xe4, 0xc4, 0x4e, 0x77, 0xcf,
	0xaf, 0x7b, 0x7a, 0xba, 0x7f, 0xcd, 0x08, 0xee, 0xf6, 0xb1, 0x81, 0x6d, 0x23, 0x6a, 0xf0, 0xbf,
	0x9a, 0xeb, 0x39, 0x81, 0x83, 0xee, 0xba, 0xc4, 0xf3, 0x1d, 0x1b, 0x63, 0xd7, 0xc5, 0x2e, 0xd5,
	0xb8, 0x52, 0xbd, 0x4f, 0xec, 0x80, 0x06, 0x94, 0xf8, 0x8d, 0xf4, 0x23, 0xb1, 0x57, 0x97, 0x7b,
	0x8e, 0xd3, 0xb3, 0x48, 0x83, 0xad, 0x4e, 0xc2, 0x6e, 0xe3, 0xad, 0x87, 0xdd, 0x18, 0x23, 0xd1,
	0xaf, 0xae, 0xc0, 0xf2, 0x73, 0x12, 0x1c, 0x31, 0x18, 0x4a, 0xfc, 0x67, 0xd4, 0x0a, 0x88, 0xe7,
	0xef, 0x51, 0x3f, 0xd0, 0xc9, 0x9b, 0x90, 0xf8, 0xc1, 0xea, 0x1f, 0x12, 0x3c, 0x1a, 0x69, 0xe2,
	0xbb, 0x8e, 0xed, 0x13, 0xf4, 0x0d, 0xcc, 0x9c, 0x38, 0x66, 0xa4, 0x14, 0x56, 0x0a, 0x6b, 0xd5,
	0xe6, 0x86, 0x36, 0x34, 0x48, 0xed, 0x0a, 0x14, 0x6d, 0xcb, 0x31, 0xa3, 0x9d, 0x5b, 0x3a, 0x83,
	0x52, 0x37, 0xe0, 0x76, 0x62, 0x1c, 0x25, 0xa6, 0x68, 0x11, 0x4a, 0x01, 0x0d, 0x2c, 0xc2, 0x9c,
	0xc8, 0x7a, 0xb2, 0x88, 0xa5, 0xd8, 0xa2, 0xd8, 0x57, 0x8a, 0x89, 0x94, 0x2d, 0xd4, 0x9f, 0x8a,
	0x30, 0x13, 0xa3, 0xa1, 0x73, 0x98, 0xe7, 0xde, 0x3b, 0xdd, 0xc4, 0xa3, 0x52, 0x58, 0x91, 0xd6,
	0xaa, 0xcd, 0x97, 0xd7, 0x88, 0x51, 0x13, 0x02, 0xf3, 0xdb, 0x76, 0xe0, 0x45, 0x7a, 0xad, 0x2f,
	0x08, 0xd5, 0x1f, 0x0b, 0x70, 0x67, 0x88, 0x1d, 0xaa, 0x83, 0x74, 0x4a, 0x22, 0x7e, 0x88, 0xf8,
	0x13, 0x1d, 0x43, 0xa9, 0x8f, 0xad, 0x90, 0xb0, 0x23, 0x54, 0x9b, 0xdb, 0x53, 0x46, 0x26, 0x38,
	0xd3, 0x13, 0xc8, 0xcf, 0x8b, 0x4f, 0x0a, 0x5b, 0x00, 0x15, 0x8f, 0x1b, 0xad, 0xfe, 0x5e, 0x84,
	0xfb, 0x79, 0xa0, 0xdc, 0x45, 0xa3, 0xef, 0x01, 0x92, 0x1c, 0x75, 0xa8, 0x99, 0xa6, 0xe9, 0x8b,
	0x31, 0x82, 0xc9, 0x61, 0x68, 0x89, 0xf7, 0x5d, 0x93, 0x27, 0x45, 0xee, 0xa6, 0x6b, 0xb4, 0x0e,
	0xb3, 0x4e, 0xb7, 0xeb, 0x93, 0x80, 0x1f, 0xf3, 0xa1, 0x96, 0x54, 0xa6, 0x96, 0x56, 0xa6, 0xb6,
	0x6b, 0x07, 0xeb, 0xcd, 0xa3, 0x38, 0x6c, 0x9d, 0x9b, 0xa2, 0x8f, 0xa1, 0x64, 0x38, 0xa1, 0x1d,
	0x28, 0xd2, 0xd5, 0x7b, 0x12, 0x4b, 0xf5, 0x15, 0xd4, 0xc4, 0x20, 0x86, 0x64, 0x7c, 0x5d, 0xcc,
	0xf8, 0xd2, 0xc0, 0x21, 0xb3, 0x16, 0x6a, 0x9f, 0xb9, 0x41, 0x94, 0x4b, 0xe5, 0xea, 0x2f, 0x55,
	0x50, 0x2e, 0x1f, 0x9d, 0x37, 0xc1, 0x97, 0x42, 0x13, 0x7c, 0x32, 0x76, 0xe6, 0x86, 0x55, 0xff,
	0x16, 0x2c, 0xb6, 0x9c, 0x33, 0x17, 0xdb, 0xd1, 0xa6, 0x11, 0xd0, 0x3e, 0x0d, 0xa2, 0x67, 0x94,
	0x58, 0xe6, 0x44, 0x4d, 0xf0, 0x6b, 0x11, 0xca, 0x1c, 0x64, 0xc4, 0xbe, 0x07, 0x50, 0xb1, 0x9c,
	0x9e, 0xd3, 0x09, 0x3d, 0x8b, 0x6f, 0x2d, 0xc7, 0xeb, 0x43, 0xcf, 0x42, 0x3f, 0xc0, 0x1d, 0xcc,
	0x3d, 0x77, 0xba, 0xb1, 0x6b, 0x9f, 0x55, 0x85, 0xc4, 0xaa, 0x62, 0x7f, 0xd2, 0xb3, 0xf1, 0x30,
	0x34, 0xe1, 0x30, 0x7e, 0x56, 0x26, 0x0b, 0x78, 0x50, 0xae, 0x1a, 0x70, 0x6f, 0xb8, 0xf1, 0x0d,
	0x5e, 0xa7, 0xfa, 0x57, 0x01, 0xca, 0xbc, 0x6d, 0x46, 0x64, 0x68, 0x09, 0xe0, 0x8c, 0xda, 0x1d,
	0x1f, 0x5b, 0xd8, 0x8b, 0x18, 0x7e, 0x49, 0x97, 0xcf, 0xa8, 0x7d, 0xc0, 0x04, 0x4c, 0x8d, 0xcf,
	0x53, 0xb5, 0xc4, 0xd5, 0xf8, 0x9c, 0xab, 0x37, 0xa0, 0x62, 0x84, 0x9e, 0x47, 0x6c, 0x23, 0x52,
	0x66, 0x56, 0x0a, 0x6b, 0xb5, 0xe6, 0xa3, 0x11, 0x99, 0x6b, 0x71, 0x33, 0x3d, 0xdb, 0x80, 0x1e,
	0x82, 0x4c, 0xcf, 0x70, 0x8f, 0xb0, 0xdb, 0x29, 0xb1, 0xa0, 0x2a, 0x4c, 0x10, 0x5f, 0xcf, 0x12,
	0x80, 0x91, 0xe4, 0xb4, 0x43, 0x4d, 0x65, 0x96, 0x69, 0x65, 0x2e, 0xd9, 0x35, 0xd5, 0xbf, 0x4b,
	0x9c, 0xff, 0xfe, 0x0f, 0xb7, 0xfb, 0xe9, 0x8d, 0x64, 0x6d, 0x2d, 0xeb, 0x73, 0x99, 0x30, 0x6e,
	0x4d, 0x0c, 0x72, 0xb6, 0x56, 0x8a, 0xec, 0x86, 0x5b, 0xd3, 0x54, 0xaf, 0x96, 0xa9, 0x78, 0xf7,
	0x67, 0xa8, 0xb1, 0x8b, 0x24, 0xba, 0xd8, 0x85, 0x74, 0x0d, 0x17, 0xad, 0x14, 0x85, 0xbb, 0xc8,
	0x50, 0xd1, 0x1b, 0x98, 0x1f, 0xa8, 0x58, 0x65, 0x86, 0x39, 0xda, 0x99, 0xca, 0x91, 0x58, 0x7d,
	0x9c, 0xe3, 0xc5, 0x3a, 0x55, 0x43, 0xa8, 0x89, 0x47, 0x1e, 0x52, 0x9c, 0x5f, 0x89, 0xc5, 0xf9,
	0xd9, 0xa4, 0xc1, 0xf0, 0xfa, 0xcc, 0x97, 0x6d, 0x08, 0x35, 0x31, 0x0d, 0xff, 0x81, 0x5b, 0xde,
	0xb1, 0x79, 0xb7, 0xf1, 0x44, 0x1b, 0x92, 0x95, 0x9b, 0x99, 0x68, 0xc3, 0x9c, 0x0b, 0xce, 0x46,
	0x4d, 0xb4, 0xa7, 0x39, 0x46, 0x8e, 0xb6, 0x49, 0x80, 0xa9, 0xe5, 0xa7, 0x13, 0x6d, 0x09, 0x20,
	0x9d, 0xfe, 0xd4, 0xe4, 0x01, 0xf2, 0xa2, 0x8c, 0x76, 0xcd, 0xd5, 0xdf, 0x64, 0x78, 0x30, 0x64,
	0x2f, 0xa7, 0xf3, 0x17, 0x02, 0x9d, 0x3f, 0xbe, 0xea, 0x0c, 0x83, 0xfb, 0x45, 0x3e, 0xff, 0x53,
	0xba, 0x60, 0x1a, 0x1d, 0xca, 0xbc, 0x53, 0x39, 0xf6, 0x93, 0x89, 0xb1, 0xd3, 0xdb, 0x49, 0x81,
	0xd0, 0x61, 0xcc, 0xe4, 0x06, 0x0e, 0xa8, 0x63, 0xf3, 0xa4, 0x3f, 0x9d, 0x18, 0x74, 0x8f, 0x03,
	0xe8, 0x19, 0xd4, 0x05, 0x29, 0x4a, 0x79, 0x52, 0x5c, 0x81, 0xaa, 0x49, 0x7c, 0xc3, 0xa3, 0x2e,
	0xf3, 0x37, 0xc3, 0x74, 0x79, 0xd1, 0x00, 0x6d, 0x96, 0xde, 0x4f, 0x9b, 0xb3, 0xef, 0xa3, 0xcd,
	0xf2, 0xb5, 0x68, 0xb3, 0x32, 0x40, 0x9b, 0x1f, 0xc0, 0xfc, 0x5b, 0xc7, 0x3b, 0xed, 0x90, 0x73,
	0x97, 0x78, 0x94, 0xd8, 0x06, 0x51, 0x64, 0x66, 0x52, 0x8b, 0xc5, 0xed, 0x4c, 0x1a, 0xf3, 0x26,
	0x33, 0xf4, 0x8d, 0xd7, 0xc4, 0x0c, 0x2d, 0xa2, 0x00, 0x33, 0x9b, 0x8b, 0x85, 0x07, 0x5c, 0xa6,
	0x6e, 0x43, 0x25, 0xcd, 0x19, 0x52, 0xa1, 0x62, 0xe1, 0x80, 0x06, 0xa1, 0x99, 0x4c, 0x90, 0xa2,
	0x9e, 0xad, 0xd1, 0xff, 0x40, 0xb6, 0x1c, 0xbb, 0x97, 0x28, 0x8b, 0x4c, 0x79, 0x21, 0x50, 0xff,
	0xb9, 0x72, 0x4c, 0x0f, 0xe4, 0xbb, 0x78, 0x39, 0xdf, 0xf9, 0x41, 0x2e, 0x89, 0x83, 0x7c, 0x11,
	0x4a, 0xee, 0x6b, 0xc7, 0x26, 0xfc, 0x9a, 0x92, 0x05, 0x0a, 0x2f, 0x93, 0x65, 0x89, 0x91, 0xe5,
	0xde, 0xb4, 0xb5, 0x38, 0x16, 0x61, 0xbe, 0x1b, 0x9b, 0x42, 0x5e, 0x89, 0x14, 0xd2, 0x9e, 0x36,
	0xac, 0x51, 0x1c, 0x72, 0x23, 0xff, 0x61, 0x1d, 0xf3, 0x29, 0xab, 0x43, 0x99, 0x07, 0x34, 0x75,
	0x47, 0xa7, 0x34, 0x9f, 0x02, 0xe5, 0x39, 0xee, 0xc3, 0x23, 0xa8, 0xa4, 0x95, 0x8e, 0x16, 0xa1,
	0xde, 0x3a, 0xd4, 0xf5, 0xf6, 0x7e, 0xeb, 0xbb, 0xce, 0xe1, 0xfe, 0x8b, 0xfd, 0x97, 0xdf, 0xee,
	0xd7, 0x6f, 0xa1, 0x3a, 0xcc, 0x5d, 0x48, 0x37, 0x77, 0xea, 0x05, 0x51, 0x72, 0xb0, 0x5d, 0x2f,
	0x0a, 0x92, 0xf6, 0xa1, 0x5e, 0x97, 0x9a, 0x3f, 0x4b, 0xb0, 0xf0, 0x75, 0x12, 0xe8, 0xa6, 0xeb,
	0xa6, 0xfc, 0xf4, 0xae, 0x20, 0xbe, 0x11, 0x72, 0x8f, 0x0d, 0xf4, 0x78, 0xd2, 0xc7, 0x09, 0x23,
	0x62, 0xf5, 0xd3, 0xe9, 0xde, 0x34, 0xc8, 0x87, 0xfa, 0xe0, 0x90, 0x40, 0xda, 0x64, 0x4f, 0x12,
	0xb5, 0x31, 0xe1, 0xf4, 0x41, 0x7d, 0x58, 0xb8, 0x74, 0x4f, 0xa8, 0x31, 0xfe, 0x8d, 0x26, 0x6e,
	0x3f, 0x9a, 0xb4, 0x04, 0xb6, 0xda, 0x70, 0xcf, 0xb1, 0x2d, 0x6a, 0x93, 0xdc, 0x4e, 0xcd, 0x70,
	0x3c, 0xb2, 0x55, 0x7d, 0xee, 0xb9, 0x06, 0xdf, 0x75, 0xbc, 0x7c, 0xa1, 0x6d, 0xb8, 0xa7, 0xbd,
	0x46, 0xcf, 0x73, 0x0d, 0xec, 0xd2, 0xf4, 0x77, 0x82, 0x93, 0x59, 0xf6, 0x38, 0x5a, 0xff, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0xfa, 0x8b, 0x93, 0x41, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonaAppVacancyClient is the client API for PersonaAppVacancy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppVacancyClient interface {
	GetVacanciesFiltersList(ctx context.Context, in *GetVacanciesFiltersListRequest, opts ...grpc.CallOption) (*GetVacanciesFiltersListResponse, error)
	GetVacanciesList(ctx context.Context, in *GetVacanciesListRequest, opts ...grpc.CallOption) (*GetVacanciesListResponse, error)
	GetVacancyDetails(ctx context.Context, in *GetVacancyDetailsRequest, opts ...grpc.CallOption) (*GetVacancyDetailsResponse, error)
}

type personaAppVacancyClient struct {
	cc *grpc.ClientConn
}

func NewPersonaAppVacancyClient(cc *grpc.ClientConn) PersonaAppVacancyClient {
	return &personaAppVacancyClient{cc}
}

func (c *personaAppVacancyClient) GetVacanciesFiltersList(ctx context.Context, in *GetVacanciesFiltersListRequest, opts ...grpc.CallOption) (*GetVacanciesFiltersListResponse, error) {
	out := new(GetVacanciesFiltersListResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacanciesFiltersList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) GetVacanciesList(ctx context.Context, in *GetVacanciesListRequest, opts ...grpc.CallOption) (*GetVacanciesListResponse, error) {
	out := new(GetVacanciesListResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacanciesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppVacancyClient) GetVacancyDetails(ctx context.Context, in *GetVacancyDetailsRequest, opts ...grpc.CallOption) (*GetVacancyDetailsResponse, error) {
	out := new(GetVacancyDetailsResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppVacancyServer is the server API for PersonaAppVacancy service.
type PersonaAppVacancyServer interface {
	GetVacanciesFiltersList(context.Context, *GetVacanciesFiltersListRequest) (*GetVacanciesFiltersListResponse, error)
	GetVacanciesList(context.Context, *GetVacanciesListRequest) (*GetVacanciesListResponse, error)
	GetVacancyDetails(context.Context, *GetVacancyDetailsRequest) (*GetVacancyDetailsResponse, error)
}

// UnimplementedPersonaAppVacancyServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppVacancyServer struct {
}

func (*UnimplementedPersonaAppVacancyServer) GetVacanciesFiltersList(ctx context.Context, req *GetVacanciesFiltersListRequest) (*GetVacanciesFiltersListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacanciesFiltersList not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) GetVacanciesList(ctx context.Context, req *GetVacanciesListRequest) (*GetVacanciesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacanciesList not implemented")
}
func (*UnimplementedPersonaAppVacancyServer) GetVacancyDetails(ctx context.Context, req *GetVacancyDetailsRequest) (*GetVacancyDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacancyDetails not implemented")
}

func RegisterPersonaAppVacancyServer(s *grpc.Server, srv PersonaAppVacancyServer) {
	s.RegisterService(&_PersonaAppVacancy_serviceDesc, srv)
}

func _PersonaAppVacancy_GetVacanciesFiltersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacanciesFiltersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacanciesFiltersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacanciesFiltersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacanciesFiltersList(ctx, req.(*GetVacanciesFiltersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_GetVacanciesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacanciesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacanciesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacanciesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacanciesList(ctx, req.(*GetVacanciesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppVacancy_GetVacancyDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacancyDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppVacancyServer).GetVacancyDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.vacancy.PersonaAppVacancy/GetVacancyDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppVacancyServer).GetVacancyDetails(ctx, req.(*GetVacancyDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaAppVacancy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.vacancy.PersonaAppVacancy",
	HandlerType: (*PersonaAppVacancyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVacanciesFiltersList",
			Handler:    _PersonaAppVacancy_GetVacanciesFiltersList_Handler,
		},
		{
			MethodName: "GetVacanciesList",
			Handler:    _PersonaAppVacancy_GetVacanciesList_Handler,
		},
		{
			MethodName: "GetVacancyDetails",
			Handler:    _PersonaAppVacancy_GetVacancyDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vacancy/vacancy.proto",
}
