// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

package personaappapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNKNOWN AccountType = 0
	AccountType_ACCOUNT_TYPE_COMPANY AccountType = 1
	AccountType_ACCOUNT_TYPE_PERSONA AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "ACCOUNT_TYPE_UNKNOWN",
	1: "ACCOUNT_TYPE_COMPANY",
	2: "ACCOUNT_TYPE_PERSONA",
}

var AccountType_value = map[string]int32{
	"ACCOUNT_TYPE_UNKNOWN": 0,
	"ACCOUNT_TYPE_COMPANY": 1,
	"ACCOUNT_TYPE_PERSONA": 2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("personaappapi.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*Empty)(nil), "personaappapi.Empty")
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor_a5f7344b79fcc63d) }

var fileDescriptor_a5f7344b79fcc63d = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x2b, 0xc9,
	0x2c, 0xc9, 0x4c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0x4b, 0x4c, 0x2c, 0x28, 0x48, 0x2c, 0xc8, 0x54, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d,
	0x28, 0xa9, 0xd4, 0x8a, 0xe6, 0xe2, 0x76, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x09, 0xa9, 0x2c,
	0x48, 0x15, 0x92, 0xe0, 0x12, 0x71, 0x74, 0x76, 0xf6, 0x0f, 0xf5, 0x0b, 0x89, 0x0f, 0x89, 0x0c,
	0x70, 0x8d, 0x0f, 0xf5, 0xf3, 0xf6, 0xf3, 0x0f, 0xf7, 0x13, 0x60, 0xc0, 0x90, 0x71, 0xf6, 0xf7,
	0x0d, 0x70, 0xf4, 0x8b, 0x14, 0x60, 0xc4, 0x90, 0x09, 0x70, 0x0d, 0x0a, 0xf6, 0xf7, 0x73, 0x14,
	0x60, 0x4a, 0x62, 0x03, 0xdb, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x42, 0x88, 0xba,
	0x8d, 0x00, 0x00, 0x00,
}
