// Code generated by protoc-gen-go. DO NOT EDIT.
// source: personaapp.proto

package personaappapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNKNOWN AccountType = 0
	AccountType_ACCOUNT_TYPE_COMPANY AccountType = 1
	AccountType_ACCOUNT_TYPE_PERSONA AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "ACCOUNT_TYPE_UNKNOWN",
	1: "ACCOUNT_TYPE_COMPANY",
	2: "ACCOUNT_TYPE_PERSONA",
}

var AccountType_value = map[string]int32{
	"ACCOUNT_TYPE_UNKNOWN": 0,
	"ACCOUNT_TYPE_COMPANY": 1,
	"ACCOUNT_TYPE_PERSONA": 2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{0}
}

type RegisterRequest struct {
	Email                string      `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string      `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string      `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	AccountType          AccountType `protobuf:"varint,4,opt,name=account_type,json=accountType,proto3,enum=personaappapi.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNKNOWN
}

type Token struct {
	Token                string               `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AccountType          AccountType          `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=personaappapi.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *Token) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNKNOWN
}

type RegisterResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type LogoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{5}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{6}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type RefreshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{7}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

type RefreshResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshResponse) Reset()         { *m = RefreshResponse{} }
func (m *RefreshResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshResponse) ProtoMessage()    {}
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{8}
}

func (m *RefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshResponse.Unmarshal(m, b)
}
func (m *RefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshResponse.Marshal(b, m, deterministic)
}
func (m *RefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshResponse.Merge(m, src)
}
func (m *RefreshResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshResponse.Size(m)
}
func (m *RefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshResponse proto.InternalMessageInfo

func (m *RefreshResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type UpdateCompanyRequest struct {
	Title                *wrappers.StringValue `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              *wrappers.StringValue `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ScopeId              *wrappers.StringValue `protobuf:"bytes,4,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateCompanyRequest) Reset()         { *m = UpdateCompanyRequest{} }
func (m *UpdateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyRequest) ProtoMessage()    {}
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{9}
}

func (m *UpdateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyRequest.Merge(m, src)
}
func (m *UpdateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyRequest.Size(m)
}
func (m *UpdateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyRequest proto.InternalMessageInfo

func (m *UpdateCompanyRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *UpdateCompanyRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateCompanyRequest) GetLogoUrl() *wrappers.StringValue {
	if m != nil {
		return m.LogoUrl
	}
	return nil
}

func (m *UpdateCompanyRequest) GetScopeId() *wrappers.StringValue {
	if m != nil {
		return m.ScopeId
	}
	return nil
}

type UpdateCompanyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCompanyResponse) Reset()         { *m = UpdateCompanyResponse{} }
func (m *UpdateCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyResponse) ProtoMessage()    {}
func (*UpdateCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6083bb8799e537c, []int{10}
}

func (m *UpdateCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyResponse.Unmarshal(m, b)
}
func (m *UpdateCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyResponse.Merge(m, src)
}
func (m *UpdateCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyResponse.Size(m)
}
func (m *UpdateCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("personaappapi.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*RegisterRequest)(nil), "personaappapi.RegisterRequest")
	proto.RegisterType((*Token)(nil), "personaappapi.Token")
	proto.RegisterType((*RegisterResponse)(nil), "personaappapi.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "personaappapi.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "personaappapi.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "personaappapi.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "personaappapi.LogoutResponse")
	proto.RegisterType((*RefreshRequest)(nil), "personaappapi.RefreshRequest")
	proto.RegisterType((*RefreshResponse)(nil), "personaappapi.RefreshResponse")
	proto.RegisterType((*UpdateCompanyRequest)(nil), "personaappapi.UpdateCompanyRequest")
	proto.RegisterType((*UpdateCompanyResponse)(nil), "personaappapi.UpdateCompanyResponse")
}

func init() { proto.RegisterFile("personaapp.proto", fileDescriptor_a6083bb8799e537c) }

var fileDescriptor_a6083bb8799e537c = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xdc, 0x7e, 0x69, 0xd3, 0x9b, 0xa6, 0xb5, 0x46, 0x41, 0x44, 0xa6, 0x4d, 0x2b, 0xc3,
	0xa2, 0xea, 0xc2, 0x95, 0xc2, 0x02, 0x21, 0xd4, 0x0a, 0x13, 0x45, 0x02, 0x15, 0x9c, 0xc8, 0x4d,
	0x40, 0x85, 0x85, 0x35, 0x4d, 0xa6, 0xae, 0x85, 0xe3, 0x19, 0x3c, 0x63, 0x95, 0xbc, 0x02, 0x2f,
	0x00, 0x0f, 0xcb, 0x02, 0x79, 0x3c, 0x26, 0x8e, 0x93, 0xb4, 0xa2, 0x3b, 0xdf, 0x7b, 0xce, 0x3d,
	0x73, 0x7f, 0x8e, 0x0c, 0x3a, 0x23, 0x31, 0xa7, 0x11, 0xc6, 0x8c, 0x59, 0x2c, 0xa6, 0x82, 0xa2,
	0xfa, 0x2c, 0x83, 0x59, 0x60, 0x1c, 0xf8, 0x94, 0xfa, 0x21, 0x39, 0x91, 0xe0, 0x55, 0x72, 0x7d,
	0x22, 0x82, 0x09, 0xe1, 0x02, 0x4f, 0x14, 0xdf, 0x68, 0x95, 0x09, 0xb7, 0x31, 0x66, 0xa9, 0x46,
	0x86, 0x9b, 0xbf, 0x34, 0xd8, 0x75, 0x89, 0x1f, 0x70, 0x41, 0x62, 0x97, 0x7c, 0x4b, 0x08, 0x17,
	0xa8, 0x01, 0x15, 0x32, 0xc1, 0x41, 0xd8, 0xd4, 0x0e, 0xb5, 0xa3, 0x2d, 0x37, 0x0b, 0xd2, 0x2c,
	0xbb, 0xa1, 0x11, 0x69, 0xae, 0x65, 0x59, 0x19, 0x20, 0x03, 0xaa, 0x0c, 0x73, 0x7e, 0x4b, 0xe3,
	0x71, 0x73, 0x5d, 0x02, 0x7f, 0x63, 0x74, 0x0a, 0xdb, 0x78, 0x34, 0xa2, 0x49, 0x24, 0x3c, 0x31,
	0x65, 0xa4, 0xf9, 0xff, 0xa1, 0x76, 0xb4, 0xd3, 0x36, 0xac, 0xb9, 0x11, 0x2c, 0x3b, 0xa3, 0x0c,
	0xa6, 0x8c, 0xb8, 0x35, 0x3c, 0x0b, 0xcc, 0x9f, 0x1a, 0x54, 0x06, 0xf4, 0x2b, 0x89, 0xd2, 0xa7,
	0x45, 0xfa, 0x91, 0x37, 0x24, 0x03, 0xf4, 0x12, 0x80, 0x7c, 0x67, 0x41, 0x4c, 0xb8, 0x87, 0x85,
	0xec, 0xaa, 0xd6, 0x36, 0xac, 0x6c, 0x5e, 0x2b, 0x9f, 0xd7, 0x1a, 0xe4, 0x0b, 0x71, 0xb7, 0x14,
	0xdb, 0x16, 0x0b, 0x9d, 0xad, 0xff, 0x5b, 0x67, 0x67, 0xa0, 0xcf, 0x76, 0xc6, 0x19, 0x8d, 0x38,
	0x41, 0xc7, 0xc5, 0x1e, 0x6b, 0xed, 0x46, 0x49, 0x4b, 0x0e, 0xa2, 0x3a, 0x37, 0x5f, 0xc3, 0xf6,
	0x7b, 0xea, 0x07, 0x51, 0x61, 0xe1, 0x61, 0x1a, 0xe7, 0xf3, 0xc9, 0x60, 0x6e, 0xb5, 0x6b, 0xf3,
	0xab, 0x35, 0x5f, 0x41, 0x5d, 0x29, 0x3c, 0xe0, 0xf9, 0x5d, 0x59, 0x4c, 0x13, 0xa1, 0xde, 0x37,
	0x75, 0xd8, 0xc9, 0x13, 0x99, 0x5c, 0x9a, 0x71, 0xc9, 0x75, 0x4c, 0xf8, 0x4d, 0xce, 0x39, 0x4d,
	0x7d, 0xa2, 0x32, 0x0f, 0x78, 0xf3, 0xb7, 0x06, 0x8d, 0x21, 0x1b, 0x63, 0x41, 0x3a, 0x74, 0xc2,
	0x70, 0x34, 0xcd, 0x67, 0x6f, 0x43, 0x45, 0x04, 0x22, 0x24, 0x4a, 0x64, 0x6f, 0xe1, 0x80, 0x17,
	0x22, 0x0e, 0x22, 0xff, 0x23, 0x0e, 0x13, 0xe2, 0x66, 0x54, 0x74, 0x06, 0xb5, 0x31, 0xe1, 0xa3,
	0x38, 0x60, 0x22, 0xa0, 0x91, 0x3a, 0xfd, 0xdd, 0x95, 0xc5, 0x02, 0xf4, 0x02, 0xaa, 0x21, 0xf5,
	0xa9, 0x97, 0xc4, 0xa1, 0x3c, 0xfd, 0x7d, 0xc5, 0x9b, 0x29, 0x7b, 0x18, 0x87, 0x69, 0x21, 0x1f,
	0x51, 0x46, 0xbc, 0x60, 0x2c, 0xdd, 0x7c, 0x6f, 0xa1, 0x64, 0xbf, 0x1b, 0x9b, 0x8f, 0xe1, 0x51,
	0x69, 0xfa, 0x6c, 0x87, 0xc7, 0x5f, 0xa0, 0x56, 0xb0, 0x19, 0x6a, 0x42, 0xc3, 0xee, 0x74, 0x7a,
	0x43, 0x67, 0xe0, 0x0d, 0x2e, 0xfb, 0x5d, 0x6f, 0xe8, 0x9c, 0x3b, 0xbd, 0x4f, 0x8e, 0xfe, 0xdf,
	0x02, 0xd2, 0xe9, 0x7d, 0xe8, 0xdb, 0xce, 0xa5, 0xae, 0x2d, 0x20, 0xfd, 0xae, 0x7b, 0xd1, 0x73,
	0x6c, 0x7d, 0xad, 0xfd, 0x63, 0x1d, 0xa0, 0x9f, 0xdd, 0xc4, 0x66, 0x0c, 0x9d, 0x43, 0x35, 0xb7,
	0x2d, 0x6a, 0x95, 0x8e, 0x55, 0xfa, 0x07, 0x18, 0x07, 0x2b, 0x71, 0x75, 0xfc, 0x37, 0x50, 0x91,
	0x0e, 0x44, 0x4f, 0x4a, 0xcc, 0xa2, 0xb3, 0x8d, 0xbd, 0xe5, 0xa0, 0xd2, 0xe8, 0xc2, 0x46, 0xe6,
	0x3b, 0xb4, 0x84, 0x37, 0xf3, 0xa7, 0xb1, 0xbf, 0x02, 0x55, 0x32, 0x6f, 0x61, 0x53, 0x59, 0x13,
	0xed, 0x2f, 0xb4, 0x5d, 0x34, 0xb1, 0xd1, 0x5a, 0x05, 0x2b, 0xa5, 0xcf, 0x50, 0x9f, 0x3b, 0x13,
	0x7a, 0x5a, 0x2a, 0x58, 0x66, 0x61, 0xe3, 0xd9, 0xdd, 0xa4, 0x4c, 0xfb, 0x6a, 0x43, 0x3a, 0xe4,
	0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0x50, 0xdc, 0x03, 0xd4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonaAppClient is the client API for PersonaApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*UpdateCompanyResponse, error)
}

type personaAppClient struct {
	cc *grpc.ClientConn
}

func NewPersonaAppClient(cc *grpc.ClientConn) PersonaAppClient {
	return &personaAppClient{cc}
}

func (c *personaAppClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.PersonaApp/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.PersonaApp/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.PersonaApp/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.PersonaApp/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppClient) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*UpdateCompanyResponse, error) {
	out := new(UpdateCompanyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.PersonaApp/UpdateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppServer is the server API for PersonaApp service.
type PersonaAppServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*UpdateCompanyResponse, error)
}

// UnimplementedPersonaAppServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppServer struct {
}

func (*UnimplementedPersonaAppServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedPersonaAppServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedPersonaAppServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedPersonaAppServer) Refresh(ctx context.Context, req *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (*UnimplementedPersonaAppServer) UpdateCompany(ctx context.Context, req *UpdateCompanyRequest) (*UpdateCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}

func RegisterPersonaAppServer(s *grpc.Server, srv PersonaAppServer) {
	s.RegisterService(&_PersonaApp_serviceDesc, srv)
}

func _PersonaApp_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.PersonaApp/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaApp_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.PersonaApp/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaApp_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.PersonaApp/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaApp_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.PersonaApp/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaApp_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.PersonaApp/UpdateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppServer).UpdateCompany(ctx, req.(*UpdateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.PersonaApp",
	HandlerType: (*PersonaAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PersonaApp_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PersonaApp_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PersonaApp_Logout_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _PersonaApp_Refresh_Handler,
		},
		{
			MethodName: "UpdateCompany",
			Handler:    _PersonaApp_UpdateCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "personaapp.proto",
}
