// Code generated by protoc-gen-go. DO NOT EDIT.
// source: company/company.proto

package company

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	entities "personaapp/pkg/grpcapi/entities"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateCompanyResponse_ErrorCode int32

const (
	UpdateCompanyResponse_UNKNOWN_ERROR_CODE         UpdateCompanyResponse_ErrorCode = 0
	UpdateCompanyResponse_INVALID_TITLE_FORMAT       UpdateCompanyResponse_ErrorCode = 3000
	UpdateCompanyResponse_INVALID_TITLE_LENGTH       UpdateCompanyResponse_ErrorCode = 3001
	UpdateCompanyResponse_INVALID_DESCRIPTION_FORMAT UpdateCompanyResponse_ErrorCode = 3100
	UpdateCompanyResponse_INVALID_DESCRIPTION_LENGTH UpdateCompanyResponse_ErrorCode = 3101
	UpdateCompanyResponse_INVALID_LOGO_URL_FORMAT    UpdateCompanyResponse_ErrorCode = 3200
	UpdateCompanyResponse_INVALID_LOGO_URL_LENGTH    UpdateCompanyResponse_ErrorCode = 3201
)

var UpdateCompanyResponse_ErrorCode_name = map[int32]string{
	0:    "UNKNOWN_ERROR_CODE",
	3000: "INVALID_TITLE_FORMAT",
	3001: "INVALID_TITLE_LENGTH",
	3100: "INVALID_DESCRIPTION_FORMAT",
	3101: "INVALID_DESCRIPTION_LENGTH",
	3200: "INVALID_LOGO_URL_FORMAT",
	3201: "INVALID_LOGO_URL_LENGTH",
}

var UpdateCompanyResponse_ErrorCode_value = map[string]int32{
	"UNKNOWN_ERROR_CODE":         0,
	"INVALID_TITLE_FORMAT":       3000,
	"INVALID_TITLE_LENGTH":       3001,
	"INVALID_DESCRIPTION_FORMAT": 3100,
	"INVALID_DESCRIPTION_LENGTH": 3101,
	"INVALID_LOGO_URL_FORMAT":    3200,
	"INVALID_LOGO_URL_LENGTH":    3201,
}

func (x UpdateCompanyResponse_ErrorCode) String() string {
	return proto.EnumName(UpdateCompanyResponse_ErrorCode_name, int32(x))
}

func (UpdateCompanyResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{1, 0}
}

// Update
type UpdateCompanyRequest struct {
	Title                *wrappers.StringValue `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              *wrappers.StringValue `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateCompanyRequest) Reset()         { *m = UpdateCompanyRequest{} }
func (m *UpdateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyRequest) ProtoMessage()    {}
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{0}
}

func (m *UpdateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyRequest.Merge(m, src)
}
func (m *UpdateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyRequest.Size(m)
}
func (m *UpdateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyRequest proto.InternalMessageInfo

func (m *UpdateCompanyRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *UpdateCompanyRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateCompanyRequest) GetLogoUrl() *wrappers.StringValue {
	if m != nil {
		return m.LogoUrl
	}
	return nil
}

type UpdateCompanyResponse struct {
	// Types that are valid to be assigned to Response:
	//	*UpdateCompanyResponse_ErrorCode_
	Response             isUpdateCompanyResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *UpdateCompanyResponse) Reset()         { *m = UpdateCompanyResponse{} }
func (m *UpdateCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyResponse) ProtoMessage()    {}
func (*UpdateCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{1}
}

func (m *UpdateCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyResponse.Unmarshal(m, b)
}
func (m *UpdateCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyResponse.Merge(m, src)
}
func (m *UpdateCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyResponse.Size(m)
}
func (m *UpdateCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyResponse proto.InternalMessageInfo

type isUpdateCompanyResponse_Response interface {
	isUpdateCompanyResponse_Response()
}

type UpdateCompanyResponse_ErrorCode_ struct {
	ErrorCode UpdateCompanyResponse_ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=personaappapi.company.UpdateCompanyResponse_ErrorCode,oneof"`
}

func (*UpdateCompanyResponse_ErrorCode_) isUpdateCompanyResponse_Response() {}

func (m *UpdateCompanyResponse) GetResponse() isUpdateCompanyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *UpdateCompanyResponse) GetErrorCode() UpdateCompanyResponse_ErrorCode {
	if x, ok := m.GetResponse().(*UpdateCompanyResponse_ErrorCode_); ok {
		return x.ErrorCode
	}
	return UpdateCompanyResponse_UNKNOWN_ERROR_CODE
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpdateCompanyResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateCompanyResponse_ErrorCode_)(nil),
	}
}

// Update Activity Fields
type UpdateCompanyActivityFieldsRequest struct {
	ActivityFields       map[string]*entities.Empty `protobuf:"bytes,1,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpdateCompanyActivityFieldsRequest) Reset()         { *m = UpdateCompanyActivityFieldsRequest{} }
func (m *UpdateCompanyActivityFieldsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyActivityFieldsRequest) ProtoMessage()    {}
func (*UpdateCompanyActivityFieldsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{2}
}

func (m *UpdateCompanyActivityFieldsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Merge(m, src)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Size(m)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyActivityFieldsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyActivityFieldsRequest proto.InternalMessageInfo

func (m *UpdateCompanyActivityFieldsRequest) GetActivityFields() map[string]*entities.Empty {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

type UpdateCompanyActivityFieldsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCompanyActivityFieldsResponse) Reset()         { *m = UpdateCompanyActivityFieldsResponse{} }
func (m *UpdateCompanyActivityFieldsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyActivityFieldsResponse) ProtoMessage()    {}
func (*UpdateCompanyActivityFieldsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{3}
}

func (m *UpdateCompanyActivityFieldsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Unmarshal(m, b)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Merge(m, src)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Size(m)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyActivityFieldsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyActivityFieldsResponse proto.InternalMessageInfo

// Get
type GetCompanyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyRequest) Reset()         { *m = GetCompanyRequest{} }
func (m *GetCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompanyRequest) ProtoMessage()    {}
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{4}
}

func (m *GetCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyRequest.Unmarshal(m, b)
}
func (m *GetCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyRequest.Marshal(b, m, deterministic)
}
func (m *GetCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyRequest.Merge(m, src)
}
func (m *GetCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompanyRequest.Size(m)
}
func (m *GetCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyRequest proto.InternalMessageInfo

func (m *GetCompanyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCompanyResponse struct {
	// Types that are valid to be assigned to Response:
	//	*GetCompanyResponse_Body_
	Response             isGetCompanyResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetCompanyResponse) Reset()         { *m = GetCompanyResponse{} }
func (m *GetCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse) ProtoMessage()    {}
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5}
}

func (m *GetCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse.Unmarshal(m, b)
}
func (m *GetCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse.Merge(m, src)
}
func (m *GetCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse.Size(m)
}
func (m *GetCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse proto.InternalMessageInfo

type isGetCompanyResponse_Response interface {
	isGetCompanyResponse_Response()
}

type GetCompanyResponse_Body_ struct {
	Body *GetCompanyResponse_Body `protobuf:"bytes,1,opt,name=body,proto3,oneof"`
}

func (*GetCompanyResponse_Body_) isGetCompanyResponse_Response() {}

func (m *GetCompanyResponse) GetResponse() isGetCompanyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetCompanyResponse) GetBody() *GetCompanyResponse_Body {
	if x, ok := m.GetResponse().(*GetCompanyResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCompanyResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCompanyResponse_Body_)(nil),
	}
}

type GetCompanyResponse_Company struct {
	Id                   string                                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                                              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                                              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              string                                              `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ActivityFields       map[string]*GetCompanyResponse_CompanyActivityField `protobuf:"bytes,5,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *GetCompanyResponse_Company) Reset()         { *m = GetCompanyResponse_Company{} }
func (m *GetCompanyResponse_Company) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse_Company) ProtoMessage()    {}
func (*GetCompanyResponse_Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5, 0}
}

func (m *GetCompanyResponse_Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse_Company.Unmarshal(m, b)
}
func (m *GetCompanyResponse_Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse_Company.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse_Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse_Company.Merge(m, src)
}
func (m *GetCompanyResponse_Company) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse_Company.Size(m)
}
func (m *GetCompanyResponse_Company) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse_Company.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse_Company proto.InternalMessageInfo

func (m *GetCompanyResponse_Company) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetActivityFields() map[string]*GetCompanyResponse_CompanyActivityField {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

type GetCompanyResponse_CompanyActivityField struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyResponse_CompanyActivityField) Reset() {
	*m = GetCompanyResponse_CompanyActivityField{}
}
func (m *GetCompanyResponse_CompanyActivityField) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse_CompanyActivityField) ProtoMessage()    {}
func (*GetCompanyResponse_CompanyActivityField) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5, 1}
}

func (m *GetCompanyResponse_CompanyActivityField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Unmarshal(m, b)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Merge(m, src)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Size(m)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse_CompanyActivityField.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse_CompanyActivityField proto.InternalMessageInfo

type GetCompanyResponse_Body struct {
	Company              *GetCompanyResponse_Company `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetCompanyResponse_Body) Reset()         { *m = GetCompanyResponse_Body{} }
func (m *GetCompanyResponse_Body) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse_Body) ProtoMessage()    {}
func (*GetCompanyResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5, 2}
}

func (m *GetCompanyResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse_Body.Unmarshal(m, b)
}
func (m *GetCompanyResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse_Body.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse_Body.Merge(m, src)
}
func (m *GetCompanyResponse_Body) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse_Body.Size(m)
}
func (m *GetCompanyResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse_Body proto.InternalMessageInfo

func (m *GetCompanyResponse_Body) GetCompany() *GetCompanyResponse_Company {
	if m != nil {
		return m.Company
	}
	return nil
}

// Get
type GetCompaniesActivityFieldsListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompaniesActivityFieldsListRequest) Reset()         { *m = GetCompaniesActivityFieldsListRequest{} }
func (m *GetCompaniesActivityFieldsListRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompaniesActivityFieldsListRequest) ProtoMessage()    {}
func (*GetCompaniesActivityFieldsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{6}
}

func (m *GetCompaniesActivityFieldsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompaniesActivityFieldsListRequest.Unmarshal(m, b)
}
func (m *GetCompaniesActivityFieldsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompaniesActivityFieldsListRequest.Marshal(b, m, deterministic)
}
func (m *GetCompaniesActivityFieldsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompaniesActivityFieldsListRequest.Merge(m, src)
}
func (m *GetCompaniesActivityFieldsListRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompaniesActivityFieldsListRequest.Size(m)
}
func (m *GetCompaniesActivityFieldsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompaniesActivityFieldsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompaniesActivityFieldsListRequest proto.InternalMessageInfo

type GetCompaniesActivityFieldsListResponse struct {
	// Types that are valid to be assigned to Response:
	//	*GetCompaniesActivityFieldsListResponse_Body_
	Response             isGetCompaniesActivityFieldsListResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *GetCompaniesActivityFieldsListResponse) Reset() {
	*m = GetCompaniesActivityFieldsListResponse{}
}
func (m *GetCompaniesActivityFieldsListResponse) String() string { return proto.CompactTextString(m) }
func (*GetCompaniesActivityFieldsListResponse) ProtoMessage()    {}
func (*GetCompaniesActivityFieldsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{7}
}

func (m *GetCompaniesActivityFieldsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse.Unmarshal(m, b)
}
func (m *GetCompaniesActivityFieldsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse.Marshal(b, m, deterministic)
}
func (m *GetCompaniesActivityFieldsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompaniesActivityFieldsListResponse.Merge(m, src)
}
func (m *GetCompaniesActivityFieldsListResponse) XXX_Size() int {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse.Size(m)
}
func (m *GetCompaniesActivityFieldsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompaniesActivityFieldsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompaniesActivityFieldsListResponse proto.InternalMessageInfo

type isGetCompaniesActivityFieldsListResponse_Response interface {
	isGetCompaniesActivityFieldsListResponse_Response()
}

type GetCompaniesActivityFieldsListResponse_Body_ struct {
	Body *GetCompaniesActivityFieldsListResponse_Body `protobuf:"bytes,1,opt,name=body,proto3,oneof"`
}

func (*GetCompaniesActivityFieldsListResponse_Body_) isGetCompaniesActivityFieldsListResponse_Response() {
}

func (m *GetCompaniesActivityFieldsListResponse) GetResponse() isGetCompaniesActivityFieldsListResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetCompaniesActivityFieldsListResponse) GetBody() *GetCompaniesActivityFieldsListResponse_Body {
	if x, ok := m.GetResponse().(*GetCompaniesActivityFieldsListResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCompaniesActivityFieldsListResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCompaniesActivityFieldsListResponse_Body_)(nil),
	}
}

type GetCompaniesActivityFieldsListResponse_CompanyActivityField struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Alias                string   `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) Reset() {
	*m = GetCompaniesActivityFieldsListResponse_CompanyActivityField{}
}
func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) String() string {
	return proto.CompactTextString(m)
}
func (*GetCompaniesActivityFieldsListResponse_CompanyActivityField) ProtoMessage() {}
func (*GetCompaniesActivityFieldsListResponse_CompanyActivityField) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{7, 0}
}

func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse_CompanyActivityField.Unmarshal(m, b)
}
func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse_CompanyActivityField.Marshal(b, m, deterministic)
}
func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompaniesActivityFieldsListResponse_CompanyActivityField.Merge(m, src)
}
func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) XXX_Size() int {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse_CompanyActivityField.Size(m)
}
func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompaniesActivityFieldsListResponse_CompanyActivityField.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompaniesActivityFieldsListResponse_CompanyActivityField proto.InternalMessageInfo

func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetCompaniesActivityFieldsListResponse_CompanyActivityField) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type GetCompaniesActivityFieldsListResponse_Body struct {
	ActivityFields       map[string]*GetCompaniesActivityFieldsListResponse_CompanyActivityField `protobuf:"bytes,1,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                                                `json:"-"`
	XXX_unrecognized     []byte                                                                  `json:"-"`
	XXX_sizecache        int32                                                                   `json:"-"`
}

func (m *GetCompaniesActivityFieldsListResponse_Body) Reset() {
	*m = GetCompaniesActivityFieldsListResponse_Body{}
}
func (m *GetCompaniesActivityFieldsListResponse_Body) String() string {
	return proto.CompactTextString(m)
}
func (*GetCompaniesActivityFieldsListResponse_Body) ProtoMessage() {}
func (*GetCompaniesActivityFieldsListResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{7, 1}
}

func (m *GetCompaniesActivityFieldsListResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse_Body.Unmarshal(m, b)
}
func (m *GetCompaniesActivityFieldsListResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse_Body.Marshal(b, m, deterministic)
}
func (m *GetCompaniesActivityFieldsListResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompaniesActivityFieldsListResponse_Body.Merge(m, src)
}
func (m *GetCompaniesActivityFieldsListResponse_Body) XXX_Size() int {
	return xxx_messageInfo_GetCompaniesActivityFieldsListResponse_Body.Size(m)
}
func (m *GetCompaniesActivityFieldsListResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompaniesActivityFieldsListResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompaniesActivityFieldsListResponse_Body proto.InternalMessageInfo

func (m *GetCompaniesActivityFieldsListResponse_Body) GetActivityFields() map[string]*GetCompaniesActivityFieldsListResponse_CompanyActivityField {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

func init() {
	proto.RegisterEnum("personaappapi.company.UpdateCompanyResponse_ErrorCode", UpdateCompanyResponse_ErrorCode_name, UpdateCompanyResponse_ErrorCode_value)
	proto.RegisterType((*UpdateCompanyRequest)(nil), "personaappapi.company.UpdateCompanyRequest")
	proto.RegisterType((*UpdateCompanyResponse)(nil), "personaappapi.company.UpdateCompanyResponse")
	proto.RegisterType((*UpdateCompanyActivityFieldsRequest)(nil), "personaappapi.company.UpdateCompanyActivityFieldsRequest")
	proto.RegisterMapType((map[string]*entities.Empty)(nil), "personaappapi.company.UpdateCompanyActivityFieldsRequest.ActivityFieldsEntry")
	proto.RegisterType((*UpdateCompanyActivityFieldsResponse)(nil), "personaappapi.company.UpdateCompanyActivityFieldsResponse")
	proto.RegisterType((*GetCompanyRequest)(nil), "personaappapi.company.GetCompanyRequest")
	proto.RegisterType((*GetCompanyResponse)(nil), "personaappapi.company.GetCompanyResponse")
	proto.RegisterType((*GetCompanyResponse_Company)(nil), "personaappapi.company.GetCompanyResponse.Company")
	proto.RegisterMapType((map[string]*GetCompanyResponse_CompanyActivityField)(nil), "personaappapi.company.GetCompanyResponse.Company.ActivityFieldsEntry")
	proto.RegisterType((*GetCompanyResponse_CompanyActivityField)(nil), "personaappapi.company.GetCompanyResponse.CompanyActivityField")
	proto.RegisterType((*GetCompanyResponse_Body)(nil), "personaappapi.company.GetCompanyResponse.Body")
	proto.RegisterType((*GetCompaniesActivityFieldsListRequest)(nil), "personaappapi.company.GetCompaniesActivityFieldsListRequest")
	proto.RegisterType((*GetCompaniesActivityFieldsListResponse)(nil), "personaappapi.company.GetCompaniesActivityFieldsListResponse")
	proto.RegisterType((*GetCompaniesActivityFieldsListResponse_CompanyActivityField)(nil), "personaappapi.company.GetCompaniesActivityFieldsListResponse.CompanyActivityField")
	proto.RegisterType((*GetCompaniesActivityFieldsListResponse_Body)(nil), "personaappapi.company.GetCompaniesActivityFieldsListResponse.Body")
	proto.RegisterMapType((map[string]*GetCompaniesActivityFieldsListResponse_CompanyActivityField)(nil), "personaappapi.company.GetCompaniesActivityFieldsListResponse.Body.ActivityFieldsEntry")
}

func init() { proto.RegisterFile("company/company.proto", fileDescriptor_13f68715d26ff6fb) }

var fileDescriptor_13f68715d26ff6fb = []byte{
	// 839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x4f, 0xfb, 0x54,
	0x18, 0xa6, 0xdd, 0x26, 0x3f, 0xde, 0x45, 0xdc, 0xef, 0x38, 0xd8, 0x56, 0x11, 0x49, 0x09, 0x8a,
	0xd1, 0x74, 0x71, 0x24, 0xfe, 0x21, 0x4a, 0xb2, 0x3f, 0x65, 0x2c, 0x8c, 0x8d, 0x94, 0x0d, 0x8c,
	0x37, 0xb5, 0xac, 0x87, 0x79, 0xa4, 0xf4, 0x1c, 0xdb, 0x0e, 0xb3, 0x2b, 0xe5, 0x3b, 0xe8, 0x85,
	0x89, 0xc4, 0x6f, 0x61, 0xf4, 0xda, 0xef, 0xa0, 0xb7, 0x7e, 0x08, 0xaf, 0xcd, 0x2f, 0x6b, 0x4f,
	0x61, 0x1d, 0x63, 0x14, 0xb8, 0xda, 0x4e, 0xdf, 0xf7, 0x79, 0xce, 0x7b, 0xde, 0xf7, 0x79, 0x4e,
	0x0b, 0x4b, 0x3d, 0x7a, 0xc1, 0x0c, 0x7b, 0x58, 0xe4, 0xbf, 0x0a, 0x73, 0xa8, 0x47, 0xd1, 0x12,
	0xc3, 0x8e, 0x4b, 0x6d, 0xc3, 0x60, 0xcc, 0x60, 0x44, 0xe1, 0x41, 0x29, 0x87, 0x6d, 0x8f, 0x78,
	0x04, 0xbb, 0xc5, 0xf0, 0x4f, 0x90, 0x2f, 0xad, 0xf6, 0x29, 0xed, 0x5b, 0xb8, 0xe8, 0xaf, 0x4e,
	0x07, 0x67, 0xc5, 0xef, 0x1d, 0x83, 0x8d, 0x38, 0x82, 0xb8, 0xfc, 0x97, 0x00, 0xd9, 0x2e, 0x33,
	0x0d, 0x0f, 0x57, 0x03, 0x2a, 0x0d, 0x7f, 0x37, 0xc0, 0xae, 0x87, 0x4a, 0x90, 0xf2, 0x88, 0x67,
	0xe1, 0xbc, 0xb0, 0x26, 0x6c, 0xa6, 0x4b, 0x2b, 0x4a, 0x40, 0xa4, 0x84, 0x44, 0xca, 0x91, 0xe7,
	0x10, 0xbb, 0x7f, 0x6c, 0x58, 0x03, 0xac, 0x05, 0xa9, 0x68, 0x07, 0xd2, 0x26, 0x76, 0x7b, 0x0e,
	0x61, 0x1e, 0xa1, 0x76, 0x5e, 0x8c, 0x81, 0x1c, 0x07, 0xa0, 0x4f, 0xe0, 0x85, 0x45, 0xfb, 0x54,
	0x1f, 0x38, 0x56, 0x3e, 0x11, 0x03, 0x3c, 0x3f, 0xca, 0xee, 0x3a, 0x96, 0xfc, 0xb7, 0x08, 0x4b,
	0x13, 0xa7, 0x70, 0x19, 0xb5, 0x5d, 0x8c, 0x4e, 0x00, 0xb0, 0xe3, 0x50, 0x47, 0xef, 0x51, 0x33,
	0x38, 0xcb, 0x62, 0xe9, 0x63, 0x65, 0x6a, 0x13, 0x95, 0xa9, 0x0c, 0x8a, 0x3a, 0x82, 0x57, 0xa9,
	0x89, 0xf7, 0xe6, 0xb4, 0x05, 0x1c, 0x2e, 0xe4, 0x7f, 0x04, 0x58, 0xb8, 0x09, 0xa1, 0x65, 0x40,
	0xdd, 0xd6, 0x7e, 0xab, 0x7d, 0xd2, 0xd2, 0x55, 0x4d, 0x6b, 0x6b, 0x7a, 0xb5, 0x5d, 0x53, 0x33,
	0x73, 0xa8, 0x00, 0xd9, 0x46, 0xeb, 0xb8, 0xdc, 0x6c, 0xd4, 0xf4, 0x4e, 0xa3, 0xd3, 0x54, 0xf5,
	0xdd, 0xb6, 0x76, 0x50, 0xee, 0x64, 0xfe, 0xc8, 0xdd, 0x0d, 0x35, 0xd5, 0x56, 0xbd, 0xb3, 0x97,
	0xf9, 0x33, 0x87, 0xde, 0x01, 0x29, 0x0c, 0xd5, 0xd4, 0xa3, 0xaa, 0xd6, 0x38, 0xec, 0x34, 0xda,
	0xad, 0x10, 0xfb, 0x6b, 0xfe, 0xbe, 0x04, 0xce, 0x70, 0x9d, 0x47, 0x2b, 0x90, 0x0b, 0x13, 0x9a,
	0xed, 0x7a, 0x5b, 0xef, 0x6a, 0xcd, 0x10, 0xfe, 0x63, 0x61, 0x6a, 0x94, 0x63, 0xaf, 0x0a, 0x15,
	0x80, 0x17, 0x0e, 0x3f, 0xbc, 0xfc, 0xbf, 0x00, 0x72, 0xa4, 0x2d, 0xe5, 0x9e, 0x47, 0x2e, 0x89,
	0x37, 0xdc, 0x25, 0xd8, 0x32, 0xdd, 0x50, 0x2c, 0x97, 0xf0, 0x86, 0xc1, 0x03, 0xfa, 0x99, 0x1f,
	0xc9, 0x0b, 0x6b, 0x89, 0xcd, 0x74, 0xe9, 0x20, 0x4e, 0xab, 0xa7, 0x72, 0x2a, 0xd1, 0xa7, 0xaa,
	0xed, 0x39, 0x43, 0x6d, 0xd1, 0x88, 0x3c, 0x94, 0xbe, 0x86, 0x37, 0xa7, 0xa4, 0xa1, 0x0c, 0x24,
	0xce, 0xf1, 0xd0, 0x9f, 0xf6, 0x82, 0x36, 0xfa, 0x8b, 0xb6, 0x20, 0x75, 0x39, 0x92, 0x0c, 0xd7,
	0xe4, 0xdb, 0x13, 0x65, 0xdd, 0x98, 0x46, 0xbd, 0x60, 0xde, 0x50, 0x0b, 0x72, 0xb7, 0xc5, 0x4f,
	0x05, 0x79, 0x03, 0xd6, 0x67, 0xd6, 0xca, 0xfb, 0xb4, 0x0e, 0x2f, 0xeb, 0xd8, 0x9b, 0xb0, 0xd0,
	0x22, 0x88, 0xc4, 0xe4, 0x55, 0x88, 0xc4, 0x94, 0x7f, 0x4f, 0x02, 0x1a, 0xcf, 0xe2, 0x12, 0xad,
	0x41, 0xf2, 0x94, 0x9a, 0x43, 0x6e, 0x34, 0xe5, 0x9e, 0x8e, 0xdd, 0x05, 0x2a, 0x15, 0x6a, 0x0e,
	0xf7, 0xe6, 0x34, 0x1f, 0x2d, 0xfd, 0x2b, 0xc2, 0x3c, 0x4f, 0x98, 0xdc, 0x18, 0x65, 0x43, 0x2f,
	0x8b, 0xfe, 0x23, 0xee, 0xd6, 0xb5, 0xa8, 0x5b, 0x13, 0x7e, 0x2c, 0xe2, 0xc7, 0xc2, 0x98, 0x1f,
	0x93, 0x7e, 0x38, 0x74, 0x1c, 0xb2, 0xef, 0x4e, 0x3c, 0xe5, 0x4f, 0x5c, 0x8d, 0x5f, 0x3f, 0x5f,
	0xc7, 0x9a, 0xf4, 0x95, 0x10, 0x77, 0xd4, 0x9d, 0xe8, 0xa8, 0x77, 0x1e, 0x5d, 0x4f, 0x64, 0x9b,
	0x31, 0x2d, 0x48, 0xcb, 0x90, 0x9d, 0x96, 0x22, 0x1d, 0x41, 0x72, 0x34, 0x0a, 0xb4, 0x0f, 0xf3,
	0x9c, 0x9d, 0xcf, 0xf2, 0xa3, 0x47, 0xef, 0xad, 0x85, 0x0c, 0x11, 0x17, 0xbe, 0x07, 0x1b, 0x37,
	0x10, 0x82, 0xdd, 0x68, 0x1f, 0x9a, 0xc4, 0xf5, 0xb8, 0xe2, 0xe4, 0xff, 0x12, 0xf0, 0xee, 0x43,
	0x99, 0x5c, 0x75, 0x5f, 0x46, 0x54, 0x57, 0x79, 0xa8, 0xd2, 0x99, 0x64, 0x51, 0x25, 0x56, 0xa6,
	0xb7, 0xe9, 0x56, 0x85, 0xc2, 0xb8, 0x0a, 0xb3, 0x90, 0x32, 0x2c, 0x62, 0xb8, 0xa1, 0x36, 0xfd,
	0x85, 0xf4, 0x9b, 0xc8, 0x7b, 0xfa, 0xc3, 0x7d, 0x37, 0xcb, 0xf1, 0xf3, 0x2b, 0x8e, 0x25, 0xbc,
	0x9f, 0x63, 0x0b, 0xef, 0x9b, 0xa8, 0xf0, 0xb4, 0xe7, 0x15, 0xf8, 0x80, 0x18, 0xc7, 0xf5, 0x51,
	0xfa, 0x25, 0x09, 0x2f, 0x0f, 0x83, 0xcd, 0xca, 0x8c, 0x85, 0xb7, 0xc0, 0xb7, 0xf0, 0x7a, 0xe4,
	0xea, 0x42, 0x1f, 0xc4, 0x7b, 0xef, 0xf9, 0x52, 0x92, 0x3e, 0x7c, 0xcc, 0x4b, 0x12, 0xfd, 0x24,
	0xc0, 0x5b, 0x33, 0xee, 0x49, 0xf4, 0xd9, 0x93, 0xdf, 0x03, 0xd2, 0xf6, 0x53, 0xa0, 0xbc, 0x2c,
	0x03, 0xe0, 0xd6, 0x6b, 0x68, 0x33, 0x86, 0x1d, 0x83, 0x3d, 0xdf, 0x8f, 0x6d, 0x5c, 0x74, 0x2d,
	0xc0, 0xea, 0xec, 0x91, 0xa2, 0xcf, 0x9f, 0xa8, 0x84, 0xa0, 0x96, 0x2f, 0x9e, 0xa5, 0xa3, 0x8a,
	0x0a, 0xcb, 0xd4, 0xb6, 0x88, 0x8d, 0xc7, 0x68, 0x94, 0x1e, 0x75, 0x70, 0x25, 0x5d, 0x77, 0x58,
	0x8f, 0x1f, 0xe7, 0xab, 0xd5, 0xdb, 0x68, 0x91, 0x9d, 0xf7, 0x8b, 0x7d, 0x87, 0xf5, 0x0c, 0x46,
	0xc2, 0xaf, 0xcf, 0xd3, 0xd7, 0xfc, 0x0f, 0xb0, 0xad, 0x57, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd,
	0x0c, 0xee, 0xef, 0x97, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonaAppCompanyClient is the client API for PersonaAppCompany service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppCompanyClient interface {
	UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*UpdateCompanyResponse, error)
	UpdateCompanyActivityFields(ctx context.Context, in *UpdateCompanyActivityFieldsRequest, opts ...grpc.CallOption) (*UpdateCompanyActivityFieldsResponse, error)
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*GetCompanyResponse, error)
	GetCompaniesActivityFieldsList(ctx context.Context, in *GetCompaniesActivityFieldsListRequest, opts ...grpc.CallOption) (*GetCompaniesActivityFieldsListResponse, error)
}

type personaAppCompanyClient struct {
	cc *grpc.ClientConn
}

func NewPersonaAppCompanyClient(cc *grpc.ClientConn) PersonaAppCompanyClient {
	return &personaAppCompanyClient{cc}
}

func (c *personaAppCompanyClient) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*UpdateCompanyResponse, error) {
	out := new(UpdateCompanyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/UpdateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCompanyClient) UpdateCompanyActivityFields(ctx context.Context, in *UpdateCompanyActivityFieldsRequest, opts ...grpc.CallOption) (*UpdateCompanyActivityFieldsResponse, error) {
	out := new(UpdateCompanyActivityFieldsResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/UpdateCompanyActivityFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCompanyClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*GetCompanyResponse, error) {
	out := new(GetCompanyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/GetCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCompanyClient) GetCompaniesActivityFieldsList(ctx context.Context, in *GetCompaniesActivityFieldsListRequest, opts ...grpc.CallOption) (*GetCompaniesActivityFieldsListResponse, error) {
	out := new(GetCompaniesActivityFieldsListResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/GetCompaniesActivityFieldsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppCompanyServer is the server API for PersonaAppCompany service.
type PersonaAppCompanyServer interface {
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*UpdateCompanyResponse, error)
	UpdateCompanyActivityFields(context.Context, *UpdateCompanyActivityFieldsRequest) (*UpdateCompanyActivityFieldsResponse, error)
	GetCompany(context.Context, *GetCompanyRequest) (*GetCompanyResponse, error)
	GetCompaniesActivityFieldsList(context.Context, *GetCompaniesActivityFieldsListRequest) (*GetCompaniesActivityFieldsListResponse, error)
}

// UnimplementedPersonaAppCompanyServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppCompanyServer struct {
}

func (*UnimplementedPersonaAppCompanyServer) UpdateCompany(ctx context.Context, req *UpdateCompanyRequest) (*UpdateCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}
func (*UnimplementedPersonaAppCompanyServer) UpdateCompanyActivityFields(ctx context.Context, req *UpdateCompanyActivityFieldsRequest) (*UpdateCompanyActivityFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompanyActivityFields not implemented")
}
func (*UnimplementedPersonaAppCompanyServer) GetCompany(ctx context.Context, req *GetCompanyRequest) (*GetCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}
func (*UnimplementedPersonaAppCompanyServer) GetCompaniesActivityFieldsList(ctx context.Context, req *GetCompaniesActivityFieldsListRequest) (*GetCompaniesActivityFieldsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompaniesActivityFieldsList not implemented")
}

func RegisterPersonaAppCompanyServer(s *grpc.Server, srv PersonaAppCompanyServer) {
	s.RegisterService(&_PersonaAppCompany_serviceDesc, srv)
}

func _PersonaAppCompany_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/UpdateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).UpdateCompany(ctx, req.(*UpdateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCompany_UpdateCompanyActivityFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyActivityFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).UpdateCompanyActivityFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/UpdateCompanyActivityFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).UpdateCompanyActivityFields(ctx, req.(*UpdateCompanyActivityFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCompany_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/GetCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCompany_GetCompaniesActivityFieldsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompaniesActivityFieldsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).GetCompaniesActivityFieldsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/GetCompaniesActivityFieldsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).GetCompaniesActivityFieldsList(ctx, req.(*GetCompaniesActivityFieldsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaAppCompany_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.company.PersonaAppCompany",
	HandlerType: (*PersonaAppCompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCompany",
			Handler:    _PersonaAppCompany_UpdateCompany_Handler,
		},
		{
			MethodName: "UpdateCompanyActivityFields",
			Handler:    _PersonaAppCompany_UpdateCompanyActivityFields_Handler,
		},
		{
			MethodName: "GetCompany",
			Handler:    _PersonaAppCompany_GetCompany_Handler,
		},
		{
			MethodName: "GetCompaniesActivityFieldsList",
			Handler:    _PersonaAppCompany_GetCompaniesActivityFieldsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "company/company.proto",
}
