// Code generated by protoc-gen-go. DO NOT EDIT.
// source: company/company.proto

package company

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	entities "personaapp/pkg/grpcapi/entities"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Common
type ErrorCode int32

const (
	ErrorCode_UNKNOWN_ERROR_CODE         ErrorCode = 0
	ErrorCode_INVALID_TITLE_FORMAT       ErrorCode = 3000
	ErrorCode_INVALID_TITLE_LENGTH       ErrorCode = 3001
	ErrorCode_INVALID_DESCRIPTION_FORMAT ErrorCode = 3100
	ErrorCode_INVALID_DESCRIPTION_LENGTH ErrorCode = 3101
	ErrorCode_INVALID_LOGO_URL_FORMAT    ErrorCode = 3200
	ErrorCode_INVALID_LOGO_URL_LENGTH    ErrorCode = 3201
)

var ErrorCode_name = map[int32]string{
	0:    "UNKNOWN_ERROR_CODE",
	3000: "INVALID_TITLE_FORMAT",
	3001: "INVALID_TITLE_LENGTH",
	3100: "INVALID_DESCRIPTION_FORMAT",
	3101: "INVALID_DESCRIPTION_LENGTH",
	3200: "INVALID_LOGO_URL_FORMAT",
	3201: "INVALID_LOGO_URL_LENGTH",
}

var ErrorCode_value = map[string]int32{
	"UNKNOWN_ERROR_CODE":         0,
	"INVALID_TITLE_FORMAT":       3000,
	"INVALID_TITLE_LENGTH":       3001,
	"INVALID_DESCRIPTION_FORMAT": 3100,
	"INVALID_DESCRIPTION_LENGTH": 3101,
	"INVALID_LOGO_URL_FORMAT":    3200,
	"INVALID_LOGO_URL_LENGTH":    3201,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{0}
}

// Update
type UpdateCompanyRequest struct {
	Title                *wrappers.StringValue `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              *wrappers.StringValue `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateCompanyRequest) Reset()         { *m = UpdateCompanyRequest{} }
func (m *UpdateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyRequest) ProtoMessage()    {}
func (*UpdateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{0}
}

func (m *UpdateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyRequest.Merge(m, src)
}
func (m *UpdateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyRequest.Size(m)
}
func (m *UpdateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyRequest proto.InternalMessageInfo

func (m *UpdateCompanyRequest) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *UpdateCompanyRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateCompanyRequest) GetLogoUrl() *wrappers.StringValue {
	if m != nil {
		return m.LogoUrl
	}
	return nil
}

type UpdateCompanyResponse struct {
	// Types that are valid to be assigned to Response:
	//	*UpdateCompanyResponse_ErrorCode
	//	*UpdateCompanyResponse_Body_
	Response             isUpdateCompanyResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *UpdateCompanyResponse) Reset()         { *m = UpdateCompanyResponse{} }
func (m *UpdateCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyResponse) ProtoMessage()    {}
func (*UpdateCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{1}
}

func (m *UpdateCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyResponse.Unmarshal(m, b)
}
func (m *UpdateCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyResponse.Merge(m, src)
}
func (m *UpdateCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyResponse.Size(m)
}
func (m *UpdateCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyResponse proto.InternalMessageInfo

type isUpdateCompanyResponse_Response interface {
	isUpdateCompanyResponse_Response()
}

type UpdateCompanyResponse_ErrorCode struct {
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=personaappapi.company.ErrorCode,oneof"`
}

type UpdateCompanyResponse_Body_ struct {
	Body *UpdateCompanyResponse_Body `protobuf:"bytes,2,opt,name=body,proto3,oneof"`
}

func (*UpdateCompanyResponse_ErrorCode) isUpdateCompanyResponse_Response() {}

func (*UpdateCompanyResponse_Body_) isUpdateCompanyResponse_Response() {}

func (m *UpdateCompanyResponse) GetResponse() isUpdateCompanyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *UpdateCompanyResponse) GetErrorCode() ErrorCode {
	if x, ok := m.GetResponse().(*UpdateCompanyResponse_ErrorCode); ok {
		return x.ErrorCode
	}
	return ErrorCode_UNKNOWN_ERROR_CODE
}

func (m *UpdateCompanyResponse) GetBody() *UpdateCompanyResponse_Body {
	if x, ok := m.GetResponse().(*UpdateCompanyResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpdateCompanyResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateCompanyResponse_ErrorCode)(nil),
		(*UpdateCompanyResponse_Body_)(nil),
	}
}

type UpdateCompanyResponse_Body struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCompanyResponse_Body) Reset()         { *m = UpdateCompanyResponse_Body{} }
func (m *UpdateCompanyResponse_Body) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyResponse_Body) ProtoMessage()    {}
func (*UpdateCompanyResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{1, 0}
}

func (m *UpdateCompanyResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyResponse_Body.Unmarshal(m, b)
}
func (m *UpdateCompanyResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyResponse_Body.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyResponse_Body.Merge(m, src)
}
func (m *UpdateCompanyResponse_Body) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyResponse_Body.Size(m)
}
func (m *UpdateCompanyResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyResponse_Body proto.InternalMessageInfo

// Update Activity Fields
type UpdateCompanyActivityFieldsRequest struct {
	ActivityFields       map[string]*entities.Empty `protobuf:"bytes,1,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpdateCompanyActivityFieldsRequest) Reset()         { *m = UpdateCompanyActivityFieldsRequest{} }
func (m *UpdateCompanyActivityFieldsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyActivityFieldsRequest) ProtoMessage()    {}
func (*UpdateCompanyActivityFieldsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{2}
}

func (m *UpdateCompanyActivityFieldsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Merge(m, src)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyActivityFieldsRequest.Size(m)
}
func (m *UpdateCompanyActivityFieldsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyActivityFieldsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyActivityFieldsRequest proto.InternalMessageInfo

func (m *UpdateCompanyActivityFieldsRequest) GetActivityFields() map[string]*entities.Empty {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

type UpdateCompanyActivityFieldsResponse struct {
	// Types that are valid to be assigned to Response:
	//	*UpdateCompanyActivityFieldsResponse_ErrorCode
	//	*UpdateCompanyActivityFieldsResponse_Body_
	Response             isUpdateCompanyActivityFieldsResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *UpdateCompanyActivityFieldsResponse) Reset()         { *m = UpdateCompanyActivityFieldsResponse{} }
func (m *UpdateCompanyActivityFieldsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyActivityFieldsResponse) ProtoMessage()    {}
func (*UpdateCompanyActivityFieldsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{3}
}

func (m *UpdateCompanyActivityFieldsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Unmarshal(m, b)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Merge(m, src)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse.Size(m)
}
func (m *UpdateCompanyActivityFieldsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyActivityFieldsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyActivityFieldsResponse proto.InternalMessageInfo

type isUpdateCompanyActivityFieldsResponse_Response interface {
	isUpdateCompanyActivityFieldsResponse_Response()
}

type UpdateCompanyActivityFieldsResponse_ErrorCode struct {
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=personaappapi.company.ErrorCode,oneof"`
}

type UpdateCompanyActivityFieldsResponse_Body_ struct {
	Body *UpdateCompanyActivityFieldsResponse_Body `protobuf:"bytes,2,opt,name=body,proto3,oneof"`
}

func (*UpdateCompanyActivityFieldsResponse_ErrorCode) isUpdateCompanyActivityFieldsResponse_Response() {
}

func (*UpdateCompanyActivityFieldsResponse_Body_) isUpdateCompanyActivityFieldsResponse_Response() {}

func (m *UpdateCompanyActivityFieldsResponse) GetResponse() isUpdateCompanyActivityFieldsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *UpdateCompanyActivityFieldsResponse) GetErrorCode() ErrorCode {
	if x, ok := m.GetResponse().(*UpdateCompanyActivityFieldsResponse_ErrorCode); ok {
		return x.ErrorCode
	}
	return ErrorCode_UNKNOWN_ERROR_CODE
}

func (m *UpdateCompanyActivityFieldsResponse) GetBody() *UpdateCompanyActivityFieldsResponse_Body {
	if x, ok := m.GetResponse().(*UpdateCompanyActivityFieldsResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpdateCompanyActivityFieldsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateCompanyActivityFieldsResponse_ErrorCode)(nil),
		(*UpdateCompanyActivityFieldsResponse_Body_)(nil),
	}
}

type UpdateCompanyActivityFieldsResponse_Body struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCompanyActivityFieldsResponse_Body) Reset() {
	*m = UpdateCompanyActivityFieldsResponse_Body{}
}
func (m *UpdateCompanyActivityFieldsResponse_Body) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyActivityFieldsResponse_Body) ProtoMessage()    {}
func (*UpdateCompanyActivityFieldsResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{3, 0}
}

func (m *UpdateCompanyActivityFieldsResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse_Body.Unmarshal(m, b)
}
func (m *UpdateCompanyActivityFieldsResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse_Body.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyActivityFieldsResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyActivityFieldsResponse_Body.Merge(m, src)
}
func (m *UpdateCompanyActivityFieldsResponse_Body) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyActivityFieldsResponse_Body.Size(m)
}
func (m *UpdateCompanyActivityFieldsResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyActivityFieldsResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyActivityFieldsResponse_Body proto.InternalMessageInfo

// Get
type GetCompanyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyRequest) Reset()         { *m = GetCompanyRequest{} }
func (m *GetCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*GetCompanyRequest) ProtoMessage()    {}
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{4}
}

func (m *GetCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyRequest.Unmarshal(m, b)
}
func (m *GetCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyRequest.Marshal(b, m, deterministic)
}
func (m *GetCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyRequest.Merge(m, src)
}
func (m *GetCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_GetCompanyRequest.Size(m)
}
func (m *GetCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyRequest proto.InternalMessageInfo

func (m *GetCompanyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCompanyResponse struct {
	// Types that are valid to be assigned to Response:
	//	*GetCompanyResponse_ErrorCode
	//	*GetCompanyResponse_Body_
	Response             isGetCompanyResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetCompanyResponse) Reset()         { *m = GetCompanyResponse{} }
func (m *GetCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse) ProtoMessage()    {}
func (*GetCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5}
}

func (m *GetCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse.Unmarshal(m, b)
}
func (m *GetCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse.Merge(m, src)
}
func (m *GetCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse.Size(m)
}
func (m *GetCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse proto.InternalMessageInfo

type isGetCompanyResponse_Response interface {
	isGetCompanyResponse_Response()
}

type GetCompanyResponse_ErrorCode struct {
	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=personaappapi.company.ErrorCode,oneof"`
}

type GetCompanyResponse_Body_ struct {
	Body *GetCompanyResponse_Body `protobuf:"bytes,2,opt,name=body,proto3,oneof"`
}

func (*GetCompanyResponse_ErrorCode) isGetCompanyResponse_Response() {}

func (*GetCompanyResponse_Body_) isGetCompanyResponse_Response() {}

func (m *GetCompanyResponse) GetResponse() isGetCompanyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetCompanyResponse) GetErrorCode() ErrorCode {
	if x, ok := m.GetResponse().(*GetCompanyResponse_ErrorCode); ok {
		return x.ErrorCode
	}
	return ErrorCode_UNKNOWN_ERROR_CODE
}

func (m *GetCompanyResponse) GetBody() *GetCompanyResponse_Body {
	if x, ok := m.GetResponse().(*GetCompanyResponse_Body_); ok {
		return x.Body
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetCompanyResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetCompanyResponse_ErrorCode)(nil),
		(*GetCompanyResponse_Body_)(nil),
	}
}

type GetCompanyResponse_Company struct {
	Id                   string                                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                                              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                                              `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl              string                                              `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ActivityFields       map[string]*GetCompanyResponse_CompanyActivityField `protobuf:"bytes,5,rep,name=activity_fields,json=activityFields,proto3" json:"activity_fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *GetCompanyResponse_Company) Reset()         { *m = GetCompanyResponse_Company{} }
func (m *GetCompanyResponse_Company) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse_Company) ProtoMessage()    {}
func (*GetCompanyResponse_Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5, 0}
}

func (m *GetCompanyResponse_Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse_Company.Unmarshal(m, b)
}
func (m *GetCompanyResponse_Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse_Company.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse_Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse_Company.Merge(m, src)
}
func (m *GetCompanyResponse_Company) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse_Company.Size(m)
}
func (m *GetCompanyResponse_Company) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse_Company.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse_Company proto.InternalMessageInfo

func (m *GetCompanyResponse_Company) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *GetCompanyResponse_Company) GetActivityFields() map[string]*GetCompanyResponse_CompanyActivityField {
	if m != nil {
		return m.ActivityFields
	}
	return nil
}

type GetCompanyResponse_CompanyActivityField struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCompanyResponse_CompanyActivityField) Reset() {
	*m = GetCompanyResponse_CompanyActivityField{}
}
func (m *GetCompanyResponse_CompanyActivityField) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse_CompanyActivityField) ProtoMessage()    {}
func (*GetCompanyResponse_CompanyActivityField) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5, 1}
}

func (m *GetCompanyResponse_CompanyActivityField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Unmarshal(m, b)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Merge(m, src)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse_CompanyActivityField.Size(m)
}
func (m *GetCompanyResponse_CompanyActivityField) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse_CompanyActivityField.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse_CompanyActivityField proto.InternalMessageInfo

type GetCompanyResponse_Body struct {
	Company              *GetCompanyResponse_Company `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetCompanyResponse_Body) Reset()         { *m = GetCompanyResponse_Body{} }
func (m *GetCompanyResponse_Body) String() string { return proto.CompactTextString(m) }
func (*GetCompanyResponse_Body) ProtoMessage()    {}
func (*GetCompanyResponse_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_13f68715d26ff6fb, []int{5, 2}
}

func (m *GetCompanyResponse_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCompanyResponse_Body.Unmarshal(m, b)
}
func (m *GetCompanyResponse_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCompanyResponse_Body.Marshal(b, m, deterministic)
}
func (m *GetCompanyResponse_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCompanyResponse_Body.Merge(m, src)
}
func (m *GetCompanyResponse_Body) XXX_Size() int {
	return xxx_messageInfo_GetCompanyResponse_Body.Size(m)
}
func (m *GetCompanyResponse_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCompanyResponse_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetCompanyResponse_Body proto.InternalMessageInfo

func (m *GetCompanyResponse_Body) GetCompany() *GetCompanyResponse_Company {
	if m != nil {
		return m.Company
	}
	return nil
}

func init() {
	proto.RegisterEnum("personaappapi.company.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*UpdateCompanyRequest)(nil), "personaappapi.company.UpdateCompanyRequest")
	proto.RegisterType((*UpdateCompanyResponse)(nil), "personaappapi.company.UpdateCompanyResponse")
	proto.RegisterType((*UpdateCompanyResponse_Body)(nil), "personaappapi.company.UpdateCompanyResponse.Body")
	proto.RegisterType((*UpdateCompanyActivityFieldsRequest)(nil), "personaappapi.company.UpdateCompanyActivityFieldsRequest")
	proto.RegisterMapType((map[string]*entities.Empty)(nil), "personaappapi.company.UpdateCompanyActivityFieldsRequest.ActivityFieldsEntry")
	proto.RegisterType((*UpdateCompanyActivityFieldsResponse)(nil), "personaappapi.company.UpdateCompanyActivityFieldsResponse")
	proto.RegisterType((*UpdateCompanyActivityFieldsResponse_Body)(nil), "personaappapi.company.UpdateCompanyActivityFieldsResponse.Body")
	proto.RegisterType((*GetCompanyRequest)(nil), "personaappapi.company.GetCompanyRequest")
	proto.RegisterType((*GetCompanyResponse)(nil), "personaappapi.company.GetCompanyResponse")
	proto.RegisterType((*GetCompanyResponse_Company)(nil), "personaappapi.company.GetCompanyResponse.Company")
	proto.RegisterMapType((map[string]*GetCompanyResponse_CompanyActivityField)(nil), "personaappapi.company.GetCompanyResponse.Company.ActivityFieldsEntry")
	proto.RegisterType((*GetCompanyResponse_CompanyActivityField)(nil), "personaappapi.company.GetCompanyResponse.CompanyActivityField")
	proto.RegisterType((*GetCompanyResponse_Body)(nil), "personaappapi.company.GetCompanyResponse.Body")
}

func init() { proto.RegisterFile("company/company.proto", fileDescriptor_13f68715d26ff6fb) }

var fileDescriptor_13f68715d26ff6fb = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x4e, 0xdb, 0x4c,
	0x14, 0xc6, 0x49, 0xb8, 0x9d, 0xe8, 0xe7, 0x0f, 0xd3, 0x40, 0x12, 0x97, 0xd2, 0x28, 0x6c, 0xe8,
	0x45, 0x8e, 0x08, 0x8b, 0xb6, 0x2c, 0xa8, 0x72, 0x31, 0x21, 0x22, 0x24, 0xc8, 0x24, 0x54, 0xea,
	0xc6, 0x35, 0xf1, 0x10, 0xb9, 0x18, 0xcf, 0x74, 0xe2, 0x50, 0x79, 0x57, 0xde, 0xa1, 0xcb, 0xf6,
	0x39, 0xda, 0xae, 0xfb, 0x08, 0x5d, 0x74, 0xdb, 0xd7, 0x60, 0x53, 0x55, 0xb1, 0xc7, 0x10, 0x87,
	0x80, 0x0c, 0x62, 0x85, 0x67, 0xce, 0xf7, 0x9d, 0x39, 0x97, 0xef, 0x1c, 0x02, 0x0b, 0x1d, 0x72,
	0x42, 0x35, 0xcb, 0xc9, 0xf3, 0xbf, 0x12, 0x65, 0xc4, 0x26, 0x68, 0x81, 0x62, 0xd6, 0x23, 0x96,
	0xa6, 0x51, 0xaa, 0x51, 0x43, 0xe2, 0x46, 0x31, 0x85, 0x2d, 0xdb, 0xb0, 0x0d, 0xdc, 0xcb, 0xfb,
	0x1f, 0x1e, 0x5e, 0x5c, 0xee, 0x12, 0xd2, 0x35, 0x71, 0xde, 0x3d, 0x1d, 0xf6, 0x8f, 0xf2, 0x1f,
	0x99, 0x46, 0x07, 0x3e, 0x3c, 0x7b, 0xee, 0xa7, 0x00, 0xc9, 0x36, 0xd5, 0x35, 0x1b, 0x97, 0x3d,
	0x57, 0x0a, 0xfe, 0xd0, 0xc7, 0x3d, 0x1b, 0x15, 0x60, 0xd2, 0x36, 0x6c, 0x13, 0xa7, 0x85, 0xac,
	0xb0, 0x1a, 0x2f, 0x2c, 0x49, 0x9e, 0x23, 0xc9, 0x77, 0x24, 0xed, 0xdb, 0xcc, 0xb0, 0xba, 0x07,
	0x9a, 0xd9, 0xc7, 0x8a, 0x07, 0x45, 0x9b, 0x10, 0xd7, 0x71, 0xaf, 0xc3, 0x0c, 0x6a, 0x1b, 0xc4,
	0x4a, 0x47, 0x42, 0x30, 0x87, 0x09, 0xe8, 0x05, 0xcc, 0x98, 0xa4, 0x4b, 0xd4, 0x3e, 0x33, 0xd3,
	0xd1, 0x10, 0xe4, 0xe9, 0x01, 0xba, 0xcd, 0xcc, 0xdc, 0x37, 0x01, 0x16, 0x46, 0xb2, 0xe8, 0x51,
	0x62, 0xf5, 0x30, 0x2a, 0x02, 0x60, 0xc6, 0x08, 0x53, 0x3b, 0x44, 0xf7, 0x72, 0x99, 0x2b, 0x64,
	0xa5, 0xb1, 0x45, 0x94, 0xe4, 0x01, 0xb0, 0x4c, 0x74, 0xbc, 0x3d, 0xa1, 0xcc, 0x62, 0xff, 0x80,
	0xaa, 0x10, 0x3b, 0x24, 0xba, 0xc3, 0xd3, 0x59, 0xbb, 0x86, 0x3c, 0xf6, 0x79, 0xa9, 0x44, 0x74,
	0x67, 0x7b, 0x42, 0x71, 0x1d, 0x88, 0x53, 0x10, 0x1b, 0x9c, 0x4b, 0x00, 0x33, 0x8c, 0x03, 0x72,
	0x7f, 0x05, 0xc8, 0x05, 0xa8, 0xc5, 0x8e, 0x6d, 0x9c, 0x1a, 0xb6, 0xb3, 0x65, 0x60, 0x53, 0xef,
	0xf9, 0xdd, 0x38, 0x85, 0xff, 0x35, 0x6e, 0x50, 0x8f, 0x5c, 0x4b, 0x5a, 0xc8, 0x46, 0x57, 0xe3,
	0x85, 0xdd, 0x30, 0xe1, 0x8c, 0xf5, 0x29, 0x05, 0x6f, 0x65, 0xcb, 0x66, 0x8e, 0x32, 0xa7, 0x05,
	0x2e, 0xc5, 0x77, 0xf0, 0x60, 0x0c, 0x0c, 0x25, 0x20, 0x7a, 0x8c, 0x1d, 0xb7, 0x9c, 0xb3, 0xca,
	0xe0, 0x13, 0xad, 0xc3, 0xe4, 0xe9, 0xa0, 0x27, 0xbc, 0x4a, 0x8f, 0x46, 0xc2, 0xba, 0x50, 0xa5,
	0x7c, 0x42, 0x6d, 0x47, 0xf1, 0xb0, 0x1b, 0x91, 0x97, 0x42, 0xee, 0x97, 0x00, 0x2b, 0x37, 0x06,
	0x7b, 0x7f, 0x8d, 0x6c, 0x07, 0x1a, 0xf9, 0xfa, 0x2e, 0x95, 0x0b, 0xdb, 0xd6, 0x15, 0x98, 0xaf,
	0x62, 0x7b, 0x64, 0xa4, 0xe6, 0x20, 0x62, 0xe8, 0xbc, 0x68, 0x11, 0x43, 0xcf, 0x9d, 0xc7, 0x00,
	0x0d, 0xa3, 0xee, 0x2f, 0xd3, 0x4a, 0x20, 0x53, 0xe9, 0x1a, 0xf2, 0xd5, 0xb7, 0x83, 0x89, 0xfd,
	0x89, 0xc0, 0x34, 0x07, 0x8c, 0xc6, 0x8e, 0x92, 0xfe, 0x7a, 0x88, 0xb8, 0x57, 0x7c, 0x01, 0x64,
	0x83, 0x0b, 0x20, 0xea, 0xda, 0x02, 0x23, 0x9e, 0x19, 0x1a, 0xf1, 0x98, 0x6b, 0xf6, 0x87, 0x18,
	0x59, 0x57, 0x35, 0x3e, 0xe9, 0x6a, 0x5c, 0x0e, 0x1f, 0x3f, 0x3f, 0x87, 0xd2, 0xf6, 0x99, 0x10,
	0x56, 0xdc, 0xad, 0xa0, 0xb8, 0x37, 0x6f, 0x1d, 0x4f, 0xe0, 0x99, 0x21, 0xf5, 0x8b, 0x8b, 0x90,
	0x1c, 0x07, 0x11, 0xf7, 0x3d, 0x4d, 0xa1, 0x1d, 0x98, 0xe6, 0xde, 0xf9, 0x1e, 0x5e, 0xbb, 0xf5,
	0xdb, 0x8a, 0xef, 0x61, 0x58, 0xa0, 0x4f, 0x7f, 0x0b, 0x30, 0x7b, 0x21, 0x1e, 0xb4, 0x08, 0xa8,
	0xdd, 0xd8, 0x69, 0x34, 0xdf, 0x34, 0x54, 0x59, 0x51, 0x9a, 0x8a, 0x5a, 0x6e, 0x56, 0xe4, 0xc4,
	0x04, 0xca, 0x40, 0xb2, 0xd6, 0x38, 0x28, 0xd6, 0x6b, 0x15, 0xb5, 0x55, 0x6b, 0xd5, 0x65, 0x75,
	0xab, 0xa9, 0xec, 0x16, 0x5b, 0x89, 0xef, 0xa9, 0xab, 0xa6, 0xba, 0xdc, 0xa8, 0xb6, 0xb6, 0x13,
	0x3f, 0x52, 0xe8, 0x31, 0x88, 0xbe, 0xa9, 0x22, 0xef, 0x97, 0x95, 0xda, 0x5e, 0xab, 0xd6, 0x6c,
	0xf8, 0xdc, 0x2f, 0xe9, 0xeb, 0x00, 0xdc, 0xc3, 0xd7, 0x34, 0x5a, 0x82, 0x94, 0x0f, 0xa8, 0x37,
	0xab, 0x4d, 0xb5, 0xad, 0xd4, 0x7d, 0xfa, 0xa7, 0xcc, 0x58, 0x2b, 0xe7, 0x9e, 0x65, 0x0a, 0xe7,
	0x11, 0x98, 0xdf, 0xf3, 0x6a, 0x54, 0xa4, 0xd4, 0xd7, 0xef, 0x7b, 0xf8, 0x2f, 0x30, 0xd8, 0xe8,
	0x59, 0xb8, 0x3d, 0xee, 0x4e, 0xae, 0xf8, 0xfc, 0x36, 0x4b, 0x1f, 0x7d, 0x16, 0xe0, 0xe1, 0x0d,
	0x5b, 0x04, 0xbd, 0xba, 0xf3, 0xce, 0x16, 0x37, 0xee, 0xbe, 0xb4, 0x90, 0x06, 0x70, 0xa9, 0x12,
	0xb4, 0x1a, 0x42, 0x48, 0xde, 0x9b, 0x4f, 0x42, 0x4b, 0xae, 0x24, 0xc3, 0x22, 0xb1, 0x4c, 0xc3,
	0xc2, 0x43, 0x14, 0xa9, 0x43, 0x18, 0x2e, 0xc5, 0xab, 0x8c, 0x76, 0x38, 0xfc, 0xed, 0xf2, 0xa5,
	0x35, 0x4f, 0x8f, 0xbb, 0xf9, 0x2e, 0xa3, 0x1d, 0x8d, 0x1a, 0xfe, 0x4f, 0x9d, 0xc3, 0x29, 0xf7,
	0xbf, 0xfd, 0xfa, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x8e, 0x65, 0x4e, 0x04, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonaAppCompanyClient is the client API for PersonaAppCompany service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppCompanyClient interface {
	UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*UpdateCompanyResponse, error)
	UpdateCompanyActivityFields(ctx context.Context, in *UpdateCompanyActivityFieldsRequest, opts ...grpc.CallOption) (*UpdateCompanyActivityFieldsResponse, error)
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*GetCompanyResponse, error)
}

type personaAppCompanyClient struct {
	cc *grpc.ClientConn
}

func NewPersonaAppCompanyClient(cc *grpc.ClientConn) PersonaAppCompanyClient {
	return &personaAppCompanyClient{cc}
}

func (c *personaAppCompanyClient) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*UpdateCompanyResponse, error) {
	out := new(UpdateCompanyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/UpdateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCompanyClient) UpdateCompanyActivityFields(ctx context.Context, in *UpdateCompanyActivityFieldsRequest, opts ...grpc.CallOption) (*UpdateCompanyActivityFieldsResponse, error) {
	out := new(UpdateCompanyActivityFieldsResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/UpdateCompanyActivityFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCompanyClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*GetCompanyResponse, error) {
	out := new(GetCompanyResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.company.PersonaAppCompany/GetCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppCompanyServer is the server API for PersonaAppCompany service.
type PersonaAppCompanyServer interface {
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*UpdateCompanyResponse, error)
	UpdateCompanyActivityFields(context.Context, *UpdateCompanyActivityFieldsRequest) (*UpdateCompanyActivityFieldsResponse, error)
	GetCompany(context.Context, *GetCompanyRequest) (*GetCompanyResponse, error)
}

// UnimplementedPersonaAppCompanyServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppCompanyServer struct {
}

func (*UnimplementedPersonaAppCompanyServer) UpdateCompany(ctx context.Context, req *UpdateCompanyRequest) (*UpdateCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}
func (*UnimplementedPersonaAppCompanyServer) UpdateCompanyActivityFields(ctx context.Context, req *UpdateCompanyActivityFieldsRequest) (*UpdateCompanyActivityFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompanyActivityFields not implemented")
}
func (*UnimplementedPersonaAppCompanyServer) GetCompany(ctx context.Context, req *GetCompanyRequest) (*GetCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}

func RegisterPersonaAppCompanyServer(s *grpc.Server, srv PersonaAppCompanyServer) {
	s.RegisterService(&_PersonaAppCompany_serviceDesc, srv)
}

func _PersonaAppCompany_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/UpdateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).UpdateCompany(ctx, req.(*UpdateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCompany_UpdateCompanyActivityFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyActivityFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).UpdateCompanyActivityFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/UpdateCompanyActivityFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).UpdateCompanyActivityFields(ctx, req.(*UpdateCompanyActivityFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCompany_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCompanyServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.company.PersonaAppCompany/GetCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCompanyServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaAppCompany_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.company.PersonaAppCompany",
	HandlerType: (*PersonaAppCompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCompany",
			Handler:    _PersonaAppCompany_UpdateCompany_Handler,
		},
		{
			MethodName: "UpdateCompanyActivityFields",
			Handler:    _PersonaAppCompany_UpdateCompanyActivityFields_Handler,
		},
		{
			MethodName: "GetCompany",
			Handler:    _PersonaAppCompany_GetCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "company/company.proto",
}
