// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: city/city.proto

package personaappapi_city

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Get cities
type GetCitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rating *wrappers.Int32Value  `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Filter *wrappers.StringValue `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *GetCitiesRequest) Reset() {
	*x = GetCitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesRequest) ProtoMessage() {}

func (x *GetCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCitiesRequest) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{0}
}

func (x *GetCitiesRequest) GetRating() *wrappers.Int32Value {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *GetCitiesRequest) GetFilter() *wrappers.StringValue {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetCitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities []*City `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
}

func (x *GetCitiesResponse) Reset() {
	*x = GetCitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesResponse) ProtoMessage() {}

func (x *GetCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCitiesResponse) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{1}
}

func (x *GetCitiesResponse) GetCities() []*City {
	if x != nil {
		return x.Cities
	}
	return nil
}

// Upsert city
type UpsertCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryCode int32                 `protobuf:"varint,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Rating      int32                 `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *UpsertCityRequest) Reset() {
	*x = UpsertCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCityRequest) ProtoMessage() {}

func (x *UpsertCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCityRequest.ProtoReflect.Descriptor instead.
func (*UpsertCityRequest) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertCityRequest) GetId() *wrappers.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpsertCityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertCityRequest) GetCountryCode() int32 {
	if x != nil {
		return x.CountryCode
	}
	return 0
}

func (x *UpsertCityRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UpsertCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpsertCityResponse) Reset() {
	*x = UpsertCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCityResponse) ProtoMessage() {}

func (x *UpsertCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCityResponse.ProtoReflect.Descriptor instead.
func (*UpsertCityResponse) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertCityResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delete city
type DeleteCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCityRequest) Reset() {
	*x = DeleteCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityRequest) ProtoMessage() {}

func (x *DeleteCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityRequest.ProtoReflect.Descriptor instead.
func (*DeleteCityRequest) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteCityResponse) Reset() {
	*x = DeleteCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityResponse) ProtoMessage() {}

func (x *DeleteCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityResponse.ProtoReflect.Descriptor instead.
func (*DeleteCityResponse) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{5}
}

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryCode int32  `protobuf:"varint,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Rating      int32  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_city_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_city_city_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_city_city_proto_rawDescGZIP(), []int{6}
}

func (x *City) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetCountryCode() int32 {
	if x != nil {
		return x.CountryCode
	}
	return 0
}

func (x *City) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_city_city_proto protoreflect.FileDescriptor

var file_city_city_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x69, 0x74, 0x79, 0x2f, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x61, 0x70, 0x70, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x69, 0x74, 0x79, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x34,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x61, 0x70, 0x70, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x52, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x11,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x24,
	0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x65, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x32, 0xa4, 0x02, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x41, 0x70, 0x70, 0x43, 0x69, 0x74, 0x79, 0x12, 0x58, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x24, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x61, 0x70, 0x70, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x61, 0x70, 0x70, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0a, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74,
	0x79, 0x12, 0x25, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x61, 0x70, 0x70, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x61, 0x70, 0x70, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5b, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x25,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x61, 0x70, 0x70, 0x61, 0x70, 0x69, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x61,
	0x70, 0x70, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x0a,
	0x11, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x61,
	0x70, 0x70, 0x42, 0x08, 0x47, 0x72, 0x70, 0x63, 0x43, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_city_city_proto_rawDescOnce sync.Once
	file_city_city_proto_rawDescData = file_city_city_proto_rawDesc
)

func file_city_city_proto_rawDescGZIP() []byte {
	file_city_city_proto_rawDescOnce.Do(func() {
		file_city_city_proto_rawDescData = protoimpl.X.CompressGZIP(file_city_city_proto_rawDescData)
	})
	return file_city_city_proto_rawDescData
}

var file_city_city_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_city_city_proto_goTypes = []interface{}{
	(*GetCitiesRequest)(nil),     // 0: personaappapi.city.GetCitiesRequest
	(*GetCitiesResponse)(nil),    // 1: personaappapi.city.GetCitiesResponse
	(*UpsertCityRequest)(nil),    // 2: personaappapi.city.UpsertCityRequest
	(*UpsertCityResponse)(nil),   // 3: personaappapi.city.UpsertCityResponse
	(*DeleteCityRequest)(nil),    // 4: personaappapi.city.DeleteCityRequest
	(*DeleteCityResponse)(nil),   // 5: personaappapi.city.DeleteCityResponse
	(*City)(nil),                 // 6: personaappapi.city.City
	(*wrappers.Int32Value)(nil),  // 7: google.protobuf.Int32Value
	(*wrappers.StringValue)(nil), // 8: google.protobuf.StringValue
}
var file_city_city_proto_depIdxs = []int32{
	7, // 0: personaappapi.city.GetCitiesRequest.rating:type_name -> google.protobuf.Int32Value
	8, // 1: personaappapi.city.GetCitiesRequest.filter:type_name -> google.protobuf.StringValue
	6, // 2: personaappapi.city.GetCitiesResponse.cities:type_name -> personaappapi.city.City
	8, // 3: personaappapi.city.UpsertCityRequest.id:type_name -> google.protobuf.StringValue
	0, // 4: personaappapi.city.PersonaAppCity.GetCities:input_type -> personaappapi.city.GetCitiesRequest
	2, // 5: personaappapi.city.PersonaAppCity.UpsertCity:input_type -> personaappapi.city.UpsertCityRequest
	4, // 6: personaappapi.city.PersonaAppCity.DeleteCity:input_type -> personaappapi.city.DeleteCityRequest
	1, // 7: personaappapi.city.PersonaAppCity.GetCities:output_type -> personaappapi.city.GetCitiesResponse
	3, // 8: personaappapi.city.PersonaAppCity.UpsertCity:output_type -> personaappapi.city.UpsertCityResponse
	5, // 9: personaappapi.city.PersonaAppCity.DeleteCity:output_type -> personaappapi.city.DeleteCityResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_city_city_proto_init() }
func file_city_city_proto_init() {
	if File_city_city_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_city_city_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_city_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_city_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_city_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_city_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_city_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_city_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_city_city_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_city_city_proto_goTypes,
		DependencyIndexes: file_city_city_proto_depIdxs,
		MessageInfos:      file_city_city_proto_msgTypes,
	}.Build()
	File_city_city_proto = out.File
	file_city_city_proto_rawDesc = nil
	file_city_city_proto_goTypes = nil
	file_city_city_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PersonaAppCityClient is the client API for PersonaAppCity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonaAppCityClient interface {
	// Cities
	GetCities(ctx context.Context, in *GetCitiesRequest, opts ...grpc.CallOption) (*GetCitiesResponse, error)
	UpsertCity(ctx context.Context, in *UpsertCityRequest, opts ...grpc.CallOption) (*UpsertCityResponse, error)
	DeleteCity(ctx context.Context, in *DeleteCityRequest, opts ...grpc.CallOption) (*DeleteCityResponse, error)
}

type personaAppCityClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonaAppCityClient(cc grpc.ClientConnInterface) PersonaAppCityClient {
	return &personaAppCityClient{cc}
}

func (c *personaAppCityClient) GetCities(ctx context.Context, in *GetCitiesRequest, opts ...grpc.CallOption) (*GetCitiesResponse, error) {
	out := new(GetCitiesResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.city.PersonaAppCity/GetCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCityClient) UpsertCity(ctx context.Context, in *UpsertCityRequest, opts ...grpc.CallOption) (*UpsertCityResponse, error) {
	out := new(UpsertCityResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.city.PersonaAppCity/UpsertCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personaAppCityClient) DeleteCity(ctx context.Context, in *DeleteCityRequest, opts ...grpc.CallOption) (*DeleteCityResponse, error) {
	out := new(DeleteCityResponse)
	err := c.cc.Invoke(ctx, "/personaappapi.city.PersonaAppCity/DeleteCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonaAppCityServer is the server API for PersonaAppCity service.
type PersonaAppCityServer interface {
	// Cities
	GetCities(context.Context, *GetCitiesRequest) (*GetCitiesResponse, error)
	UpsertCity(context.Context, *UpsertCityRequest) (*UpsertCityResponse, error)
	DeleteCity(context.Context, *DeleteCityRequest) (*DeleteCityResponse, error)
}

// UnimplementedPersonaAppCityServer can be embedded to have forward compatible implementations.
type UnimplementedPersonaAppCityServer struct {
}

func (*UnimplementedPersonaAppCityServer) GetCities(context.Context, *GetCitiesRequest) (*GetCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCities not implemented")
}
func (*UnimplementedPersonaAppCityServer) UpsertCity(context.Context, *UpsertCityRequest) (*UpsertCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCity not implemented")
}
func (*UnimplementedPersonaAppCityServer) DeleteCity(context.Context, *DeleteCityRequest) (*DeleteCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCity not implemented")
}

func RegisterPersonaAppCityServer(s *grpc.Server, srv PersonaAppCityServer) {
	s.RegisterService(&_PersonaAppCity_serviceDesc, srv)
}

func _PersonaAppCity_GetCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCityServer).GetCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.city.PersonaAppCity/GetCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCityServer).GetCities(ctx, req.(*GetCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCity_UpsertCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCityServer).UpsertCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.city.PersonaAppCity/UpsertCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCityServer).UpsertCity(ctx, req.(*UpsertCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonaAppCity_DeleteCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonaAppCityServer).DeleteCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personaappapi.city.PersonaAppCity/DeleteCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonaAppCityServer).DeleteCity(ctx, req.(*DeleteCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonaAppCity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personaappapi.city.PersonaAppCity",
	HandlerType: (*PersonaAppCityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCities",
			Handler:    _PersonaAppCity_GetCities_Handler,
		},
		{
			MethodName: "UpsertCity",
			Handler:    _PersonaAppCity_UpsertCity_Handler,
		},
		{
			MethodName: "DeleteCity",
			Handler:    _PersonaAppCity_DeleteCity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "city/city.proto",
}
